// Generated by Skyramp v1.3.40 on 2026-08-29 06:03:57.315584325 +0000 UTC m=+758.327408410
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output deep_link_reload.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/deep_link_reload_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/`);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();

    await expect(page).toHaveURL(/\/petclinic\/owners$/);
    await expect(page.locator('#ownersTable > table > tbody > tr')).toHaveCount(10);

    await page.reload();

    await expect(page).toHaveURL(/\/petclinic\/owners$/);
    await expect(page.locator('app-owner-list h2')).toHaveText('Owners');
    await expect(page.locator('#ownersTable > table > tbody > tr')).toHaveCount(10);

    expect(pageErrors).toHaveLength(0);
});
