// Generated by Skyramp v1.3.40 on 2026-08-30 08:44:19.329237342 +0000 UTC m=+766.544718812
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_detail_renders_owner_and_visit_history.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_detail_renders_owner_and_visit_history_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openOwnerDetail } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1111000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    const errors: Error[] = [];
    page.on('pageerror', (error) => { errors.push(error); });
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await expect(page.locator("#ownersTable table > tbody > tr").filter({ has: page.locator("a[href=\"/petclinic/owners/6\"]") }).locator("> td").nth(3)).toHaveText("6085552654");

    await openOwnerDetail(page);
    await expect(page.getByRole("heading", { name: "Pets and visit history" })).toBeVisible();
    await expect(page.locator(".ownerFullName")).toHaveText("Jean Coleman");
    await expect(page.locator("app-pet-list")).toHaveCount(2);
    expect(errors).toHaveLength(0);
});
