// Generated by Skyramp v1.3.40 on 2026-08-29 06:04:02.092015181 +0000 UTC m=+945.583383152
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_detail_pet_nickname_row.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_detail_pet_nickname_row_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1128000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    const ownerResponsePromise = page.waitForResponse("**/petclinic/api/owners/1");
    await page.locator("a[href=\"/petclinic/owners/1\"]").click();
    const ownerResponse = await ownerResponsePromise;

    // The owner detail page is the only place app-pet-list renders, so it is where
    // the Nickname row added by this PR becomes visible to a user.
    expect(ownerResponse.status()).toBe(200);
    await expect(page.getByRole("heading", { name: "Owner Information" })).toBeVisible();

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    // The owner payload that backs the pet list has arrived, so the owner's own
    // details and each pet's Nickname row must be rendered.
    await expect(page.locator("main")).toContainText("George Franklin");
    await expect(page.locator("main")).toContainText("Nickname");
    await expect(page.locator("main")).toContainText("Leo");
});
