// Generated by Skyramp v1.3.40 on 2026-08-30 08:53:44.843638091 +0000 UTC m=+1293.740216612
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_edit_phone_number.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_edit_phone_number_ui_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openOwnersList, openOwnerEditForm, fillOwnerPhoneNumber, submitOwnerEditForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1823000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (e) => pageErrors.push(e.message));

    await page.goto(baseUrl);
    await openOwnersList(page);
    await openOwnerEditForm(page);

    const playwrightRequest0: Record<string, any> = {"phoneNumber": "6085559999"};

    await fillOwnerPhoneNumber(page, getValue(playwrightRequest0, "phoneNumber"));
    await expect(page.getByRole("textbox", { name: "First Name" })).toHaveValue("George");

    const response0 = await submitOwnerEditForm(page);
    expect(response0.status()).toBe(204);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await openOwnersList(page);

    const georgeRow = page.locator("tr", { has: page.locator("a[href=\"/petclinic/owners/1\"]") });
    await expect(georgeRow.locator("td").nth(3)).toHaveText("6085559999");

    expect(pageErrors).toHaveLength(0);
});
