// Generated by Skyramp v1.3.40 on 2026-08-29 09:23:38.48103614 +0000 UTC m=+935.632590042
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_edit_form_prefills.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_edit_form_prefills_trace.zip

// Import of required libraries
import { test, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { expect } from '@playwright/test';
import { openOwnerDetail, openOwnerEditForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1321000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();

    // The owners list renders data fetched from the API, so the browser does
    // receive the owner records.
    await expect(page.getByRole("link", { name: "George Franklin" })).toHaveText("George Franklin");

    await openOwnerDetail(page, "/petclinic/owners/1");

    // Owner Information must show the owner that was just fetched. The component
    // holds the loaded owner (its Edit Owner button routes to /owners/1/edit), but
    // the bound cell is rendered empty.
    await expect(page.locator(".ownerFullName")).toHaveText("George Franklin");

    await openOwnerEditForm(page);

    // The Edit Owner form must be pre-filled from the loaded owner. Without this,
    // the required fields stay empty, Update Owner stays disabled, and no save --
    // successful or rejected -- can be submitted from this screen.
    await expect(page.locator("#firstName")).toHaveValue("George");
    await expect(page.locator("#telephone")).toHaveValue("6085551023");
    await expect(page.getByRole("button", { name: "Update Owner" })).toBeEnabled();
});
