// Generated by Skyramp v1.3.40 on 2026-08-30 08:45:00.691962196 +0000 UTC m=+783.190393100
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner-detail-renders-owner-and-pets.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_detail_renders_owner_and_pets_trace_1.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.goto(`${baseUrl}/owners/1`);
    await expect(page).toHaveURL(/\/petclinic\/owners\/1$/);

    // The owner record is fetched successfully, so the detail page must render it.
    await expect(page.locator(".ownerFullName")).toHaveText("George Franklin");
    await expect(page.getByRole("row", { name: "Address" })).toContainText("110 W. Liberty St.");

    // Each of the owner's pets renders a row carrying its Add Visit control.
    await expect(page.locator("app-pet-list")).toContainText("Leo");
});
