// Generated by Skyramp v1.3.40 on 2026-08-30 08:51:27.561351953 +0000 UTC m=+1141.171193836
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_detail_shows_pets.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_detail_shows_pets_trace_clean.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await page.locator("a[href=\"/petclinic/owners/1\"]").click();

    // Landed on the owner detail route for owner 1.
    await expect(page).toHaveURL(`${baseUrl}/petclinic/owners/1`);

    // GET /petclinic/api/owners/1 returns George Franklin with one pet, "Leo",
    // so the detail page must render both. These currently fail: OwnerDetailComponent
    // assigns `owner` in a subscribe callback without calling ChangeDetectorRef.markForCheck(),
    // so under Angular's zoneless change detection the view is never re-rendered.
    await expect(page.locator(".ownerFullName")).toHaveText("George Franklin");
    await expect(page.locator("app-owner-detail")).toContainText("110 W. Liberty St.");
    await expect(page.locator("app-owner-detail app-pet-list")).toHaveCount(1);
    await expect(page.locator("app-owner-detail")).toContainText("Leo");
});
