// Generated by Skyramp v1.3.44 on 2026-09-08 19:17:03.218307305 +0000 UTC m=+1463.564123142
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_add_phone_validation.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_add_phone_validation_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { fillOwnerPhoneNumber } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(98000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/`);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await page.getByRole("button", { name: "Add Owner" }).click();
    await fillOwnerPhoneNumber(page, "abc");
    await expect(page).toHaveURL(`${baseUrl}/petclinic/owners/add`);
    await expect(page.getByText("Phone number only accepts")).toContainText("Phone number only accepts digits");
    await expect(page.locator("#phoneNumber")).toHaveValue("abc");
    await expect(page.locator("#phoneNumber")).toHaveClass(/is-invalid/);
    await expect(page.getByRole("button", { name: "Add Owner" })).toBeDisabled();
});
