// Generated by Skyramp v1.3.40 on 2026-08-30 08:49:00.458391185 +0000 UTC m=+1680.329896128
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner-create-without-email-blank-cell.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_create_without_email_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openNewOwnerForm, fillOwnerFormWithoutEmail, submitOwnerForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(153000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const playwrightRequest0: Record<string, any> = {
        "address": "3 Legacy Lane",
        "city": "Madison",
        "firstName": "Noemi",
        "lastName": "Optional",
        "telephone": "6085550222"
    };

    await page.goto(baseUrl);
    await openNewOwnerForm(page);

    // The Email box is deliberately left untouched -- an owner with no email at all.
    await fillOwnerFormWithoutEmail(
        page,
        getValue(playwrightRequest0, "firstName"),
        getValue(playwrightRequest0, "lastName"),
        getValue(playwrightRequest0, "address"),
        getValue(playwrightRequest0, "city"),
        getValue(playwrightRequest0, "telephone"),
    );

    // Email is optional, so the form is submittable with it empty.
    await expect(page.locator("#email")).toHaveValue("");
    await expect(page.getByRole("button", { name: "Add Owner" })).toBeEnabled();

    const response0 = await submitOwnerForm(page);

    // The owner is created even though no email was supplied.
    expect(response0.status()).toBe(201);
    const created0 = await response0.json();
    expect(created0.firstName).toBe("Noemi");
    expect(created0.lastName).toBe("Optional");
    expect(created0.address).toBe("3 Legacy Lane");
    expect(created0.city).toBe("Madison");
    expect(created0.telephone).toBe("6085550222");
    expect(created0.id).toBeGreaterThan(0);
    // No email was sent, so the server returns the record without the field.
    expect(created0.email).toBeUndefined();
    expect(created0.pets.length).toBe(0);

    // The successful save redirects to the owners list.
    await expect(page).toHaveURL(/\/petclinic\/owners$/);
    await expect(page.getByRole("link", { name: "Noemi Optional" }).first()).toBeVisible();

    // The Email column is present ...
    await expect(page.getByRole("row", { name: "Name Address City Telephone" })).toContainText("Email");
    // ... and this owner's Email cell renders blank rather than "undefined" or an error.
    const noemiRow = page.locator("#ownersTable table tbody tr").filter({ hasText: "Noemi Optional" }).first();
    await expect(noemiRow.locator("td").nth(4)).toHaveText("");
});
