// Generated by Skyramp v1.3.40 on 2026-08-29 04:20:06.619256911 +0000 UTC m=+1111.229765097
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_add_email.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_add_email_ui_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(65000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Add New" }).click();

    const playwrightRequest0: Record<string, any> = {
        "address": "2 Compiler Ct",
        "city": "Madison",
        "email": "grace.hopper@example.com",
        "firstName": "Grace",
        "lastName": "Hopper",
        "telephone": "6085550120"
    };

    await page.locator("#firstName").fill(getValue(playwrightRequest0, "firstName"));
    await page.locator("#lastName").fill(getValue(playwrightRequest0, "lastName"));
    await page.locator("#address").fill(getValue(playwrightRequest0, "address"));
    await page.locator("#city").fill(getValue(playwrightRequest0, "city"));
    await page.locator("#telephone").fill(getValue(playwrightRequest0, "telephone"));
    await page.locator("#email").fill(getValue(playwrightRequest0, "email"));
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/petclinic/api/owners**");
    await page.getByRole("button", { name: "Add Owner" }).click();
    const response0 = await responsePromise0;
    const createdOwner = await response0.json();

    expect(response0.status()).toBe(201);
    expect(getValue(createdOwner, "firstName")).toBe(getValue(playwrightRequest0, "firstName"));
    expect(getValue(createdOwner, "lastName")).toBe(getValue(playwrightRequest0, "lastName"));
    expect(getValue(createdOwner, "address")).toBe(getValue(playwrightRequest0, "address"));
    expect(getValue(createdOwner, "city")).toBe(getValue(playwrightRequest0, "city"));
    expect(getValue(createdOwner, "telephone")).toBe(getValue(playwrightRequest0, "telephone"));
    expect(getValue(createdOwner, "email")).toBe(getValue(playwrightRequest0, "email"));
    expect(getValue(createdOwner, "id")).toBeGreaterThan(0);

    await expect(page).toHaveURL(`${baseUrl}/petclinic/owners`);

    const createdRow = page
        .locator("#ownersTable table > tbody > tr")
        .filter({ has: page.getByRole("link", { name: "Grace Hopper" }) })
        .last();
    await expect(createdRow).toContainText(getValue(playwrightRequest0, "email"));
    await expect(createdRow).toContainText(getValue(playwrightRequest0, "telephone"));
});
