// Generated by Skyramp v1.3.40 on 2026-08-29 05:39:34.185458946 +0000 UTC m=+692.294972270
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_edit_form_phone_prefill.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_edit_form_phone_prefill_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(904000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await page.locator("a[href=\"/petclinic/owners/1\"]").click();
    await page.getByRole("button", { name: "Edit Owner" }).click();
    await expect(page).toHaveURL(/\/petclinic\/owners\/1\/edit$/);
    await expect(page.getByRole("textbox", { name: "Phone" })).toHaveValue("6085551023");
    await expect(page.getByRole("textbox", { name: "First Name" })).toHaveValue("George");
});
