// Generated by Skyramp v1.3.40 on 2026-08-30 08:47:21.272770506 +0000 UTC m=+939.644879228
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_search_partial_last_name_match.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_search_partial_last_name_match_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { searchOwnersByLastName } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await searchOwnersByLastName(page, "Davis");
    await expect(page.getByRole("link", { name: "Betty Davis" })).toBeVisible();
    await expect(page.getByRole("link", { name: "Harold Davis" })).toBeVisible();
    await expect(page.getByRole("link", { name: "George Franklin" })).toHaveCount(0);
    await expect(page.locator("#ownersTable tbody tr td.ownerFullName")).toHaveCount(2);
    await expect(page.locator(".alert.alert-info")).toHaveCount(0);
});
