// Generated by Skyramp v1.3.40 on 2026-09-02 08:07:25.507160951 +0000 UTC m=+1349.377120280
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_long_value_no_midword_wrap.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_long_value_no_midword_wrap_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }, testInfo) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page, testInfo);

    const pageErrors: string[] = [];
    page.on('pageerror', (error: Error) => pageErrors.push(error.message));

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await page.waitForLoadState('networkidle');
    await page.locator("#ownersTable").waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.getByText("NameAddressCityTelephonePetsGeorge Franklin110 W. Liberty St.Madison6085551023")).toHaveScreenshot("owners-table-columns.png", { maxDiffPixelRatio: 0.005 });
    await expect(page.locator("#ownersTable table tbody td")).toHaveCount(50);
    await expect(page.getByRole("link", { name: "Eduardo Rodriquez" })).toHaveText("Eduardo Rodriquez");
    await expect(page.getByRole("cell", { name: "2749 Blackhawk Trail" })).toHaveText("2749 Blackhawk Trail");
    await expect(page.getByRole("cell", { name: "2335 Independence La." })).toHaveText("2335 Independence La.");

    const overflowingCells = await page.evaluate(() => {
        const cells = Array.from(document.querySelectorAll("#ownersTable table tbody td"));
        return cells
            .filter((cell) => cell.scrollWidth > cell.clientWidth + 1)
            .map((cell) => (cell.textContent || "").trim());
    });
    expect(overflowingCells, "no owner name or address cell may overflow its column").toEqual([]);

    expect(pageErrors, 'no uncaught page errors').toEqual([]);
});
