// Generated by Skyramp v1.3.40 on 2026-08-30 08:48:06.333458062 +0000 UTC m=+1003.065087758
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_edit_telephone_rejection_shows_raw_object.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_edit_telephone_rejection_shows_raw_object_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { fillOwnerForm, submitEditOwnerForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(325000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await page.locator("a[href=\"/petclinic/owners/1\"]").click();
    await page.getByRole("button", { name: "Edit Owner" }).click();
    await page.waitForTimeout(3000);

    const playwrightRequest0: Record<string, any> = {
        "address": "110 W. Liberty St.",
        "city": "Madison",
        "firstName": "George",
        "lastName": "Franklin",
        "telephone": "12345"
    };

    await fillOwnerForm(
        page,
        getValue(playwrightRequest0, "firstName"),
        getValue(playwrightRequest0, "lastName"),
        getValue(playwrightRequest0, "address"),
        getValue(playwrightRequest0, "city"),
        getValue(playwrightRequest0, "telephone")
    );

    const response0 = await submitEditOwnerForm(page);

    expect(response0.status()).toBe(400);
    const errorBody0 = await response0.json();
    expect(errorBody0.status).toBe(400);
    expect(errorBody0.title).toBe("MethodArgumentNotValidException");
    expect(errorBody0.detail).toBe("The request contains invalid or missing parameters");
    expect(errorBody0.schemaValidationErrors.length).toBe(2);
    expect(errorBody0.schemaValidationErrors[0].field).toBe("telephone");
    expect(errorBody0.schemaValidationErrors[0].rejectedValue).toBe(getValue(playwrightRequest0, "telephone"));
    expect(errorBody0.schemaValidationErrors[2]).toBeUndefined();

    await expect(page.getByRole("heading", { name: "Edit Owner" })).toBeVisible();
    await expect(page.getByRole("textbox", { name: "Telephone" })).toHaveValue("12345");

    await expect(
        page.locator(".alert-danger"),
        "owner-edit.component.html:22 defines an errorMessage banner, but the view is never re-rendered after the error callback assigns it"
    ).toBeVisible();
    await expect(
        page.locator(".alert-danger"),
        "HttpErrorHandler interpolates the JSON error body into a template literal, producing [object Object] instead of the telephone field message the API returned"
    ).toContainText("telephone");
});
