// Generated by Skyramp v1.3.40 on 2026-08-29 09:17:30.668285999 +0000 UTC m=+553.320334237
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_detail_page_renders_owner_data.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_detail_page_renders_owner_data_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await page.waitForLoadState('networkidle');
    await page.locator('#ownersTable').waitFor({ state: 'visible', timeout: 10000 });
    await page.locator("a[href=\"/petclinic/owners/1\"]").click();
    await page.waitForLoadState('networkidle');
    await page.locator('app-owner-detail').waitFor({ state: 'visible', timeout: 10000 });
    await expect(page).toHaveURL(/\/petclinic\/owners\/1$/);
    await expect(page.getByRole("heading", { name: "Owner Information" })).toBeVisible();

    // GET /petclinic/api/owners/1 returns owner "George Franklin" with pet "Leo",
    // so the Owner Information table must render that name and the pet must appear
    // under "Pets and Visits".
    const ownerInformationTable = page.locator("app-owner-detail table").first();
    await expect(ownerInformationTable).toContainText("George Franklin");
    await expect(ownerInformationTable).toContainText("110 W. Liberty St.");
    await expect(page.locator("app-owner-detail")).toContainText("Leo");
});
