// Generated by Skyramp v1.3.44 on 2026-09-08 19:21:56.298827861 +0000 UTC m=+1756.776828918
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_search_no_match_shows_message.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_search_no_match_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { searchOwnersByLastName } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(71000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (error) => pageErrors.push(error.message));

    await page.goto(`${baseUrl}/`);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await expect(page).toHaveURL(`${baseUrl}/petclinic/owners`);
    await expect(page.getByRole("link", { exact: true, name: "Eduardo Rodriquez" })).toBeVisible();
    await expect(page.locator("#ownersTable .ownerFullName")).toHaveCount(10);
    await searchOwnersByLastName(page, "Zzzznosuchowner");
    await expect(page.getByText("No owners with LastName")).toContainText("No owners with LastName starting with \"Zzzznosuchowner\"");
    await expect(page.getByRole("link", { exact: true, name: "Eduardo Rodriquez" })).toBeHidden();
    await expect(page.locator("#ownersTable .ownerFullName")).toHaveCount(0);

    expect(pageErrors, 'uncaught page errors').toEqual([]);
});
