// Generated by Skyramp v1.3.40 on 2026-08-30 08:50:31.144179486 +0000 UTC m=+1084.754021349
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_list_pet_count_column.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_list_pet_count_column_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();

    // The owners list rendered.
    await expect(page).toHaveURL(`${baseUrl}/petclinic/owners`);
    await expect(page.locator("#ownersTable tbody tr").first()).toBeVisible();

    // This PR adds the "No. of pets" column as the 5th column of the owners table.
    await expect(page.locator("#ownersTable thead th").nth(4)).toHaveText("No. of pets");

    // Seed data: George Franklin owns 1 pet (Leo) and Jean Coleman owns 2 (Max, Samantha),
    // as returned by GET /petclinic/api/owners/1 and /owners/6. The list must show those counts.
    // These currently fail with "0": OwnerRestControllerV1.listOwners strips the pets array
    // from every owner in the collection response, so `owner.pets?.length || 0` always yields 0.
    const georgeRow = page.locator("#ownersTable tbody tr", { hasText: "George Franklin" });
    await expect(georgeRow.locator("td").nth(4)).toHaveText("1");

    const jeanRow = page.locator("#ownersTable tbody tr", { hasText: "Jean Coleman" });
    await expect(jeanRow.locator("td").nth(4)).toHaveText("2");
});
