// Generated by Skyramp v1.3.40 on 2026-08-29 04:47:24.259368768 +0000 UTC m=+587.664477287
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_search_filters_then_restores_full_list.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_search_filters_then_restores_full_list_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(84000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();

    // One .ownerFullName cell is rendered per owner row, so its count is the row count.
    const ownerRows = page.locator(".ownerFullName");
    await expect(ownerRows.first()).toBeVisible();
    const unfilteredOwnerCount = await ownerRows.count();
    expect(unfilteredOwnerCount).toBeGreaterThan(2);

    await page.locator("#lastName").fill("Davis");
    await page.getByRole("button", { name: "Find Owner" }).click();
    await expect(page.getByRole("link", { name: "Betty Davis" })).toBeVisible();
    await expect(page.getByRole("link", { name: "Harold Davis" })).toBeVisible();
    // Searching "Davis" must narrow the table to exactly the two Davis owners.
    await expect(ownerRows).toHaveCount(2);
    await expect(page.getByRole("link", { name: "George Franklin" })).toHaveCount(0);

    await page.locator("#lastName").fill("");
    await page.getByRole("button", { name: "Find Owner" }).click();
    await expect(page.getByRole("link", { name: "George Franklin" })).toBeVisible();
    await expect(page.getByRole("link", { name: "Carlos Estaban" })).toBeVisible();
    // Clearing the box restores the full list -- same row count as before filtering,
    // which also catches rows being duplicated or appended instead of replaced.
    await expect(ownerRows).toHaveCount(unfilteredOwnerCount);
});
