// Generated by Skyramp v1.3.40 on 2026-09-02 08:05:40.076197573 +0000 UTC m=+1546.087003840
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner-detail-email-visible.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_detail_email_visible_trace.zip

// Import of required libraries
import { expect, test, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openOwnersList } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(2524000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await openOwnersList(page, baseUrl);

    // Owners list: the Email column added by this change renders the owner's address.
    const ownerRow = page.locator('#ownersTable tbody tr').filter({ hasText: 'George Franklin' });
    await expect(ownerRow).toContainText('george.franklin@example.com');

    await page.locator("a[href=\"/petclinic/owners/1\"]").click();

    // Owner detail: the PR states the email field appears on the owner detail view.
    // The Email row renders, but its value cell is empty because OwnerDetailComponent
    // never notifies change detection after getOwnerById resolves, so this fails.
    const emailRow = page
        .locator('app-owner-detail table tr')
        .filter({ has: page.locator('th', { hasText: /^Email$/ }) });
    await expect(emailRow.locator('td')).toHaveText('george.franklin@example.com');
});
