// Generated by Skyramp v1.3.40 on 2026-08-30 08:48:53.944228266 +0000 UTC m=+1027.738032882
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_detail_pet_nickname_row.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_detail_pet_nickname_row_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openOwnersSearchList, openOwnerDetail } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1114000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await openOwnersSearchList(page);
    await openOwnerDetail(page, "/petclinic/owners/1");

    await expect(page).toHaveURL(`${baseUrl}/petclinic/owners/1`);
    await expect(page.getByRole("heading", { name: "Owner Information" })).toBeVisible();

    // The owner detail page must render the owner it fetched.
    await expect(page.locator(".ownerFullName")).toHaveText("George Franklin");

    // pet-list.component.html renders one <dt>Nickname</dt>/<dd>{{ pet.nickname }}</dd>
    // row per pet, so the owner's pets and the new Nickname row must both be visible.
    await expect(page.locator("main")).toContainText("Leo");
    await expect(page.locator("main")).toContainText("Nickname");
});
