// Generated by Skyramp v1.3.40 on 2026-08-29 09:17:34.820127767 +0000 UTC m=+557.472176005
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_search_last_name_pet_count.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_search_last_name_pet_count_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { searchOwnersByLastName } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(82000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await page.waitForLoadState('networkidle');
    await page.locator('#ownersTable').waitFor({ state: 'visible', timeout: 10000 });
    await searchOwnersByLastName(page, "Davis");
    await expect(page.getByRole("link", { name: "Betty Davis" })).toBeVisible();
    await expect(page.getByRole("link", { name: "Harold Davis" })).toBeVisible();
    await expect(page.getByRole("link", { name: "George Franklin" })).toHaveCount(0);
    await expect(page.locator("#ownersTable table tbody tr")).toHaveCount(2);

    // Betty Davis (owner 2) owns one pet ("Basil") per GET /petclinic/api/owners/2,
    // so the "No. of pets" column must read 1 on the filtered result too.
    const bettyDavisRow = page
        .locator("#ownersTable tbody tr")
        .filter({ hasText: "Betty Davis" });
    await expect(bettyDavisRow.locator("td").nth(4)).toHaveText("1");
});
