// Generated by Skyramp v1.3.40 on 2026-09-02 08:05:55.686429445 +0000 UTC m=+1259.556388754
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_initial_load_no_alert_flash.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_initial_load_no_alert_flash_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (error: Error) => pageErrors.push(error.message));

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await page.waitForLoadState('networkidle');
    await page.locator("#ownersTable").waitFor({ state: 'visible', timeout: 10000 });
    await expect(page.locator("#ownersTable table tbody td")).toHaveCount(50);
    await expect(page.getByText("NameAddressCityTelephonePetsGeorge Franklin110 W. Liberty St.Madison6085551023")).toBeVisible();
    await expect(page.locator("#ownersTable")).toBeVisible();
    await expect(page.locator("app-owner-list .alert")).toHaveCount(0);
    await expect(page.getByText("No owners found with a last")).toHaveCount(0);
    await expect(page.locator("#lastName")).toHaveValue("");

    expect(pageErrors, 'no uncaught page errors').toEqual([]);
});
