// Generated by Skyramp v1.3.40 on 2026-08-30 08:46:10.370910928 +0000 UTC m=+877.586392398
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_list_add_new_owner_flow.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_list_add_new_owner_flow_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openNewOwnerForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(72000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    const errors: Error[] = [];
    page.on('pageerror', (error) => { errors.push(error); });
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await expect(page.locator("#ownersTable table > tbody > tr > td:first-child > a")).toHaveCount(10);

    await openNewOwnerForm(page);
    await expect(page.getByRole("heading", { name: "New Owner" })).toHaveText("New Owner");
    await expect(page.getByRole("button", { name: "Add Owner" })).toBeDisabled();
    expect(errors).toHaveLength(0);
});
