// Generated by Skyramp v1.3.44 on 2026-09-08 19:12:39.803105005 +0000 UTC m=+1229.231426169
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_sort_by_city.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_sort_by_city_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { sortOwnersByCity } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(195000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/`);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await expect(page.locator("#sortByCity")).toBeVisible();

    // Direct-child selector: the Pets column nests a <tr> per pet inside its <td>,
    // so "#ownersTable table tbody tr" matches 23 rows, not the 10 owner rows.
    const cityCells = page.locator("#ownersTable > table > tbody > tr > td:nth-child(3)");
    await expect(cityCells).toHaveCount(10);

    await sortOwnersByCity(page);

    // The PR requires the list to be ordered by city once the City header is clicked.
    await expect(cityCells).toHaveCount(10);
    const cities = (await cityCells.allTextContents()).map((city) => city.trim());
    expect(cities).toEqual([...cities].sort((a, b) => a.localeCompare(b)));
    expect(cities[1], "second row city").toBe("Madison");
    expect(cities[cities.length - 1], "last row city").toBe("Windsor");
});
