// Generated by Skyramp v1.3.40 on 2026-08-29 04:49:25.621215116 +0000 UTC m=+649.825251263
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_list_clear_search_restores_full_list.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_list_clear_search_restores_full_list_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(97000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await page.locator("#lastName").fill("Davis");
    await page.getByRole("button", { name: "Find Owner" }).click();
    await expect(page.getByRole("row", { name: "Betty Davis 638 Cardinal Ave" })).toContainText("Betty Davis");
    await expect(page.getByRole("row", { name: "Harold Davis 563 Friendly St" })).toContainText("Harold Davis");
    await expect(page.getByRole("link", { name: "George Franklin" })).toHaveCount(0);
    await page.locator("#clearSearch").click();
    await expect(page.getByRole("row", { name: "George Franklin 110 W." })).toContainText("George Franklin");
    await expect(page.getByRole("row", { name: "Carlos Estaban 2335" })).toContainText("Carlos Estaban");
    await expect(page.locator("#lastName")).toHaveValue("");
    await expect(page.locator("#ownersTable tbody > tr")).toHaveCount(10);
});
