// Generated by Skyramp v1.3.40 on 2026-09-02 08:06:38.612382903 +0000 UTC m=+1275.078855980
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_detail_pets_visit_history_render.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_detail_pets_visit_history_render_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openOwnerDetail } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1729000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (error) => pageErrors.push(error.message));

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await openOwnerDetail(page);

    await expect(page).toHaveURL(`${baseUrl}/petclinic/owners/1`);

    // The section this PR renamed still carries its new label.
    await expect(page.getByRole("heading", { name: "Pets and visit history" })).toHaveText("Pets and visit history");

    // The section must actually show the owner and the owner's pets.
    await expect(page.locator("b.ownerFullName")).toHaveText("George Franklin");
    await expect(page.locator("app-owner-detail")).toContainText("Leo");

    expect(pageErrors, 'uncaught page errors').toEqual([]);
});
