// Generated by Skyramp v1.3.40 on 2026-08-30 08:40:42.969045606 +0000 UTC m=+558.912109809
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_search_then_sort_by_city.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_search_then_sort_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { searchOwnersByLastName, sortOwnersByCity } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();

    const ownerRows = page.locator("#ownersTable tbody > tr");
    const nameCells = page.locator("#ownersTable tbody > tr td:nth-child(1)");
    const cityCells = page.locator("#ownersTable tbody > tr td:nth-child(3)");

    await searchOwnersByLastName(page, "Davis");

    await expect(ownerRows).toHaveCount(2);
    await expect(nameCells.nth(0)).toHaveText("Betty Davis");
    await expect(nameCells.nth(1)).toHaveText("Harold Davis");

    await sortOwnersByCity(page);

    await expect(page.locator("#lastName")).toHaveValue("Davis");
    await expect(ownerRows).toHaveCount(2);
    await expect(nameCells.nth(0)).toHaveText("Betty Davis");
    await expect(cityCells.nth(0)).toHaveText("Sun Prairie");
    await expect(cityCells.nth(1)).toHaveText("Windsor");

    expect(pageErrors).toHaveLength(0);
});
