// Generated by Skyramp v1.3.40 on 2026-08-30 08:53:52.707931355 +0000 UTC m=+1301.604509870
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_detail_renders_phone.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_detail_renders_phone_ui_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openOwnersList } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (e) => pageErrors.push(e.message));

    await page.goto(baseUrl);
    await openOwnersList(page);
    await page.locator("a[href=\"/petclinic/owners/2\"]").click();

    await expect(page).toHaveURL(/\/petclinic\/owners\/2$/);

    const phoneCell = page.locator("app-owner-detail table").first().locator("td").nth(3);
    await phoneCell.waitFor({ state: "visible", timeout: 10000 });
    await expect(phoneCell).toHaveText("6085551749");

    expect(pageErrors).toHaveLength(0);
});
