// Generated by Skyramp v1.3.44 on 2026-09-08 19:06:57.102859824 +0000 UTC m=+934.015014253
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_search_clear.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_search_clear_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openOwnersSearch, searchOwnersByLastName, clearOwnerSearch } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});




test('testUi', async ({ page }) => {
    test.setTimeout(215000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on("pageerror", (error) => pageErrors.push(error.message));

    await page.goto(`${baseUrl}/`);
    await openOwnersSearch(page);
    await expect(page.locator("#ownersTable tbody > tr")).toHaveCount(10);

    await searchOwnersByLastName(page, "Davis");
    await expect(page.getByRole("link", { exact: true, name: "George Franklin" })).toBeHidden();
    await expect(page.getByRole("textbox", { name: "Last name" })).toHaveValue("Davis");
    await expect(page.locator("#ownersTable tbody > tr")).toHaveCount(2);

    await clearOwnerSearch(page);
    await expect(page.getByRole("textbox", { name: "Last name" })).toHaveValue("");
    await expect(page.getByRole("link", { exact: true, name: "George Franklin" })).toBeVisible();
    await expect(page.locator("#ownersTable tbody > tr")).toHaveCount(10);
    await expect(page.getByRole("link", { name: "Betty Davis" })).toBeVisible();
    await expect(page.getByRole("link", { name: "Harold Davis" })).toBeVisible();
    expect(pageErrors).toHaveLength(0);
});
