// Generated by Skyramp v1.3.44 on 2026-09-08 19:09:26.755825412 +0000 UTC m=+1040.426404508
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_detail_visit_history.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_detail_visit_history_trace_1.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (error: Error) => errors.push(error));

    await page.goto(`${baseUrl}/`);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await page.locator("a[href=\"/petclinic/owners/1\"]").click();

    await expect(page).toHaveURL(/\/petclinic\/owners\/1$/);
    await expect(page.getByRole('heading')).toHaveCount(2);
    await expect(page.getByRole('heading').nth(0)).toHaveText('Owner Information');
    await expect(page.getByRole('heading').nth(1)).toHaveText('Pets and visit history');

    await expect(page.locator('app-pet-list')).toHaveCount(1);
    await expect(page.locator('app-pet-list dd').first()).toHaveText('Leo');

    expect(errors).toHaveLength(0);
});
