// Generated by Skyramp v1.3.40 on 2026-09-02 08:07:24.140123448 +0000 UTC m=+1266.649716360
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_edit_form_populates_from_owner_record.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_edit_form_populates_from_owner_record_trace.zip

// Import of required libraries
import { test, getBaseUrl, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1679000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await page.locator("a[href=\"/petclinic/owners/1\"]").click();
    await page.getByRole("button", { name: "Edit Owner" }).click();
    await page.waitForTimeout(3000);

    // The Edit Owner form must be populated from the owner record that was just opened,
    // otherwise the owner cannot be saved (Update Owner stays disabled on an invalid form).
    await expect(page.locator("#firstName")).toHaveValue("George");
    await expect(page.locator("#lastName")).toHaveValue("Franklin");
    await expect(page.getByRole("button", { name: "Update Owner" })).toBeEnabled();
});
