// Generated by Skyramp v1.3.40 on 2026-08-29 04:51:19.243650213 +0000 UTC m=+819.060014722
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_edit_short_telephone_rejected.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_edit_short_telephone_rejected_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(165000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await page.locator("a[href=\"/petclinic/owners/1\"]").click();
    await page.getByRole("button", { name: "Edit Owner" }).click();

    const playwrightRequest0: Record<string, any> = {
        "address": "110 W. Liberty St.",
        "city": "Madison",
        "firstName": "George",
        "lastName": "Franklin",
        "telephone": "12345"
    };

    await page.locator("#firstName").fill(getValue(playwrightRequest0, "firstName"));
    await page.locator("#lastName").fill(getValue(playwrightRequest0, "lastName"));
    await page.locator("#address").fill(getValue(playwrightRequest0, "address"));
    await page.locator("#city").fill(getValue(playwrightRequest0, "city"));
    await page.locator("#telephone").fill(getValue(playwrightRequest0, "telephone"));
    await expect(page.locator("#telephone").locator("xpath=following-sibling::div[@class='form-text']")).toHaveText("Digits only, no spaces or dashes.");
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/petclinic/api/owners/**");
    await page.getByRole("button", { name: "Update Owner" }).click();
    const response0 = await responsePromise0;
    expect(response0.status()).toBe(400);
    expect(JSON.stringify(await response0.json())).toContain("^[0-9]{10}$");
    await expect(page.locator(".alert-danger")).toBeVisible();

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("textbox", { name: "Telephone" })).toHaveValue("12345");
    await expect(page.getByRole("heading", { name: "Edit Owner" })).toBeVisible();
});
