// Generated by Skyramp v1.3.44 on 2026-09-08 19:18:51.564524402 +0000 UTC m=+1603.045247018
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_edit_save_failure_message.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_edit_save_failure_message_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { submitOwnerForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1582000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (error) => pageErrors.push(error.message));

    await page.goto(`${baseUrl}/`);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await page.locator("a[href=\"/petclinic/owners/1\"]").click();
    await page.getByRole("button", { name: "Edit Owner" }).click();

    const playwrightRequest0: Record<string, any> = {
        "address": "110 W. Liberty St.",
        "city": "Madison",
        "firstName": "George",
        "lastName": "Franklin",
        "telephone": "12345"
    };

    const response0 = await submitOwnerForm(
        page,
        getValue(playwrightRequest0, "firstName"),
        getValue(playwrightRequest0, "lastName"),
        getValue(playwrightRequest0, "address"),
        getValue(playwrightRequest0, "city"),
        getValue(playwrightRequest0, "telephone"));

    expect(response0.status(), 'status code').toBe(500);
    const problem0 = await response0.json();
    expect(problem0.detail, 'detail').toBe("An unexpected error occurred while processing your request");
    expect(problem0.status, 'status').toBe(500);
    expect(problem0.title, 'title').toBe("TransactionSystemException");
    expect(problem0.validationErrors.length, 'validationErrors').toBe(0);
    expect(problem0.validationErrors[0], 'validationErrors.0').toBeUndefined();
    expect(problem0.schemaValidationErrors, 'schemaValidationErrors').toBeUndefined();

    // The refused save must leave the user on the form with the rejected input intact,
    // not navigate to the owner detail page the way a successful save does.
    await expect(page).toHaveURL(/\/owners\/1\/edit$/);
    await expect(page.getByRole("textbox", { name: "Telephone" })).toHaveValue("12345");

    expect(pageErrors, 'uncaught page errors').toEqual([]);

    // The message the API put in its response body has to reach the user.
    await expect(page.locator(".alert-danger")).toHaveText(
        "An unexpected error occurred while processing your request");
});
