// Generated by Skyramp v1.3.40 on 2026-08-30 08:49:09.100196053 +0000 UTC m=+1062.117608254
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_search_clear_restores_full_list.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_search_clear_restores_full_list_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openOwnerSearch, searchOwnersByLastName, clearOwnerSearch } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});


test('testUi', async ({ page }) => {
    test.setTimeout(76000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await openOwnerSearch(page);
    await searchOwnersByLastName(page, "Coleman");
    await expect(page.getByRole("link", { name: "Jean Coleman" })).toBeVisible();
    await expect(page.getByRole("link", { name: "George Franklin" })).toHaveCount(0);
    await clearOwnerSearch(page);
    await expect(page.locator("#lastName")).toHaveValue("");
    await expect(page.getByRole("link", { name: "George Franklin" })).toBeVisible();
    await expect(page.getByRole("link", { name: "Carlos Estaban" })).toBeVisible();
});
