// Generated by Skyramp v1.3.40 on 2026-08-30 08:54:33.532445478 +0000 UTC m=+2013.403950421
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner-edit-form-prepopulates-email.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_edit_form_prepopulates_email_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openOwnersList, openOwnerDetail, openOwnerEditForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(80000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await openOwnersList(page);

    // This owner has an email on record, visible in the list's new Email column.
    await expect(page.getByRole("row", { name: "Betty Davis 638 Cardinal Ave." })).toContainText("betty.davis@example.com");

    await openOwnerDetail(page, "Betty Davis");
    await expect(page).toHaveURL(/\/petclinic\/owners\/2$/);

    await openOwnerEditForm(page);

    await expect(page).toHaveURL(/\/petclinic\/owners\/2\/edit$/);
    await expect(page.getByRole("heading", { name: "Edit Owner" })).toBeVisible();
    // The Email control this PR adds is rendered on the edit form.
    await expect(page.locator("#email")).toBeVisible();

    // KNOWN BUG (expected to fail until fixed), and PRE-EXISTING -- not introduced by this PR.
    // The edit form never pre-populates: First Name, Last Name, Address, City and Telephone are
    // all blank too, and "Update Owner" stays disabled because the required controls read empty.
    // Only the Email row is new here, so the five long-standing controls being blank cannot be
    // this PR's doing -- it is the same non-refreshing view as owner-detail.component.html.
    // Consequence for this PR: the Email field it adds to the edit form can never show the
    // owner's stored address, and the form cannot be submitted to change it.
    await expect(page.locator("#email")).toHaveValue("betty.davis@example.com");
    await expect(page.getByRole("button", { name: "Update Owner" })).toBeEnabled();
});
