// Generated by Skyramp v1.3.40 on 2026-09-02 08:09:28.829224073 +0000 UTC m=+1167.155943038
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_add_telephone_hint_vs_api_contract.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_add_telephone_hint_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { fillOwnerForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(86000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    const pageErrors: string[] = [];
    page.on('pageerror', (error) => { pageErrors.push(error.message); });
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Add New" }).click();
    await expect(page.getByText("Digits only, no spaces or")).toContainText("Digits only, no spaces or dashes.");
    await expect(page.locator(".form-text")).toHaveText("Digits only, no spaces or dashes.");
    await expect(page.getByRole("button", { name: "Add Owner" })).toBeDisabled();
    await fillOwnerForm(page, "Hintcheck", "Shortphone", "1 Test Street", "Madison", "123");
    await expect(page.getByRole("textbox", { name: "Telephone" })).toHaveValue("123");
    await expect(page.getByRole("button", { name: "Add Owner" })).toBeDisabled();
    expect(pageErrors).toHaveLength(0);
});
