// Generated by Skyramp v1.3.40 on 2026-09-02 07:58:42.381019344 +0000 UTC m=+739.397610466
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_list_pet_count_column.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_list_pet_count_column_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(959000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);

    const pageErrors: string[] = [];
    page.on('pageerror', error => pageErrors.push(error.message));

    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.waitForLoadState('networkidle');

    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();

    await page.waitForLoadState('networkidle');
    await page.locator('#ownersTable').waitFor({ state: 'visible', timeout: 10000 });

    await expect(page).toHaveURL(/\/petclinic\/owners$/);

    await expect(page.locator('#ownersTable thead th').nth(4)).toHaveText('No. of pets');
    await expect(page.locator('#ownersTable tbody tr td.ownerFullName')).toHaveCount(10);

    await expect(
        page.locator('#ownersTable tbody tr').filter({ hasText: 'Jean Coleman' }).locator('td').nth(4)
    ).toHaveText('2');
    await expect(
        page.locator('#ownersTable tbody tr').filter({ hasText: 'George Franklin' }).locator('td').nth(4)
    ).toHaveText('1');

    expect(pageErrors).toHaveLength(0);
});
