// Generated by Skyramp v1.3.40 on 2026-08-29 04:47:27.970294843 +0000 UTC m=+591.375403361
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_table_column_widths_applied.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_table_column_widths_applied_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }, testInfo) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page, testInfo);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await expect(page.getByRole("row", { name: "Name Address City Telephone" })).toContainText("NameAddressCityTelephonePets");

    // assertions reviewed: this test is named for the column-width change, so it asserts the
    // width utility class on each header the PR touched. The resulting rendered layout is
    // covered by the toHaveScreenshot baseline below.
    const headers = page.locator("#ownersTable thead th");
    await expect(headers).toHaveCount(5);
    await expect(headers.nth(0)).toHaveClass(/\bw-20\b/);
    await expect(headers.nth(1)).toHaveClass(/\bw-25\b/);
    await expect(headers.nth(2)).toHaveClass(/\bw-15\b/);

    // Bootstrap 5.3 only defines .w-25 of the three, so the Address column is the one whose
    // class actually resolves to a width rule: it should occupy ~25% of the table.
    const tableBox = await page.locator("#ownersTable table").boundingBox();
    const addressBox = await headers.nth(1).boundingBox();
    expect(addressBox!.width / tableBox!.width).toBeGreaterThan(0.2);
    expect(addressBox!.width / tableBox!.width).toBeLessThan(0.3);
    await expect(page.getByText("NameAddressCityTelephonePetsGeorge Franklin110 W. Liberty St.Madison6085551023")).toHaveScreenshot("owners-table-column-widths.png", { maxDiffPixelRatio: 0.005 });
});
