// Generated by Skyramp v1.3.40 on 2026-08-29 07:51:28.609197482 +0000 UTC m=+1248.308873240
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_detail_email_row_renders.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_detail_email_row_renders_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1738000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await expect(page.locator("#ownersTable thead")).toContainText("Email");
    await expect(page.locator("#ownersTable table tbody tr").first().locator("td").nth(4)).toHaveText("george.franklin@example.com");

    await page.locator("a[href=\"/petclinic/owners/1\"]").click();

    await expect(page.locator(".ownerFullName")).toHaveText("George Franklin");
    await expect(page.locator("app-owner-detail table tr").filter({ hasText: "Email" }).locator("td")).toHaveText("george.franklin@example.com");
});
