// Generated by Skyramp v1.3.40 on 2026-08-30 08:52:37.588806432 +0000 UTC m=+1897.460311396
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner-detail-displays-email.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_detail_displays_email_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openOwnersList, openOwnerDetail } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(71000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await openOwnersList(page);

    // The owners list renders the new Email column and this owner's address.
    await expect(page.getByRole("row", { name: "Name Address City Telephone" })).toContainText("Email");
    await expect(page.getByRole("row", { name: "George Franklin 110 W." })).toContainText("george.franklin@example.com");

    await openOwnerDetail(page, "George Franklin");

    await expect(page).toHaveURL(/\/petclinic\/owners\/1$/);
    await expect(page.getByRole("heading", { name: "Owner Information" })).toBeVisible();

    // The Email row label is rendered by the template ...
    await expect(page.getByRole("row", { name: "Email" })).toContainText("Email");

    // ... but every value cell on this page is blank. KNOWN BUG (expected to fail until fixed),
    // and PRE-EXISTING -- not introduced by this PR: reverting owner-detail.component.html to its
    // base revision leaves the other four cells (Name, Address, City, Telephone) equally blank.
    // OwnerDetailComponent.ngOnInit does receive the owner (the GET returns 200 and the component
    // instance holds the data), but owner-detail.component.html renders into a view that is never
    // refreshed after the async load -- unlike owner-list.component.html:39, whose table is guarded
    // by *ngIf="owners" and is therefore CREATED after the data arrives.
    // Consequence for this PR: the Email row the PR adds to the detail view can never show a value.
    const emailRow = page.getByRole("row", { name: "Email" });
    await expect(emailRow.locator("td")).toHaveText("george.franklin@example.com");
});
