// Generated by Skyramp v1.3.44 on 2026-09-08 19:16:53.081319629 +0000 UTC m=+1453.427135461
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_list_phone_column.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_list_phone_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1009000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/petclinic/owners`);
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.goto(`${baseUrl}/`);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await expect(page).toHaveURL(`${baseUrl}/petclinic/owners`);
    await expect(page.locator("#ownersTable thead th").nth(3)).toHaveText("Phone");
    await expect(page.getByRole("row", { name: "Name Address City Phone Pets" })).not.toContainText("Telephone");
    await expect(page.getByRole("row", { name: "George Franklin 110 W." })).toContainText("6085551023");
});
