// Generated by Skyramp v1.3.40 on 2026-08-30 08:45:34.149667315 +0000 UTC m=+843.526487240
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_list_shows_every_owner.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_list_shows_every_owner_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { submitOwnerSearch } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1132000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();

    // Initial load goes through OwnerService.getOwnersPage() -> GET /v2/owners with
    // no size param, so the server applies its default page size of 5.
    await expect(page.getByRole("link", { name: "Peter McTavish" })).toBeVisible();

    // BUG: 10 owners exist (GET /v2/owners reports totalElements=10, totalPages=2)
    // but the default page returns only the first 5, and the owners list renders no
    // pagination control -- so owners 6-10 are unreachable in the UI.
    // This assertion is EXPECTED TO FAIL until the list requests every page (or a
    // large enough size) or gains pagination controls.
    await expect(page.getByRole("link", { name: "Carlos Estaban" })).toBeVisible();

    // Submitting the search re-fetches through the unpaged v1 endpoint, which does
    // return all 10 owners -- proof the data exists and only the paged load drops it.
    await submitOwnerSearch(page);
    await expect(page.getByRole("link", { name: "Jean Coleman" })).toBeVisible();
    await expect(page.getByRole("link", { name: "Carlos Estaban" })).toBeVisible();
});
