// Generated by Skyramp v1.3.40 on 2026-08-29 09:21:38.844008934 +0000 UTC m=+820.770895761
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_add_telephone_digits_only.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_add_telephone_digits_only_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openAddOwnerForm, fillOwnerTelephone } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(66000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/`);

    await openAddOwnerForm(page);

    await fillOwnerTelephone(page, "608-555-1023");

    await expect(page.getByText("Phone number only accepts")).toContainText("Phone number only accepts digits");
    await expect(page.getByText("Digits only, no spaces or")).toContainText("Digits only, no spaces or dashes.");
    await expect(page.locator("#telephone")).toHaveValue("608-555-1023");
    await expect(page.getByRole("button", { name: "Add Owner" })).toBeDisabled();
});
