// Generated by Skyramp v1.3.40 on 2026-08-29 04:55:51.981751748 +0000 UTC m=+1045.917131348
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_list_surfaces_paged_endpoint_failure.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_paged_endpoint_failure_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(63000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.evaluate(() => { const origOpen = XMLHttpRequest.prototype.open; XMLHttpRequest.prototype.open = function (method, url, ...rest) { if (typeof url === 'string' && url.indexOf('v2/owners') !== -1) { url = url.replace('v2/owners', 'v2/owners-force-failure'); } return origOpen.call(this, method, url, ...rest); }; return 'paged owners endpoint patched to fail'; });
    await page.getByRole("button", { name: "Owners" }).click();

    const failedResponsePromise = page.waitForResponse(
        (response) => response.url().includes('v2/owners-force-failure')
    );
    await page.getByRole("link", { name: "Search" }).click();
    const failedResponse = await failedResponsePromise;

    expect(failedResponse.status()).toBe(500);
    const failureBody = await failedResponse.json();
    expect(failureBody.status).toBe(500);
    expect(failureBody.title).toBe("NoResourceFoundException");
    expect(failureBody.detail).toBe("An unexpected error occurred while processing your request");
    expect(failureBody.schemaValidationErrors.length).toBe(0);
    expect(failureBody.schemaValidationErrors[0]).toBeUndefined();

    await expect(page).toHaveURL(/\/petclinic\/owners$/);
    await expect(page.locator('#ownersTable')).toHaveCount(0);
    await expect(page.locator('app-owner-list')).not.toContainText('No owners with LastName starting with');
});
