// Generated by Skyramp v1.3.40 on 2026-08-29 09:20:14.927038478 +0000 UTC m=+749.557534377
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_list_add_new_owner_navigates_to_form.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_list_add_new_owner_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openOwnersList, openNewOwnerForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await openOwnersList(page);
    await expect(page.getByRole("button", { name: "Add New Owner" })).toBeVisible();
    await openNewOwnerForm(page);
    await expect(page).toHaveURL(`${baseUrl}/petclinic/owners/add`);
    await expect(page.getByRole("heading", { name: "New Owner" })).toHaveText("New Owner");
    await expect(page.getByRole("button", { name: "Add Owner" })).toBeDisabled();
});
