// Generated by Skyramp v1.3.40 on 2026-09-02 08:09:08.724670567 +0000 UTC m=+1368.992632906
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner-add-short-phone-surfaces-failure.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_add_short_phone_surfaces_failure_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { fillOwnerForm, submitOwnerForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1606000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.goto(`${baseUrl}/petclinic/owners`);
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Add New" }).click();

    const playwrightRequest0: Record<string, any> = {
        "address": "12 Analytical Way",
        "city": "Madison",
        "firstName": "Ada",
        "lastName": "Lovelace",
        "phoneNumber": "12345"
    };

    await fillOwnerForm(
        page,
        getValue(playwrightRequest0, "firstName"),
        getValue(playwrightRequest0, "lastName"),
        getValue(playwrightRequest0, "address"),
        getValue(playwrightRequest0, "city"),
        getValue(playwrightRequest0, "phoneNumber"),
    );
    await expect(page.getByRole("textbox", { name: "Phone" })).toHaveValue("12345");
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const response0 = await submitOwnerForm(page);

    expect(response0.status()).toBe(201);
    const createdOwner0 = await response0.json();
    expect(getValue(createdOwner0, "firstName")).toBe("Ada");
    expect(getValue(createdOwner0, "lastName")).toBe("Lovelace");
    expect(getValue(createdOwner0, "address")).toBe("12 Analytical Way");
    expect(getValue(createdOwner0, "city")).toBe("Madison");
    expect(getValue(createdOwner0, "phoneNumber")).toBe("12345");
    expect(getValue(createdOwner0, "id")).toBeGreaterThan(0);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await expect(page.locator("#ownersTable")).toContainText("Ada Lovelace");
});
