// Generated by Skyramp v1.3.44 on 2026-09-08 19:21:52.004755448 +0000 UTC m=+1752.482756505
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_list_shows_pet_count.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_list_pet_count_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1511000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (error) => pageErrors.push(error.message));

    await page.goto(`${baseUrl}/`);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await expect(page).toHaveURL(`${baseUrl}/petclinic/owners`);
    await expect(page.getByRole("link", { name: "Eduardo Rodriquez" })).toBeVisible();
    await expect(page.locator("#ownersTable thead th").nth(4)).toHaveText("No. of pets");
    // Owner rows are counted by their name cell: once the collection carries pets again,
    // the template's nested <tr> hoists extra rows into tbody, but .ownerFullName stays one per owner.
    await expect(page.locator("#ownersTable .ownerFullName")).toHaveCount(10);
    const eduardoRow = page.locator("#ownersTable table tbody tr")
        .filter({ has: page.getByRole("link", { exact: true, name: "Eduardo Rodriquez" }) });
    await expect(eduardoRow.locator("td").nth(4)).toHaveText("2");

    expect(pageErrors, 'uncaught page errors').toEqual([]);
});
