// Generated by Skyramp v1.3.44 on 2026-09-08 19:05:28.582443877 +0000 UTC m=+843.803880969
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_name_column_width.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_name_column_width_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (e) => errors.push(e));

    await page.goto(`${baseUrl}/`);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await expect(page.getByRole("link", { name: "George Franklin" })).toBeVisible();
    await expect(page.locator("#ownersTable tbody tr td.ownerFullName")).toHaveCount(10);
    await expect(page.locator("#ownersTable tbody tr td.ownerFullName").first()).toHaveText("George Franklin");

    await expect(page.locator("#ownersTable table thead th")).toHaveCount(5);
    await expect(page.locator("#ownersTable table thead th").nth(0)).toHaveText("Name");
    await expect(page.locator("#ownersTable table thead th").nth(1)).toHaveText("Address");

    const tableBox = await page.locator("#ownersTable table").boundingBox();
    const nameBox = await page.locator("#ownersTable table thead th").nth(0).boundingBox();
    const addressBox = await page.locator("#ownersTable table thead th").nth(1).boundingBox();
    const namePercent = Math.round((nameBox!.width / tableBox!.width) * 100);
    const addressPercent = Math.round((addressBox!.width / tableBox!.width) * 100);

    expect(addressPercent).toBeGreaterThanOrEqual(24);
    expect(addressPercent).toBeLessThanOrEqual(26);

    expect(namePercent).toBeGreaterThanOrEqual(19);
    expect(namePercent).toBeLessThanOrEqual(21);

    expect(errors).toHaveLength(0);
});
