// Generated by Skyramp v1.3.44 on 2026-09-08 19:09:22.455015577 +0000 UTC m=+1036.125594669
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_list_add_new_owner_button.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_list_add_new_owner_button_trace_1.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const errors: Error[] = [];
    page.on('pageerror', (error: Error) => errors.push(error));

    await page.goto(`${baseUrl}/`);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();

    await expect(page.locator('#ownersTable td.ownerFullName a').first()).toHaveText('George Franklin');
    await expect(page.locator('#ownersTable > div > button')).toHaveText('Add New Owner');

    await page.getByRole("button", { name: "Add New Owner" }).click();

    await expect(page).toHaveURL(/\/petclinic\/owners\/add$/);
    await expect(page.getByRole('heading')).toHaveText('New Owner');

    expect(errors).toHaveLength(0);
});
