// Generated by Skyramp v1.3.40 on 2026-08-30 08:45:37.791945905 +0000 UTC m=+850.809358096
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_search_empty_state_message.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_search_empty_state_message_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openOwnerSearch, searchOwnersByLastName } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(78000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await openOwnerSearch(page);
    await searchOwnersByLastName(page, "Franklinx");
    await expect(page.getByText("No owners with LastName")).toContainText("No owners with LastName starting with \"Franklinx\"");
    await expect(page.getByRole("textbox", { name: "Last name" })).toHaveValue("Franklinx");
    await expect(page.getByRole("link", { name: "George Franklin" })).toHaveCount(0);
});
