// Generated by Skyramp v1.3.40 on 2026-08-29 06:03:53.417176596 +0000 UTC m=+754.429000671
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_list_credentials.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_list_credentials_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/`);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();

    await expect(page).toHaveURL(/\/petclinic\/owners$/);

    const ownerRows = page.locator('#ownersTable > table > tbody > tr');
    await expect(ownerRows).toHaveCount(10);

    const firstOwnerRow = ownerRows.nth(0);
    await expect(firstOwnerRow.locator('> td').nth(0)).toHaveText('George Franklin');
    await expect(firstOwnerRow.locator('> td').nth(1)).toHaveText('110 W. Liberty St.');
    await expect(firstOwnerRow.locator('> td').nth(2)).toHaveText('Madison');
    await expect(firstOwnerRow.locator('> td').nth(3)).toHaveText('6085551023');

    const lastOwnerRow = ownerRows.nth(9);
    await expect(lastOwnerRow.locator('> td').nth(0)).toHaveText('Carlos Estaban');
    await expect(lastOwnerRow.locator('> td').nth(2)).toHaveText('Waunakee');

    expect(pageErrors).toHaveLength(0);
});
