// Generated by Skyramp v1.3.40 on 2026-08-30 08:46:07.142031875 +0000 UTC m=+1507.013536828
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner-add-invalid-email-silent-failure.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_add_invalid_email_clean_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openNewOwnerForm, fillOwnerForm, submitOwnerForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(150000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const playwrightRequest0: Record<string, any> = {
        "address": "1 Test Street",
        "city": "Madison",
        "email": "not-an-email",
        "firstName": "Testy",
        "lastName": "Mcemail",
        "telephone": "6085551234"
    };

    await page.goto(baseUrl);
    await openNewOwnerForm(page);

    await fillOwnerForm(
        page,
        getValue(playwrightRequest0, "firstName"),
        getValue(playwrightRequest0, "lastName"),
        getValue(playwrightRequest0, "address"),
        getValue(playwrightRequest0, "city"),
        getValue(playwrightRequest0, "telephone"),
        getValue(playwrightRequest0, "email"),
    );

    // The client accepts the malformed address: the email input carries only maxlength="100",
    // with no type="email" and no pattern, so the form reports itself as valid.
    await expect(page.getByRole("button", { name: "Add Owner" })).toBeEnabled();

    const response0 = await submitOwnerForm(page);

    // The server rejects what the client accepted.
    expect(response0.status()).toBe(400);
    const errorBody0 = await response0.json();
    expect(errorBody0.status).toBe(400);
    expect(errorBody0.title).toBe("MethodArgumentNotValidException");
    expect(errorBody0.detail).toBe("The request contains invalid or missing parameters");
    expect(errorBody0.instance).toBe("/petclinic/api/owners");
    expect(errorBody0.schemaValidationErrors.length).toBe(1);
    expect(errorBody0.schemaValidationErrors[0].field).toBe("email");
    expect(errorBody0.schemaValidationErrors[0].rejectedValue).toBe("not-an-email");
    expect(errorBody0.schemaValidationErrors[0].defaultMessage).toBe("must match \"^[^@\\s]+@[^@\\s]+\\.[^@\\s]+$\"");
    expect(errorBody0.schemaValidationErrors[1]).toBeUndefined();

    // The submit was rejected, so the user is still stranded on the form with their input intact.
    await expect(page.getByRole("textbox", { name: "Email" })).toHaveValue("not-an-email");
    await expect(page.getByRole("heading", { name: "New Owner" })).toBeVisible();
    await expect(page).toHaveURL(/\/petclinic\/owners\/add$/);

    // KNOWN BUG (expected to fail until fixed): OwnerAddComponent.onSubmit assigns the server
    // error to this.errorMessage, but owner-add.component.html never renders it -- unlike
    // owner-edit.component.html:22, which has <div *ngIf="errorMessage" class="alert alert-danger">.
    // The 400 above is therefore invisible: the user clicks Add Owner and nothing happens at all.
    await expect(page.locator(".alert-danger")).toBeVisible();
});
