// Generated by Skyramp v1.3.40 on 2026-08-29 05:16:36.371357896 +0000 UTC m=+893.758633445
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_detail_page_renders_loaded_owner.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_detail_page_renders_loaded_owner_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1167000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await expect(page.getByRole("heading", { name: "Welcome to Petclinic" })).toBeVisible();
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await expect(page.getByRole("row", { name: "George Franklin 110 W." })).toContainText("George Franklin");
    await expect(page.getByRole("row", { name: "George Franklin 110 W." })).toContainText("6085551023");
    await page.locator("a[href=\"/petclinic/owners/1\"]").click();

    // The owner detail page must render the owner returned by GET /petclinic/api/owners/1.
    await expect(page.getByRole("heading", { name: "Owner Information" })).toBeVisible();
    await expect(page.locator("b.ownerFullName")).toHaveText("George Franklin");
});
