// Generated by Skyramp v1.3.40 on 2026-08-30 08:48:02.130514288 +0000 UTC m=+998.862144004
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_add_telephone_rejection_not_surfaced.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_add_telephone_rejection_not_surfaced_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { fillOwnerForm, submitNewOwnerForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1423000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    const playwrightRequest0: Record<string, any> = {
        "address": "1 Elm St",
        "city": "Madison",
        "firstName": "Ana",
        "lastName": "Reyes",
        "telephone": "12345"
    };

    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Add New" }).click();

    await fillOwnerForm(
        page,
        getValue(playwrightRequest0, "firstName"),
        getValue(playwrightRequest0, "lastName"),
        getValue(playwrightRequest0, "address"),
        getValue(playwrightRequest0, "city"),
        getValue(playwrightRequest0, "telephone")
    );

    const response0 = await submitNewOwnerForm(page);

    expect(response0.status()).toBe(400);
    const errorBody0 = await response0.json();
    expect(errorBody0.status).toBe(400);
    expect(errorBody0.title).toBe("MethodArgumentNotValidException");
    expect(errorBody0.detail).toBe("The request contains invalid or missing parameters");
    expect(errorBody0.schemaValidationErrors.length).toBe(2);
    expect(errorBody0.schemaValidationErrors[0].field).toBe("telephone");
    expect(errorBody0.schemaValidationErrors[0].rejectedValue).toBe(getValue(playwrightRequest0, "telephone"));
    expect(errorBody0.schemaValidationErrors[2]).toBeUndefined();

    await expect(page.getByRole("heading", { name: "New Owner" })).toBeVisible();
    await expect(page.getByRole("textbox", { name: "Telephone" })).toHaveValue("12345");

    await expect(
        page.locator(".alert-danger"),
        "owner-add.component.html renders no element bound to errorMessage, so the backend 400 above is never surfaced to the user"
    ).toBeVisible();
});
