// Generated by Skyramp v1.3.40 on 2026-08-29 07:51:35.342644168 +0000 UTC m=+1255.042319936
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_detail_without_email_renders.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_detail_without_email_renders_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { fillOwnerFormWithoutEmail } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(106000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Add New" }).click();

    // Owners carry no unique constraint, so give this run its own last name to
    // keep the test re-runnable against a database that retains earlier runs.
    // Last Name only accepts letters, so map the timestamp digits onto letters.
    const runSuffix = Date.now().toString().slice(-6)
        .split("").map(digit => "abcdefghij"[Number(digit)]).join("");
    const playwrightRequest0: Record<string, any> = {
        "address": "42 Optional Way",
        "city": "Madison",
        "firstName": "Noemail",
        "lastName": `Optionalfield${runSuffix}`,
        "telephone": "6085550042"
    };

    await fillOwnerFormWithoutEmail(
        page,
        getValue(playwrightRequest0, "firstName"),
        getValue(playwrightRequest0, "lastName"),
        getValue(playwrightRequest0, "address"),
        getValue(playwrightRequest0, "city"),
        getValue(playwrightRequest0, "telephone")
    );
    // Wait to finish any potential hydration
    await page.waitForTimeout(1500);
    const responsePromise0 = page.waitForResponse("**/petclinic/api/owners**");
    await page.getByRole("button", { name: "Add Owner" }).click();
    const response0 = await responsePromise0;

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    expect(response0.status()).toBe(201);

    const createdOwnerName = `Noemail Optionalfield${runSuffix}`;
    await expect(page.getByRole("link", { name: createdOwnerName })).toBeVisible();

    const createdRow = page.locator("#ownersTable table tbody tr").filter({ hasText: createdOwnerName });
    await expect(createdRow.locator("td").nth(3)).toHaveText(getValue(playwrightRequest0, "telephone"));
    await expect(createdRow.locator("td").nth(4)).toHaveText("");
});
