// Generated by Skyramp v1.3.40 on 2026-08-29 09:29:15.746984814 +0000 UTC m=+1238.492630007
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_add_phone_number_appears_in_list.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_add_phone_number_appears_in_list_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openAddOwnerForm, fillOwnerForm, submitAddOwnerForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(71000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    const errors: string[] = [];
    page.on('pageerror', e => errors.push(e.message));
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await openAddOwnerForm(page);

    const playwrightRequest0: Record<string, any> = {
        "address": "42 Phone Field Rd",
        "city": "Madison",
        "firstName": "Testbot",
        "lastName": "Phonecheck",
        "phoneNumber": "5551230001"
    };

    await fillOwnerForm(
        page,
        getValue(playwrightRequest0, "firstName"),
        getValue(playwrightRequest0, "lastName"),
        getValue(playwrightRequest0, "address"),
        getValue(playwrightRequest0, "city"),
        getValue(playwrightRequest0, "phoneNumber"),
    );
    const responsePromise0 = page.waitForResponse("**/petclinic/api/owners**");
    await submitAddOwnerForm(page);
    const response0 = await responsePromise0;

    expect(response0.status()).toBe(201);
    const createdOwner = await response0.json();
    expect(createdOwner.phoneNumber).toBe(getValue(playwrightRequest0, "phoneNumber"));
    expect(createdOwner.firstName).toBe(getValue(playwrightRequest0, "firstName"));
    expect(createdOwner.lastName).toBe(getValue(playwrightRequest0, "lastName"));
    expect(createdOwner.id).toBeGreaterThan(0);

    await expect(page).toHaveURL(/\/petclinic\/owners$/);
    const newOwnerRow = page.locator("#ownersTable table tbody > tr")
        .filter({ hasText: `${getValue(playwrightRequest0, "firstName")} ${getValue(playwrightRequest0, "lastName")}` })
        .last();
    await expect(newOwnerRow.locator("td").nth(3)).toHaveText(getValue(playwrightRequest0, "phoneNumber"));

    expect(errors).toHaveLength(0);
});
