// Generated by Skyramp v1.3.40 on 2026-08-29 05:41:02.531616846 +0000 UTC m=+780.641130161
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_add_form_phone_validation_feedback.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_add_form_phone_validation_feedback_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(83000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Add New" }).click();
    await page.locator("#phoneNumber").fill("abc123xyz");
    await expect(page.getByText("Phone number only accepts")).toContainText("Phone number only accepts digits");
    await expect(page.getByRole("textbox", { name: "Phone" })).toHaveValue("abc123xyz");
    await expect(page.getByRole("button", { name: "Add Owner" })).toBeDisabled();
});
