// Generated by Skyramp v1.3.40 on 2026-08-29 09:22:03.137113764 +0000 UTC m=+855.224030685
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_search_then_clear_list_consistency.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_search_then_clear_trace.zip

// Import of required libraries
import { test, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { expect } from '@playwright/test';
import { searchOwnersByLastName } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(76000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();

    await expect(page).toHaveURL(/\/petclinic\/owners$/);
    await expect(page.getByRole('link', { name: 'George Franklin' })).toBeVisible();
    // The owner set the page renders on first load, before any search is applied.
    const initialOwnerCount = await page.locator('#ownersTable td.ownerFullName').count();

    await searchOwnersByLastName(page, "Davis");

    // Searching narrows the list to matching owners only.
    await expect(page.locator('#ownersTable td.ownerFullName')).toHaveCount(2);
    await expect(page.getByRole('link', { name: 'Betty Davis' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'Harold Davis' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'George Franklin' })).toHaveCount(0);

    await searchOwnersByLastName(page, "");

    // Clearing the search restores the unfiltered list.
    await expect(page.getByRole('link', { name: 'Betty Davis' })).toBeVisible();
    await expect(page.getByRole('link', { name: 'George Franklin' })).toBeVisible();

    // Clearing the search must restore the same list the page showed on first load.
    // It does not: ngOnInit loads through the paged getOwnersPage() (default size 5)
    // while searchByLastName('') falls back to the unpaged getOwners() and returns all
    // 10 owners, so the same screen shows two different owner sets. This assertion
    // FAILS on the current code and documents that inconsistency.
    await expect(page.locator('#ownersTable td.ownerFullName')).toHaveCount(initialOwnerCount);
});
