// Generated by Skyramp v1.3.40 on 2026-08-30 08:50:03.07530929 +0000 UTC m=+1059.269366991
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner-detail-renders-stored-owner-fields.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_detail_renders_stored_owner_fields_trace.zip

// Import of required libraries
import { test, getBaseUrl, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1218000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();

    // The owners list is the source of truth for owner 1's stored values.
    await expect(page.locator('#ownersTable')).toContainText("George Franklin");
    await expect(page.locator('#ownersTable')).toContainText("110 W. Liberty St.");

    await page.locator("a[href=\"/petclinic/owners/1\"]").click();

    await expect(page.getByRole("heading", { name: "Owner Information" })).toBeVisible();

    // The detail screen must render the same stored values the list just showed.
    await expect(page.locator(".ownerFullName")).toHaveText("George Franklin");
    await expect(page.locator("main table").first()).toContainText("110 W. Liberty St.");
    await expect(page.locator("main table").first()).toContainText("Madison");
    await expect(page.locator("main table").first()).toContainText("6085551023");
});
