// Generated by Skyramp v1.3.40 on 2026-09-02 08:06:48.652082482 +0000 UTC m=+1285.118555559
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_list_add_new_owner_button.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_list_add_new_owner_button_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openAddOwnerForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(65000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (error) => pageErrors.push(error.message));

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();

    await expect(page).toHaveURL(`${baseUrl}/petclinic/owners`);
    // The owners table loaded its rows, so the button gated on isOwnersDataReceived renders.
    await expect(page.locator("#ownersTable td.ownerFullName").first()).toHaveText("George Franklin");
    // The button this PR renamed carries its new label exactly.
    await expect(page.locator("#ownersTable").getByRole("button", { name: "Add New Owner" })).toHaveText("Add New Owner");

    await openAddOwnerForm(page);

    await expect(page).toHaveURL(`${baseUrl}/petclinic/owners/add`);
    await expect(page.getByRole("heading", { name: "New Owner" })).toHaveText("New Owner");

    expect(pageErrors, 'uncaught page errors').toEqual([]);
});
