// Generated by Skyramp v1.3.40 on 2026-08-30 08:44:04.177795111 +0000 UTC m=+742.549903833
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_list_initial_load_no_alert_flash.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_list_initial_load_no_alert_flash_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await expect(page.getByRole("button", { name: "Add Owner" })).toBeVisible();
    await expect(page.getByRole("row", { name: "Name Address City Telephone" })).toContainText("NameAddressCityTelephonePets");
    await expect(page.locator("#ownersTable")).toBeVisible();
    await expect(page.getByRole("link", { name: "George Franklin" })).toBeVisible();
    await expect(page.locator(".alert.alert-info")).toHaveCount(0);
});
