// Generated by Skyramp v1.3.40 on 2026-08-29 09:20:14.89459952 +0000 UTC m=+729.076720102
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_list_sort_toggle_direction.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_list_sort_toggle_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { sortOwnersByCity } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();

    const cityCells = page.locator("#ownersTable table > tbody > tr td:nth-child(3)");
    await expect(cityCells).toHaveCount(10);

    // First click sorts ascending: "Madison" first, "Windsor" last.
    await sortOwnersByCity(page);
    await expect(cityCells.nth(0)).toHaveText("Madison");

    // Second click must reverse the direction: "Windsor" first, "Madison" last.
    await sortOwnersByCity(page);
    await expect(cityCells.nth(0)).toHaveText("Windsor");
    await expect(cityCells.nth(9)).toHaveText("Madison");
});
