// Generated by Skyramp v1.3.44 on 2026-09-09 05:47:07.12504572 +0000 UTC m=+1339.658281097
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_detail_reminders_appear_after_booking.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_reminders_appear_after_booking_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openAddVisitForm, submitVisitForm, deleteVisit } from './skyrampUtils';

const pageTimeout = 15000;

// The reminder window is relative to the day the test runs, so the booked date is
// derived from today. A literal date would drop out of the window and stop appearing
// in the Upcoming reminders section this test asserts on.
function isoDateOffsetFromToday(days: number): string {
    const date = new Date();
    date.setUTCHours(0, 0, 0, 0);
    date.setUTCDate(date.getUTCDate() + days);
    return date.toISOString().slice(0, 10);
}

const bookedVisitDate = isoDateOffsetFromToday(5);

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(272000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Any uncaught frontend exception fails this test: the owner page now issues an
    // extra request on init, and a throw there would otherwise only show as an empty
    // reminders section.
    const pageErrors: string[] = [];
    page.on('pageerror', (error) => pageErrors.push(error.message));

    await page.goto(`${baseUrl}/petclinic/owners/1`);
    await expect(page.getByText("Nothing coming up for this")).toContainText("Nothing coming up for this owner.");
    await openAddVisitForm(page);

    const playwrightRequest0: Record<string, any> = {
        "date": bookedVisitDate,
        "description": "Skyramp reminder check"
    };

    const response0 = await submitVisitForm(page, getValue(playwrightRequest0, "date"), getValue(playwrightRequest0, "description"));

    expect(response0.status()).toBe(201);
    const bookedVisit = await response0.json();
    expect(getValue(bookedVisit, "date")).toBe(bookedVisitDate);
    expect(getValue(bookedVisit, "description")).toBe("Skyramp reminder check");
    expect(getValue(bookedVisit, "id")).toBeGreaterThan(0);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.locator("#remindersTable tr")).toHaveCount(2);
    await expect(page.locator("#remindersTable tr").nth(1).locator("td").nth(0)).toHaveText(bookedVisitDate);
    await expect(page.locator("#remindersTable tr").nth(1).locator("td").nth(1)).toHaveText("Skyramp reminder check");
    await expect(page.getByText("Nothing coming up for this owner.", { exact: true })).toBeHidden();
    await deleteVisit(page);
    await expect(page.getByRole("button", { exact: true, name: "Delete Visit" })).toBeHidden();

    expect(pageErrors, 'uncaught frontend errors').toEqual([]);
});
