// Generated by Skyramp v1.3.40 on 2026-08-30 08:47:46.765234687 +0000 UTC m=+979.782646878
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_search_clear_preserves_add_owner_action.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_search_clear_preserves_add_owner_action_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openOwnerSearch, searchOwnersByLastName, clearOwnerSearch } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});


test('testUi', async ({ page }) => {
    test.setTimeout(74000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await openOwnerSearch(page);
    await searchOwnersByLastName(page, "Davis");
    await expect(page.getByRole("link", { name: "Eduardo Rodriquez" })).toHaveCount(0);
    await clearOwnerSearch(page);
    await expect(page.getByRole("button", { name: "Add Owner" })).toBeVisible();
    await expect(page.getByRole("link", { name: "Eduardo Rodriquez" })).toBeVisible();
    await expect(page.getByRole("link", { name: "Betty Davis" })).toBeVisible();
});
