// Generated by Skyramp v1.3.40 on 2026-08-29 09:27:16.000282783 +0000 UTC m=+1118.745927976
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_edit_form_prefills_phone_number.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_edit_form_prefills_phone_number_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openOwnersList, openOwnerDetail, openOwnerEditForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(132000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    const errors: string[] = [];
    page.on('pageerror', e => errors.push(e.message));
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await openOwnersList(page);

    const bettyDavisRow = page.locator("#ownersTable table tbody > tr")
        .filter({ has: page.locator("a[href=\"/petclinic/owners/2\"]") });
    await expect(bettyDavisRow.locator("td").nth(3)).toHaveText("6085551749");

    await openOwnerDetail(page);
    await openOwnerEditForm(page);

    await expect(page).toHaveURL(/\/petclinic\/owners\/1\/edit$/);
    await expect(page.getByRole("textbox", { name: "Phone" })).toHaveValue("6085551023");
    await expect(page.getByRole("textbox", { name: "First Name" })).toHaveValue("George");
    await expect(page.getByRole("button", { name: "Update Owner" })).toBeEnabled();

    expect(errors).toHaveLength(0);
});
