// Generated by Skyramp v1.3.40 on 2026-08-30 08:48:10.233985384 +0000 UTC m=+1006.965615080
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_add_client_accepts_telephone_backend_rejects.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_add_client_accepts_telephone_backend_rejects_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { fillOwnerForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(77000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Add New" }).click();
    await fillOwnerForm(page, "Ana", "Reyes", "1 Elm St", "Madison", "12345");

    await expect(
        page.getByRole("button", { name: "Add Owner" }),
        "client validators are minlength=1/maxlength=20 while the backend requires exactly 10 digits, so a 5-digit value is submittable"
    ).toBeEnabled();
    await expect(page.getByRole("textbox", { name: "Telephone" })).toHaveValue("12345");
    await expect(page.getByText("Digits only, no spaces or")).toContainText("Digits only, no spaces or dashes.");
});
