// Generated by Skyramp v1.3.40 on 2026-08-30 08:48:25.750894257 +0000 UTC m=+1004.123002969
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_table_name_column_width_applied.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owners_table_name_column_width_applied_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }, testInfo) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page, testInfo);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await expect(page.locator("#ownersTable")).toBeVisible();

    // The PR widens the Name and Address columns via Bootstrap width utilities.
    // Bootstrap 5.3 ships only .w-25/.w-50/.w-75/.w-100, so "w-25" on Address resolves
    // but "w-20" on Name (and "w-15" on City) match no CSS rule and apply no width.
    const columnWidthRatios = await page.evaluate(() => {
        const table = document.querySelector("#ownersTable table") as HTMLElement;
        const headers = Array.from(table.querySelectorAll("thead th")) as HTMLElement[];
        const tableWidth = table.getBoundingClientRect().width;
        return headers.map(th => th.getBoundingClientRect().width / tableWidth);
    });

    // Address uses w-25, which Bootstrap defines: width is 25% of the table.
    expect(columnWidthRatios[1]).toBeCloseTo(0.25, 2);

    // Name uses w-20, which the PR intends as 20% of the table.
    expect(columnWidthRatios[0]).toBeCloseTo(0.20, 2);

    await expect(page.locator("#ownersTable table")).toHaveScreenshot("owners-table-columns.png", { maxDiffPixelRatio: 0.005 });
});
