// Generated by Skyramp v1.3.40 on 2026-08-29 09:21:34.786457104 +0000 UTC m=+816.713343951
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_add_telephone_rejection.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_add_telephone_rejection_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openAddOwnerForm, submitOwnerForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(1080000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.goto(`${baseUrl}/petclinic/owners/add`);
    await page.goto(`${baseUrl}/petclinic/welcome`);
    // Wait for network activities to finish
    await page.waitForTimeout(5000);

    await page.goto(`${baseUrl}/`);

    await openAddOwnerForm(page);

    const playwrightRequest0: Record<string, any> = {
        "address": "1 Main St",
        "city": "Madison",
        "firstName": "Helper",
        "lastName": "Probe",
        "telephone": "608555"
    };

    const response0 = await submitOwnerForm(
        page,
        getValue(playwrightRequest0, "firstName"),
        getValue(playwrightRequest0, "lastName"),
        getValue(playwrightRequest0, "address"),
        getValue(playwrightRequest0, "city"),
        getValue(playwrightRequest0, "telephone"),
    );

    await expect(page.getByText("Digits only, no spaces or")).toContainText("Digits only, no spaces or dashes.");

    expect(response0.status()).toBe(400);
    const response0Body = await response0.json();
    expect(getValue(response0Body, "status")).toBe(400);
    expect(getValue(response0Body, "title")).toBe("MethodArgumentNotValidException");
    expect(getValue(response0Body, "detail")).toBe("The request contains invalid or missing parameters");
    expect(getValue(response0Body, "schemaValidationErrors.0.field")).toBe("telephone");
    expect(getValue(response0Body, "schemaValidationErrors.0.rejectedValue")).toBe(getValue(playwrightRequest0, "telephone"));
    expect(getValue(response0Body, "schemaValidationErrors.0.defaultMessage")).toBe("size must be between 10 and 10");
    expect(getValue(response0Body, "schemaValidationErrors.1.field")).toBe("telephone");
    expect(getValue(response0Body, "schemaValidationErrors.1.defaultMessage")).toBe("must match \"^[0-9]{10}$\"");
    expect(getValue(response0Body, "schemaValidationErrors.2")).toBeNull();

    // The backend rejects this telephone, so the form must not have offered it for submission:
    // the Add Owner button should be disabled for a value the API will not accept.
    await expect(page.getByRole("button", { name: "Add Owner" })).toBeDisabled();

    // And the rejection must be surfaced to the user rather than swallowed.
    await expect(page.locator(".alert-danger")).toBeVisible();
});
