// Generated by Skyramp v1.3.40 on 2026-09-02 08:12:14.292654237 +0000 UTC m=+1565.742563079
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output pet_list_nickname_visible.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/pet_list_nickname_visible_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { updatePetViaApi } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Precondition: give owner 1's pet a nickname so the pet list has one to surface.
    const seedResponse = await updatePetViaApi(page, baseUrl, 1, "Leo", "Leonardo", "2010-09-07", 1, "cat", 1);
    expect(seedResponse.status()).toBe(204);

    await page.goto(`${baseUrl}/owners/1`);

    // The PR description states the pet nickname is surfaced on the pet list.
    // The pet list renders only inside the owner detail page, so assert it there.
    await expect(page.locator("main")).toContainText("Leo");
    await expect(page.locator("main")).toContainText("Nickname");
    await expect(page.locator("main")).toContainText("Leonardo");
});
