// Generated by Skyramp v1.3.40 on 2026-08-29 06:04:10.167626739 +0000 UTC m=+953.658994710
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output pet_add_nickname_maxlength.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/pet_add_nickname_maxlength_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(66000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await page.locator("a[href=\"/petclinic/owners/1\"]").click();
    await page.getByRole("button", { name: "Add New Pet" }).click();
    await expect(page.locator("#nickname")).toHaveAttribute("maxlength", "30");
    await page.locator("#nickname").fill("NicknameThatIsWayTooLongForTheField");
    await expect(page.getByRole("textbox", { name: "Nickname" })).toHaveValue("NicknameThatIsWayTooLongForThe");
    await expect(page.getByRole("textbox", { name: "Nickname" })).not.toHaveValue("NicknameThatIsWayTooLongForTheField");
});
