// Generated by Skyramp v1.3.40 on 2026-08-30 08:49 UTC
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output pet_edit_form_prefills_nickname.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/pet_edit_form_prefills_nickname_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openOwnersSearchList, openOwnerDetail, openPetEditForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await openOwnersSearchList(page);
    await openOwnerDetail(page, "/petclinic/owners/1");

    await expect(page).toHaveURL(`${baseUrl}/petclinic/owners/1`);

    // The "Edit Pet" button rendered by pet-list.component.html is the only route
    // into the pet edit form, which is where the new Nickname input is pre-filled.
    // It must be present for that form to be reachable at all.
    await expect(page.getByRole("button", { name: "Edit Pet" }).first()).toBeVisible();

    await openPetEditForm(page);

    await expect(page).toHaveURL(/\/petclinic\/pets\/\d+\/edit$/);
    await expect(page.getByRole("heading", { name: "Pet" })).toBeVisible();

    // The edit form must pre-populate from the stored pet: "Leo" is owner 1's
    // seeded pet, so its name is the stable check that binding happened at all.
    await expect(page.locator("#name")).toHaveValue("Leo");

    // pet-edit.component.html adds <input id="nickname" [(ngModel)]="pet.nickname">,
    // so the new Nickname control must be present and bound on form load.
    await expect(page.locator("#nickname")).toBeVisible();
    await expect(page.locator("#nickname")).toHaveAttribute("maxlength", "30");
});
