// Generated by Skyramp v1.3.40 on 2026-08-29 09:22:11.551720552 +0000 UTC m=+824.720756009
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output pet_add_nickname_maxlength.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/pet_add_nickname_maxlength_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openOwnersList, openOwnerDetail, openAddPetForm, fillPetNickname } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(63000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await page.waitForLoadState("networkidle");

    await openOwnersList(page);
    await openOwnerDetail(page, "/petclinic/owners/1");
    await openAddPetForm(page);

    await expect(page).toHaveURL(/\/petclinic\/owners\/1\/pets\/add$/);

    // The Nickname control this PR adds carries the backend's 30-character limit.
    await expect(page.locator("#nickname")).toHaveAttribute("maxlength", "30");

    // A 31-character nickname must be clamped to 30 characters by the control.
    await fillPetNickname(page, "Bartholomew-Reginald-Fizzwiggle");
    await expect(page.getByRole("textbox", { name: "Nickname" })).toHaveValue("Bartholomew-Reginald-Fizzwiggl");
});
