// Generated by Skyramp v1.3.40 on 2026-08-30 08:48 UTC
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output pet_add_nickname_input.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/pet_add_nickname_input_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import {
    openOwnersSearchList,
    openOwnerDetail,
    openAddPetForm,
    fillPetIdentityFields,
    fillPetTypeAndBirthDate,
    submitPetForm,
} from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(138000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const playwrightRequest0: Record<string, any> = {
        "birthDate": "2021-04-15",
        "name": "Rex",
        "nickname": "Rexy",
        "type": {"name": "dog"}
    };

    await page.goto(baseUrl);
    await openOwnersSearchList(page);
    await openOwnerDetail(page, "/petclinic/owners/1");
    await openAddPetForm(page);

    await fillPetIdentityFields(
        page,
        getValue(playwrightRequest0, "name"),
        getValue(playwrightRequest0, "nickname"),
    );
    await expect(page.getByRole("textbox", { name: "Nickname" })).toHaveValue("Rexy");
    await expect(page.getByRole("textbox", { name: "Owner" })).toHaveValue("George Franklin");

    await fillPetTypeAndBirthDate(
        page,
        getValue(playwrightRequest0, "type.name"),
        getValue(playwrightRequest0, "birthDate"),
    );

    const response0 = await submitPetForm(page);

    // The new nickname field must reach the API and be echoed back unchanged.
    expect(response0.status()).toBe(201);
    const createdPet = await response0.json();
    expect(getValue(createdPet, "name")).toBe("Rex");
    expect(getValue(createdPet, "nickname")).toBe("Rexy");
    expect(getValue(createdPet, "birthDate")).toBe("2021-04-15");
    expect(getValue(createdPet, "type.name")).toBe("dog");
    expect(getValue(createdPet, "id")).toBeGreaterThan(0);

    // Saving redirects to the owner detail page, which must list the pet just
    // created together with the nickname entered on the form.
    await expect(page).toHaveURL(`${baseUrl}/petclinic/owners/1`);
    await expect(page.locator("main")).toContainText("Rex");
    await expect(page.locator("main")).toContainText("Rexy");
});
