// Generated by Skyramp v1.3.40 on 2026-09-02 08:12:02.527409537 +0000 UTC m=+1553.977318359
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output pet_add_nickname.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/pet_add_nickname_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { fillPetForm, submitPetForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(70000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/owners/1/pets/add`);

    const playwrightRequest0: Record<string, any> = {
        "birthDate": "2021-04-15",
        "name": "Rex",
        "nickname": "Rexy",
        "type": {"name": "dog"}
    };

    await fillPetForm(
        page,
        getValue(playwrightRequest0, "name"),
        getValue(playwrightRequest0, "nickname"),
        getValue(playwrightRequest0, "birthDate"),
        getValue(playwrightRequest0, "type.name")
    );
    await expect(page.getByRole("textbox", { name: "Nickname" })).toHaveValue("Rexy");

    const response0 = await submitPetForm(page, "Save Pet", "**/petclinic/api/owners/**/pets**");

    expect(response0.status()).toBe(201);
    const createdPet = await response0.json();
    expect(createdPet.name).toBe("Rex");
    expect(createdPet.nickname).toBe("Rexy");
    expect(createdPet.birthDate).toBe("2021-04-15");
    expect(createdPet.type.name).toBe("dog");
    expect(createdPet.ownerId).toBe(1);
    expect(createdPet.id).toBeGreaterThan(0);

    // Saving redirects to the owner detail page, which renders the pet list.
    // The nickname this PR added must surface there for the feature to be usable.
    await expect(page).toHaveURL(/\/petclinic\/owners\/1$/);
    await expect(page.locator("main")).toContainText("Rex");
    await expect(page.locator("main")).toContainText("Rexy");
});
