// Generated by Skyramp on 2026-09-08 19:15:01.214 Coordinated Universal Time


import { expect } from '@skyramp/skyramp';
import type { Page } from '@playwright/test';

export async function sortOwnersByCity(page: Page) {
    await page.locator("#sortByCity").click();
    await expect(page.getByRole("link", { name: "City" })).toBeVisible();
}
