// Generated by Skyramp on 2026-08-30 08:43:19.849 Coordinated Universal Time


export async function searchOwnersByLastName(page, lastName) {
    await page.locator("#lastName").fill(lastName);
    await page.getByRole("button", { name: "Find Owner" }).click();
}
