// Generated by Skyramp on 2026-08-30 08:56:05.548 Coordinated Universal Time


export async function openOwnersList(page) {
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
}

export async function openOwnerEditForm(page) {
    await page.locator("a[href=\"/petclinic/owners/1\"]").click();
    await page.getByRole("button", { name: "Edit Owner" }).click();
}

export async function fillOwnerPhoneNumber(page, phoneNumber) {
    await page.locator("#phoneNumber").fill(phoneNumber);
}

export async function submitOwnerEditForm(page) {
    await page.waitForTimeout(1500);
    const responsePromise = page.waitForResponse("**/petclinic/api/owners/**");
    await page.getByRole("button", { name: "Update Owner" }).click();
    return await responsePromise;
}

export async function fillNewOwnerForm(page, firstName, lastName, address, city) {
    await page.locator("#firstName").fill(firstName);
    await page.locator("#lastName").fill(lastName);
    await page.locator("#address").fill(address);
    await page.locator("#city").fill(city);
}
