// Generated by Skyramp v1.3.44 on 2026-09-09 04:45:56.962659563 +0000 UTC m=+1374.117310349
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ui_add_owner_invalid_email.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/add_owner_invalid_email_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { fillOwnerForm, fillOwnerEmail } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(75000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (error) => pageErrors.push(error.message));

    await page.goto(`${baseUrl}/petclinic/owners/add`);

    await fillOwnerForm(page, "Ivan", "Badmail", "9 Bounce Road", "Madison", "6085552603");

    // Every other field on this form carries a client-side validator matching its server
    // constraint, so an invalid value disables the submit button. The API refuses an email
    // that does not match ^[^@\s]+@[^@\s]+\.[^@\s]+$ with HTTP 400, so a malformed address
    // must block submission the same way.
    await fillOwnerEmail(page, "not-an-email");

    await expect(page.getByRole("button", { name: "Add Owner" })).toBeDisabled();

    expect(pageErrors, 'page errors').toEqual([]);
});
