// Generated by Skyramp v1.3.44 on 2026-09-09 04:45:52.812 +0000 UTC
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ui_edit_owner_email.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/edit_owner_email_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openOwnerFromList, openOwnerEditForm, updateOwnerEmail } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(191000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (error) => pageErrors.push(error.message));

    await page.goto(`${baseUrl}/petclinic/owners`);
    // The owners list must already carry the seeded address before the edit begins,
    // so the restore at the end returns the record to the state this test found it in.
    await expect(page.locator("#ownersTable").getByRole("row", { name: "George Franklin" })).toContainText("george.franklin@example.com");

    await openOwnerFromList(page, "George Franklin");
    await openOwnerEditForm(page);
    await expect(page.getByRole("textbox", { name: "Email" })).toHaveValue("george.franklin@example.com");

    await updateOwnerEmail(page, "george.franklin.updated@example.com");
    await expect(page.getByRole("row", { name: "Email george.franklin.updated" })).toContainText("george.franklin.updated@example.com");

    await openOwnerEditForm(page);
    await updateOwnerEmail(page, "george.franklin@example.com");
    await expect(page.getByRole("row", { name: "Email george.franklin@example" })).toContainText("george.franklin@example.com");
    await expect(page.getByRole("row", { name: "Email george.franklin.updated" })).toHaveCount(0);

    expect(pageErrors, 'page errors').toEqual([]);
});
