// Generated by Skyramp v1.3.44 on 2026-09-08 19:16:32.56152331 +0000 UTC m=+1831.036244363
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ui_owner_add_email.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_add_email_trace_1.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openAddOwnerForm, fillOwnerForm, submitAddOwnerForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(127000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/`);
    await openAddOwnerForm(page);

    const playwrightRequest0: Record<string, any> = {
        "address": "1 Test Way",
        "city": "Madison",
        "email": "emma.skyramp@example.com",
        "firstName": "Emma",
        "lastName": "Skyramp",
        "telephone": "6085551000"
    };

    await fillOwnerForm(
        page,
        getValue(playwrightRequest0, "firstName"),
        getValue(playwrightRequest0, "lastName"),
        getValue(playwrightRequest0, "address"),
        getValue(playwrightRequest0, "city"),
        getValue(playwrightRequest0, "telephone"),
        getValue(playwrightRequest0, "email")
    );

    const response0 = await submitAddOwnerForm(page);

    expect(response0.status()).toBe(201);
    const createdOwner0 = await response0.json();
    expect(getValue(createdOwner0, "email")).toBe("emma.skyramp@example.com");
    expect(getValue(createdOwner0, "firstName")).toBe("Emma");
    expect(getValue(createdOwner0, "lastName")).toBe("Skyramp");
    expect(getValue(createdOwner0, "address")).toBe("1 Test Way");
    expect(getValue(createdOwner0, "city")).toBe("Madison");
    expect(getValue(createdOwner0, "telephone")).toBe("6085551000");
    expect(getValue(createdOwner0, "id")).toBeGreaterThan(0);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.getByRole("row", { name: "Emma Skyramp 1 Test Way" })).toContainText("emma.skyramp@example.com");
    await expect(page.getByRole("link", { name: "Emma Skyramp" })).toHaveCount(1);
});
