// Generated by Skyramp v1.3.44 on 2026-09-08 19:16:41.217808739 +0000 UTC m=+1839.692529782
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output ui_owner_email_detail_and_edit.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/owner_email_detail_edit_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(133000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/`);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await page.locator("a[href=\"/petclinic/owners/1\"]").click();
    await expect(page.getByRole("heading", { name: "Owner Information" })).toBeVisible();
    await expect(page.locator("app-owner-detail tr").filter({ hasText: "Email" })).toContainText("george.franklin@example.com");
    await page.getByRole("button", { name: "Edit Owner" }).click();
    await expect(page.getByRole("heading", { name: "Edit Owner" })).toBeVisible();
    await expect(page.locator("#email")).toHaveValue("george.franklin@example.com");
});
