// Generated by Skyramp v1.3.40 on 2026-08-30 08:54:34.304868389 +0000 UTC m=+1363.741989746
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output vet-list-specialties-inline-and-empty-state.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/vet_list_specialties_inline_and_empty_state_trace.zip
// Import of required libraries
import { test, getBaseUrl, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';
import { openVetList } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await openVetList(page);

    // A vet with two specialties renders both of them inline in a single cell.
    // The exact match pins the one-line "dentistry surgery" rendering: were the
    // specialties stacked in block-level divs again, or were the placeholder to
    // leak in alongside them, this assertion fails.
    await expect(page.locator("#vets tbody tr").filter({ hasText: "Linda Douglas" }).locator("td").nth(1)).toHaveText("dentistry surgery");

    // A vet with an empty specialties array renders the placeholder, not a blank cell.
    await expect(page.locator("#vets tbody tr").filter({ hasText: "James Carter" }).locator("td").nth(1)).toHaveText("No specialties");
    await expect(page.locator("#vets tbody tr").filter({ hasText: "Sharon Jenkins" }).locator("td").nth(1)).toHaveText("No specialties");

    // A vet with exactly one specialty renders it alone, with no placeholder.
    await expect(page.locator("#vets tbody tr").filter({ hasText: "Rafael Ortega" }).locator("td").nth(1)).toHaveText("surgery");

    // List integrity: rendering the specialties column must not add or drop rows.
    await expect(page.locator("#vets tbody tr")).toHaveCount(6);
});
