// Generated by Skyramp v1.3.40 on 2026-08-30 08:56:47.174384219 +0000 UTC m=+1496.611505566
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output vet-list-specialties-render-on-narrow-viewport.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/vet_list_specialties_render_on_narrow_viewport_trace.zip
// Import of required libraries
import { test, getBaseUrl, newSkyrampPlaywrightPage, expect } from '@skyramp/skyramp';
import { openVetList } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

// Narrow, phone-sized viewport: the specialties column is most likely to reflow here.
test.use({
    viewport: { width: 375, height: 667 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);

    // At this width Bootstrap collapses the navbar, so the menu must be
    // expanded before its entries are clickable.
    const toggler = page.getByRole("button", { name: "Toggle navigation" });
    await toggler.click();
    await expect(page.locator("#petclinicNavbar")).toHaveClass(/show/);

    await openVetList(page);

    const specialtyCell = page.locator("#vets tbody tr").filter({ hasText: "Linda Douglas" }).locator("td").nth(1);
    const specialtyItems = specialtyCell.locator("div");

    // Both specialties are still present at a narrow width.
    await expect(specialtyItems).toHaveCount(2);
    await expect(specialtyCell).toHaveText("dentistry surgery");

    // Layout assertion. Text assertions cannot see this: the cell reads the same
    // whether its entries are laid out inline or stacked in block-level divs.
    // Asserting the computed display is what pins the change this PR made
    // (class="d-inline"); reverting to plain block divs fails here even though
    // the cell text is unchanged.
    //
    // Note: at this width the two entries do WRAP onto separate lines, because
    // inline content wraps when the cell is too narrow to hold it. That is
    // correct behaviour, so this asserts the inline formatting itself rather
    // than a shared baseline, which would only hold on a wide viewport.
    const displays = await specialtyItems.evaluateAll(
        nodes => nodes.map(node => getComputedStyle(node).display)
    );
    expect(displays).toEqual(["inline", "inline"]);
});
