// Generated by Skyramp v1.3.40 on 2026-09-02 08:00:21.781391452 +0000 UTC m=+854.798024255
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output vet-list-specialties-inline.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/vet_list_specialties_inline_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }, testInfo) => {
    test.setTimeout(61000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page, testInfo);

    const pageErrors: string[] = [];
    page.on('pageerror', error => pageErrors.push(error.message));

    await page.goto(`${baseUrl}/vets`);
    await expect(page).toHaveURL(/\/petclinic\/vets$/);

    await expect(page.getByRole('row', { name: 'Linda Douglas' }).getByRole('cell').nth(1)).toHaveText('dentistry surgery');
    await expect(page.getByRole('row', { name: 'Linda Douglas' }).getByRole('cell').nth(1).locator('div.d-inline')).toHaveCount(2);
    await expect(page.getByRole('row', { name: 'Rafael Ortega' }).getByRole('cell').nth(1)).toHaveText('surgery');
    await expect(page.getByRole('row', { name: 'Rafael Ortega' }).getByRole('cell').nth(1).locator('div.d-inline')).toHaveCount(1);

    await expect(page.getByText("NameSpecialties James Carter")).toHaveScreenshot("vets-table-inline-specialties.png", { maxDiffPixelRatio: 0.005 });

    expect(pageErrors).toHaveLength(0);
});
