// Generated by Skyramp v1.3.40 on 2026-09-02 07:58:32.006580918 +0000 UTC m=+745.023213711
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output vet-list-no-specialties-empty-state.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/vet_list_no_specialties_clean_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', error => pageErrors.push(error.message));

    await page.goto(`${baseUrl}/vets`);
    await expect(page).toHaveURL(/\/petclinic\/vets$/);
    await expect(page.getByRole("row")).toHaveCount(7);

    await expect(page.getByRole('cell', { name: 'No specialties', exact: true })).toHaveCount(2);
    await expect(page.getByRole('row', { name: 'James Carter' }).getByRole('cell').nth(1)).toHaveText('No specialties');
    await expect(page.getByRole('row', { name: 'Helen Leary' }).getByRole('cell').nth(1)).toHaveText('radiology');

    expect(pageErrors).toHaveLength(0);
});
