// Generated by Skyramp v1.3.40 on 2026-08-29 09:27:00.94169543 +0000 UTC m=+1100.429832905
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output vet_list_load_failure_shows_error_not_blank_table.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/vet_list_load_failure_shows_error_not_blank_table_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { forceVetsRequestToFail } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(baseUrl);
    await forceVetsRequestToFail(page);
    await page.getByRole("button", { name: "Veterinarians" }).click();
    await page.getByRole("link", { name: "All" }).click();

    // The vets request was forced to fail above, so the list renders no rows.
    await expect(page.getByRole("heading", { name: "Veterinarians" })).toBeVisible();
    await expect(page.locator("#vets tbody tr")).toHaveCount(0);

    // A failed load must tell the user something went wrong. VetListComponent assigns
    // errorMessage on the error path, but vet-list.component.html never renders it, so
    // the page shows an empty table with no explanation. This assertion documents that
    // bug and is expected to FAIL until the template surfaces the error.
    await expect(page.getByText(/error|failed|unable|could not/i).first()).toBeVisible();
});
