// Generated by Skyramp v1.3.40 on 2026-08-29 09:27:07.585482568 +0000 UTC m=+1107.073620033
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output vet_list_specialties_inline_and_empty_state.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/vet_list_specialties_inline_and_empty_state_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }, testInfo) => {
    test.setTimeout(838000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page, testInfo);

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Veterinarians" }).click();
    await page.getByRole("link", { name: "All" }).click();

    // A vet with no specialties must say so explicitly rather than leaving the cell blank.
    await expect(page.getByRole("row", { name: /James Carter/ }).getByRole("cell").nth(1)).toHaveText("No specialties");

    // A vet with two specialties must render both, together on a single line.
    await expect(page.getByRole("row", { name: /Linda Douglas/ }).getByRole("cell").nth(1)).toHaveText("dentistry surgery");

    // Text alone cannot tell inline rendering from stacked rendering, so pin the actual
    // layout of the two-specialty row with a visual baseline. Scoped to Linda Douglas's
    // row because it is the only multi-specialty vet no sibling spec mutates.
    await expect(page.getByRole("row", { name: /Linda Douglas/ })).toHaveScreenshot("vets-table-inline-specialties.png", { maxDiffPixelRatio: 0.005 });
});
