// Generated by Skyramp v1.3.40 on 2026-08-29 09:27:02.974646197 +0000 UTC m=+1102.462783662
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output vet_list_renders_all_specialties_after_adding_second.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/vet_list_renders_all_specialties_after_adding_second_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { toggleSpecialty, submitVetForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page, request }) => {
    test.setTimeout(493000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    // Normalize Helen Leary to exactly one specialty ("radiology") before the UI flow,
    // so this test is re-runnable regardless of what a previous run left in the database.
    // Ids are looked up by name rather than hardcoded.
    const vets = await (await request.get(`${baseUrl}/petclinic/api/vets`)).json();
    const specialties = await (await request.get(`${baseUrl}/petclinic/api/specialties`)).json();
    const vet = vets.find(v => v.firstName === "Helen" && v.lastName === "Leary");
    const specialty = specialties.find(s => s.name === "radiology");
    await request.put(`${baseUrl}/petclinic/api/vets/${vet.id}`, {
        data: { id: vet.id, firstName: vet.firstName, lastName: vet.lastName, specialties: [specialty] }
    });

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Veterinarians" }).click();
    await page.getByRole("link", { name: "All" }).click();

    // Helen Leary starts with exactly one specialty, radiology.
    await expect(page.getByRole("row", { name: /Helen Leary/ }).getByRole("cell").nth(1)).toHaveText("radiology");

    await page.getByRole("row", { name: /Helen Leary/ }).getByRole("button", { name: "Edit Vet" }).click();
    await toggleSpecialty(page, "surgery");
    await submitVetForm(page);

    // Both specialties must render together on one line, not just the first one.
    await expect(page.getByRole("row", { name: /Helen Leary/ }).getByRole("cell").nth(1)).toHaveText("radiology surgery");
    // Saving must not duplicate or drop a vet row (6 vets + 1 header row).
    await expect(page.getByRole("row")).toHaveCount(7);
});
