// Generated by Skyramp v1.3.40 on 2026-08-29 06:01:30.704651161 +0000 UTC m=+752.196939146
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output vets-list-deep-link-renders-table.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/vets_list_deep_link_renders_table_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    await page.goto(`${baseUrl}/petclinic/vets`);
    await expect(page.getByRole("heading", { name: "Veterinarians" })).toBeVisible();
    await expect(page.locator("#vets tbody > tr").first()).toBeVisible();
});
