// Generated by Skyramp v1.3.44 on 2026-09-08 19:04:28.868317621 +0000 UTC m=+685.981200875
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output vets-specialties-render.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/vets_specialties_render_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }, testInfo) => {
    test.setTimeout(259000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    const pageErrors: string[] = [];
    page.on('pageerror', error => pageErrors.push(error.message));
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page, testInfo);

    await page.goto(`${baseUrl}/`);
    await page.getByRole("button", { name: "Veterinarians" }).click();
    await page.getByRole("link", { name: "All" }).click();

    await expect(page.locator('#vets tbody tr')).toHaveCount(6);
    await expect(page.locator('#vets tbody tr:has-text("James Carter") td:nth-child(2)')).toHaveText('No specialties');
    await expect(page.locator('#vets tbody tr:has-text("Linda Douglas") td:nth-child(2)')).toHaveText('dentistry surgery');
    await expect(page.getByText("NameSpecialties James Carter")).toHaveScreenshot("vets-specialties-inline.png", { maxDiffPixelRatio: 0.005 });

    expect(pageErrors).toHaveLength(0);
});
