// Generated by Skyramp v1.3.44 on 2026-09-08 19:24:47.062271343 +0000 UTC m=+1972.065876003
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output visit_add_duration_out_of_range_blocked.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/visit_add_duration_out_of_range_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(92000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    await page.goto(`${baseUrl}/pets/7/visits/add`);
    await page.locator("#date").fill("2026-11-02");
    await page.locator("#description").fill("post-op check");
    await page.locator("#durationMinutes").fill("3");
    await expect(page.getByText("Duration must be between 5")).toContainText("Duration must be between 5 and 240 minutes");
    await expect(page.getByRole("spinbutton", { name: "Duration (minutes)" })).toHaveValue("3");
    await expect(page.getByRole("button", { name: "Add Visit" })).toBeDisabled();
    await page.getByRole("spinbutton", { name: "Duration (minutes)" }).fill("45");
    await expect(page.getByText("Duration must be between 5 and 240 minutes", { exact: true })).toBeHidden();
    await expect(page.getByRole("spinbutton", { name: "Duration (minutes)" })).toHaveValue("45");
    await expect(page.getByRole("button", { name: "Add Visit" })).toBeEnabled();

    expect(pageErrors, 'uncaught page errors').toEqual([]);
});
