// Generated by Skyramp v1.3.44 on 2026-09-08 19:24:42.426676466 +0000 UTC m=+1967.430281126
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output visit_add_duration_shows_in_list.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/visit_add_duration_shows_in_list_trace_1.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { submitNewVisitForm, revealLoadedVisitRows, deleteFirstVisit } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

// The test deletes the visit it created as its last step; this guard also removes
// it when an earlier assertion fails, so each run starts from the same state.
test.afterEach(async ({ request }) => {
    const listed = await request.get(`${baseUrl}/petclinic/api/visits`);
    if (!listed.ok()) {
        return;
    }
    for (const visit of await listed.json()) {
        if (visit.description === "dental cleaning") {
            await request.delete(`${baseUrl}/petclinic/api/visits/${visit.id}`);
        }
    }
});

test('testUi', async ({ page }) => {
    test.setTimeout(158000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    await page.goto(`${baseUrl}/pets/7/visits/add?after=save`);

    const playwrightRequest0: Record<string, any> = {
        "date": "2026-10-15",
        "description": "dental cleaning",
        "durationMinutes": 45
    };

    await submitNewVisitForm(
        page,
        getValue(playwrightRequest0, "date"),
        getValue(playwrightRequest0, "description"),
        getValue(playwrightRequest0, "durationMinutes")
    );

    const url0 = `${baseUrl}/pets/7/visits/add?after=save`;
    await page.goto(url0);
    await revealLoadedVisitRows(page);
    await expect(page.getByRole("cell", { name: "min" })).toContainText("45 min");
    // The seeded visit carries no duration, so its Duration cell renders empty.
    await expect(page.getByRole("row", { name: /spayed/ }).getByRole("cell").nth(2)).toHaveText("");
    await expect(page.getByRole("button", { name: "Delete Visit" })).toHaveCount(3);

    await deleteFirstVisit(page);

    const url1 = `${baseUrl}/pets/7/visits/add?after=delete`;
    await page.goto(url1);
    await revealLoadedVisitRows(page);
    await expect(page.getByRole("button", { name: "Delete Visit" })).toHaveCount(2);
    await expect(page.getByRole("cell", { name: "dental cleaning" })).toHaveCount(0);

    expect(pageErrors, 'uncaught page errors').toEqual([]);
});
