// Generated by Skyramp v1.3.44 on 2026-09-08 19:24:51.390327634 +0000 UTC m=+1976.393932294
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output visit_edit_duration_persists.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/visit_edit_duration_persists_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import type { Page } from '@playwright/test';
import { submitNewVisitForm, revealLoadedVisitRows, deleteFirstVisit } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

// This test asserts the duration the PR promises, so it stays red until the API
// keeps it — which means its in-page Delete Visit click is never reached. Remove
// the visit it created here so each run starts from the same state.
test.afterEach(async ({ request }) => {
    const listed = await request.get(`${baseUrl}/petclinic/api/visits`);
    if (!listed.ok()) {
        return;
    }
    for (const visit of await listed.json()) {
        if (visit.description === "x-ray review") {
            await request.delete(`${baseUrl}/petclinic/api/visits/${visit.id}`);
        }
    }
});

async function openFirstVisitEditForm(page: Page) {
    await page.locator("tr").getByRole("button", { name: "Edit Visit" }).first().click();
    // The form renders its loaded visit only after a change-detection pass.
    await page.getByRole("button", { name: "Back" }).hover();
}

async function submitEditVisitForm(page: Page, durationMinutes: number) {
    await page.locator("#durationMinutes").fill(durationMinutes.toString());
    await page.getByRole("button", { name: "Update Visit" }).click();
    // Saving redirects to the owner's detail page; wait for it before moving on.
    await expect(page.getByRole("heading", { name: "Owner Information" })).toBeVisible();
}

test('testUi', async ({ page }) => {
    test.setTimeout(338000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', (err) => pageErrors.push(err.message));

    const visitUpdateBodies: string[] = [];
    page.on('request', (req) => {
        if (req.method() === "PUT" && req.url().includes("/petclinic/api/visits/")) {
            visitUpdateBodies.push(req.postData() ?? "");
        }
    });

    await page.goto(`${baseUrl}/pets/7/visits/add`);

    const playwrightRequest0: Record<string, any> = {
        "date": "2026-12-01",
        "description": "x-ray review",
        "durationMinutes": 30
    };

    await submitNewVisitForm(
        page,
        getValue(playwrightRequest0, "date"),
        getValue(playwrightRequest0, "description"),
        getValue(playwrightRequest0, "durationMinutes")
    );

    const url0 = `${baseUrl}/pets/7/visits/add?after=save`;
    await page.goto(url0);
    await revealLoadedVisitRows(page);

    await openFirstVisitEditForm(page);

    await submitEditVisitForm(page, 90);

    // The Edit Visit form does send the new appointment length ...
    expect(visitUpdateBodies.length, 'one PUT to the visit').toBe(1);
    expect(JSON.parse(visitUpdateBodies[0] || "{}").durationMinutes, 'duration sent by the Edit Visit form').toBe(90);

    const url1 = `${baseUrl}/pets/7/visits/add?after=edit`;
    await page.goto(url1);
    await revealLoadedVisitRows(page);
    await expect(page.getByRole("row", { name: /x-ray review/ })).toContainText("2026-12-01");
    // ... so the visit list must show the changed length, as the PR describes.
    await expect(page.getByRole("row", { name: /x-ray review/ })).toContainText("90 min");

    await deleteFirstVisit(page);

    expect(pageErrors, 'uncaught page errors').toEqual([]);
});
