// Generated by Skyramp v1.3.44 on 2026-09-09 04:58:09.256604713 +0000 UTC m=+2080.443833413
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output visit_duration_range_guard_ui.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/visit_duration_range_guard_trace.zip

import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openAddVisitForm, fillVisitForm } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(94000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    await page.goto(`${baseUrl}/owners/6`);
    await expect(page.getByRole("button", { name: "Add Visit" })).toHaveCount(2);
    await expect(page.locator("th").filter({ hasText: "Duration" })).toHaveCount(2);

    await openAddVisitForm(page, 1);
    await fillVisitForm(page, "2026/09/15", "Skyramp duration range guard", 2);
    await expect(page.getByText("Duration must be between 5")).toContainText("Duration must be between 5 and 240 minutes");

    await page.getByRole("spinbutton", { name: "Duration (minutes)" }).fill("60");
    await expect(page.getByText("Duration must be between 5 and 240 minutes", { exact: true })).toBeHidden();
    await expect(page.getByRole("button", { name: "Add Visit" })).toBeEnabled();

    expect(pageErrors, 'uncaught page errors').toHaveLength(0);
});
