// Generated by Skyramp v1.3.40 on 2026-08-30 08:47:21.725029008 +0000 UTC m=+949.023256826
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output visit_add_duration_validation.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/visit_add_duration_validation_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { fillVisitForm, setVisitDuration } from './skyrampUtils';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(60000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', error => pageErrors.push(error));

    await page.goto(`${baseUrl}/pets/1/visits/add`);

    await fillVisitForm(page, "2026-09-15", "annual wellness exam", "300");
    await expect(page.getByText("Duration must be between 5")).toHaveText("Duration must be between 5 and 240 minutes");
    await expect(page.getByRole("button", { name: "Add Visit" })).toBeDisabled();
    await expect(page.getByRole("cell", { name: "Duration", exact: true })).toBeVisible();

    await setVisitDuration(page, "60");
    await expect(page.locator("#durationMinutes")).toHaveValue("60");
    await expect(page.getByText("Duration must be between 5 and 240 minutes")).toHaveCount(0);
    await expect(page.getByRole("button", { name: "Add Visit" })).toBeEnabled();

    expect(pageErrors).toHaveLength(0);
});
