// Generated by Skyramp v1.3.44 on 2026-09-09 04:58:07.149937342 +0000 UTC m=+2078.337166042
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output visit_duration_lifecycle_ui.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/visit_duration_lifecycle_trace.zip

import { test, expect, getBaseUrl, getValue, newSkyrampPlaywrightPage } from '@skyramp/skyramp';
import { openAddVisitForm, fillVisitForm, submitAddVisitForm, openEditVisitForm, setVisitDuration, submitEditVisitForm, deleteVisitRow } from './skyrampUtils';

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

const pageTimeout = 15000;

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(184000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: Error[] = [];
    page.on('pageerror', (error) => pageErrors.push(error));

    await page.goto(`${baseUrl}/owners/6`);
    await expect(page.locator("th").filter({ hasText: "Duration" }).first()).toBeVisible();

    await openAddVisitForm(page, 1);

    const playwrightRequest0: Record<string, any> = {
        "description": "Skyramp duration check",
        "durationMinutes": 60
    };

    await fillVisitForm(
        page,
        "2026/09/15",
        getValue(playwrightRequest0, "description"),
        getValue(playwrightRequest0, "durationMinutes")
    );

    const response0 = await submitAddVisitForm(page);

    expect(response0.status(), 'create visit status').toBe(201);
    const createdVisit = await response0.json();
    expect(createdVisit.durationMinutes, 'durationMinutes').toBe(60);
    expect(createdVisit.description, 'description').toBe("Skyramp duration check");
    expect(createdVisit.date, 'date').toBe("2026-09-15");
    expect(createdVisit.id, 'id').toBeGreaterThan(0);

    // Wait for network activities to finish
    await page.waitForTimeout(3000);

    await expect(page.locator("app-visit-list tr").filter({ hasText: "Skyramp duration check" }).first()).toContainText("60 min");

    await openEditVisitForm(page, 11);
    await expect(page.getByRole("spinbutton", { name: "Duration (minutes)" })).toHaveValue("60");

    await setVisitDuration(page, 90);
    await submitEditVisitForm(page);
    await expect(page.locator("app-visit-list tr").filter({ hasText: "Skyramp duration check" }).first()).toContainText("90 min");

    await deleteVisitRow(page, 11);
    await expect(page.locator("app-visit-list tr").filter({ hasText: "Skyramp duration check" })).toHaveCount(0);

    expect(pageErrors, 'uncaught page errors').toHaveLength(0);
});
