// Generated by Skyramp v1.3.40 on 2026-09-02 08:07:24.30213872 +0000 UTC m=+1324.577083633
// Command: skyramp generate ui rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output visit-list-duration-column-renders.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/e2e \
// 		--overwrite \
// 		--playwright-trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/.skyramp/visit_list_duration_column_renders_trace.zip

// Import of required libraries
import { test, expect, getBaseUrl, newSkyrampPlaywrightPage } from '@skyramp/skyramp';

const pageTimeout = 15000;

// URL for test requests
const baseUrl = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:4200");

test.use({
    viewport: { width: 1280, height: 900 },
});

test('testUi', async ({ page }) => {
    test.setTimeout(2000000);

    // set default timeout for all locator/page actions in this test
    page.setDefaultTimeout(pageTimeout);
    // Wrap playwright page with Skyramp page
    page = newSkyrampPlaywrightPage(page);

    const pageErrors: string[] = [];
    page.on('pageerror', error => pageErrors.push(error.message));

    await page.goto(baseUrl);
    await page.getByRole("button", { name: "Owners" }).click();
    await page.getByRole("link", { name: "Search" }).click();
    await expect(page.getByRole("cell", { name: "Max Samantha" })).toContainText("Samantha");
    await page.locator("a[href=\"/petclinic/owners/6\"]").click();
    await expect(page).toHaveURL(`${baseUrl}/petclinic/owners/6`);
    await expect(page.getByRole("heading", { name: "Pets and Visits" })).toBeVisible();
    await expect(page.locator("b.ownerFullName")).toHaveText("Jean Coleman");
    await expect(page.locator("app-owner-detail")).toContainText("Samantha");
    await expect(page.getByRole("columnheader", { name: "Duration" })).toBeVisible();

    expect(pageErrors, 'uncaught page errors').toEqual([]);
});
