// Generated by Skyramp v1.3.44 on 2026-09-08 19:09:02.043387767 +0000 UTC m=+1015.713966869
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output bulk_delete_owner_pets_removes_all_pets_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_bulk_delete_owner_pets_removes_all_pets.json

// Import of required libraries
import { test, expect, SkyrampClient, getResponseValue } from '@skyramp/skyramp';
import { createOwner, addPetToOwner, deleteOwnerPets, getOwner, deleteOwner } from './skyrampUtils';

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Request Body
    const ownersPostRequestBody: string = `{
        "address": "1 Bulk Way",
        "city": "Madison",
        "firstName": "Bulkdelete",
        "lastName": "Owner",
        "telephone": "6085550111"
    }`;

    const ownersPostResponse = await createOwner(client, ownersPostRequestBody);
    expect(ownersPostResponse.statusCode, 'status code').toBe(201);
    expect(Number(getResponseValue(ownersPostResponse, "id")), 'id').toBeGreaterThan(0);
    expect(getResponseValue(ownersPostResponse, "firstName"), 'firstName').toBe("Bulkdelete");
    expect(getResponseValue(ownersPostResponse, "lastName"), 'lastName').toBe("Owner");
    expect(getResponseValue(ownersPostResponse, "address"), 'address').toBe("1 Bulk Way");
    expect(getResponseValue(ownersPostResponse, "city"), 'city').toBe("Madison");
    expect(getResponseValue(ownersPostResponse, "telephone"), 'telephone').toBe("6085550111");
    expect((getResponseValue(ownersPostResponse, "pets") as unknown[]).length, 'pets length').toBe(0);

    const ownerId = getResponseValue(ownersPostResponse, "id");

    // Request Body
    const petsPostRequestBody: string = `{
        "birthDate": "2020-01-01",
        "name": "BulkPetOne",
        "type": {
            "id": 1,
            "name": "cat"
        }
    }`;

    const petsPostResponse = await addPetToOwner(client, ownerId, petsPostRequestBody);
    expect(petsPostResponse.statusCode, 'status code').toBe(201);
    expect(Number(getResponseValue(petsPostResponse, "id")), 'id').toBeGreaterThan(0);
    expect(getResponseValue(petsPostResponse, "name"), 'name').toBe("BulkPetOne");
    expect(getResponseValue(petsPostResponse, "birthDate"), 'birthDate').toBe("2020-01-01");
    expect(Number(getResponseValue(petsPostResponse, "type.id")), 'type id').toBe(1);
    expect(getResponseValue(petsPostResponse, "type.name"), 'type name').toBe("cat");
    expect(String(getResponseValue(petsPostResponse, "ownerId")), 'ownerId').toBe(String(ownerId));

    // Request Body
    const petsPost1RequestBody: string = `{
        "birthDate": "2021-02-02",
        "name": "BulkPetTwo",
        "type": {
            "id": 1,
            "name": "cat"
        }
    }`;

    const petsPost1Response = await addPetToOwner(client, ownerId, petsPost1RequestBody);
    expect(petsPost1Response.statusCode, 'status code').toBe(201);
    expect(Number(getResponseValue(petsPost1Response, "id")), 'id').toBeGreaterThan(0);
    expect(getResponseValue(petsPost1Response, "name"), 'name').toBe("BulkPetTwo");
    expect(getResponseValue(petsPost1Response, "birthDate"), 'birthDate').toBe("2021-02-02");
    expect(Number(getResponseValue(petsPost1Response, "type.id")), 'type id').toBe(1);
    expect(getResponseValue(petsPost1Response, "type.name"), 'type name').toBe("cat");
    expect(String(getResponseValue(petsPost1Response, "ownerId")), 'ownerId').toBe(String(ownerId));

    const petsDeleteResponse = await deleteOwnerPets(client, ownerId);
    expect(petsDeleteResponse.statusCode, 'status code').toBe(204);

    const ownersOwnersGetResponse = await getOwner(client, ownerId);
    expect(ownersOwnersGetResponse.statusCode, 'status code').toBe(200);
    expect((getResponseValue(ownersOwnersGetResponse, "pets") as unknown[]).length, 'pets length after bulk delete').toBe(0);
    expect(getResponseValue(ownersOwnersGetResponse, "pets.0"), 'first pet after bulk delete').toBeNull();
    expect(String(getResponseValue(ownersOwnersGetResponse, "id")), 'id').toBe(String(ownerId));
    expect(getResponseValue(ownersOwnersGetResponse, "firstName"), 'firstName').toBe("Bulkdelete");
    expect(getResponseValue(ownersOwnersGetResponse, "lastName"), 'lastName').toBe("Owner");
    expect(getResponseValue(ownersOwnersGetResponse, "address"), 'address').toBe("1 Bulk Way");
    expect(getResponseValue(ownersOwnersGetResponse, "city"), 'city').toBe("Madison");
    expect(getResponseValue(ownersOwnersGetResponse, "telephone"), 'telephone').toBe("6085550111");

    const ownersOwnersDeleteResponse = await deleteOwner(client, ownerId);
    expect(ownersOwnersDeleteResponse.statusCode, 'status code').toBe(204);
});
