// Generated by Skyramp v1.3.40 on 2026-09-02 07:59:49.490427104 +0000 UTC m=+841.075317561
// Command: skyramp generate contract rest http://localhost:9966/petclinic/api/owners/1/pets/1/visits \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output contract_owner_pet_visits_post_description_over_30.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--provider \
// 		--provider-output contract_owner_pet_visits_post_description_over_30.spec.ts \
// 		--request-data {"date":"2026-09-02","description":"ccccccccccccccccccccccccccccccc"} \
// 		--response-status-code 400 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

// contract test for /petclinic/api/owners/1/pets/1/visits POST
test('testVisitsPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const visitsPostRequestBody: string = `{
        "date": "2026-09-02",
        "description": "ccccccccccccccccccccccccccccccc"
    }`;

    // Execute Request
    const visitsPostResponse = await client.sendRequest({
        url: URL,
        path: "/petclinic/api/owners/1/pets/1/visits",
        method: "POST",
        body: visitsPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(visitsPostResponse.statusCode, 'status code').toBe(400);
    expect(getValue(visitsPostResponse, "title"), 'title').toBe("MethodArgumentNotValidException");
    expect(getValue(visitsPostResponse, "detail"), 'detail').toBe("The request contains invalid or missing parameters");
    expect(Number(getValue(visitsPostResponse, "status")), 'status').toBe(400);
    expect(getValue(visitsPostResponse, "instance"), 'instance').toBe("/petclinic/api/owners/1/pets/1/visits");
    expect(getValue(visitsPostResponse, "schemaValidationErrors.0.field"), 'field').toBe("description");
    expect(getValue(visitsPostResponse, "schemaValidationErrors.0.defaultMessage"), 'defaultMessage').toBe("size must be between 1 and 30");
    expect(getValue(visitsPostResponse, "schemaValidationErrors.0.rejectedValue"), 'rejectedValue').toBe("ccccccccccccccccccccccccccccccc");
    expect(getValue(visitsPostResponse, "schemaValidationErrors.1")).toBeNull();
});
