// Generated by Skyramp v1.3.40 on 2026-09-02 08:09:48.094103455 +0000 UTC m=+1410.603696357
// Command: skyramp generate contract rest http://localhost:9966/petclinic/api/owners/{ownerId} \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_owners_get_problem_detail.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--path-params ownerId=abc \
// 		--provider \
// 		--provider-output contract_owners_get_problem_detail.spec.ts \
// 		--response-status-code 500 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, checkSchema } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

// contract test for /petclinic/api/owners/{ownerId} GET
test('testOwnersOwnerIdGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Declaration of variables
    const ownerId = "abc";

    // Execute Request
    const ownersOwnerIdGetResponse = await client.sendRequest({
        url: URL,
        path: "/petclinic/api/owners/{ownerId}",
        method: "GET",
        headers: headers,
        pathParams: {"ownerId": ownerId}
    });

    // Generated Assertions
    expect(ownersOwnerIdGetResponse.statusCode, 'status code').toBe(500);
    expect(getValue(ownersOwnerIdGetResponse, "status"), 'status').toBe(500);
    expect(getValue(ownersOwnerIdGetResponse, "title"), 'title').toBe("MethodArgumentTypeMismatchException");
    expect(getValue(ownersOwnerIdGetResponse, "detail"), 'detail').toBe("An unexpected error occurred while processing your request");
    expect(getValue(ownersOwnerIdGetResponse, "instance"), 'instance').toBe("/petclinic/api/owners/abc");
    expect(getValue(ownersOwnerIdGetResponse, "timestamp"), 'timestamp').toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(checkSchema(ownersOwnerIdGetResponse, '{"validationErrors": []}'), 'validationErrors present and empty').toBe(true);
    expect(getValue(ownersOwnerIdGetResponse, "validationErrors.0.message"), 'validationErrors first item').toBeNull();
});
