// Generated by Skyramp v1.3.40 on 2026-09-02 07:54:47.462558067 +0000 UTC m=+583.084794286
// Command: skyramp generate contract rest http://localhost:9966/petclinic/api/owners \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output contract_owner_create_city_120.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--provider \
// 		--request-data {"firstName":"Ada","lastName":"Lovelace","address":"12 Analytical Way","city":"Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogochxxx","telephone":"6085551234"} \
// 		--response-status-code 201 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

// contract test for /petclinic/api/owners POST
test('testOwnersPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const ownersPostRequestBody: string = `{
        "address": "12 Analytical Way",
        "city": "Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogochxxx",
        "firstName": "Ada",
        "lastName": "Lovelace",
        "telephone": "6085551234"
    }`;

    // Execute Request
    const ownersPostResponse = await client.sendRequest({
        url: URL,
        path: "/petclinic/api/owners",
        method: "POST",
        body: ownersPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(ownersPostResponse.statusCode, 'status code').toBe(201);
    expect(getValue(ownersPostResponse, "city"), 'city').toBe("Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogochxxx");
    expect((getValue(ownersPostResponse, "city") as string).length, 'city length').toBe(120);
    expect(getValue(ownersPostResponse, "firstName"), 'firstName').toBe("Ada");
    expect(getValue(ownersPostResponse, "lastName"), 'lastName').toBe("Lovelace");
    expect(getValue(ownersPostResponse, "address"), 'address').toBe("12 Analytical Way");
    expect(getValue(ownersPostResponse, "telephone"), 'telephone').toBe("6085551234");
    expect(getValue(ownersPostResponse, "id"), 'id').toBeGreaterThan(0);
    expect(getValue(ownersPostResponse, "pets.0"), 'pets.0').toBeNull();
});
