// Generated by Skyramp v1.3.40 on 2026-09-02 08:10:00.119114384 +0000 UTC m=+1198.445833349
// Command: skyramp generate contract rest http://localhost:9966/petclinic/api/owners \
// 		--api-schema /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-rest/src/main/resources/openapi.yml \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output contract_owner_create_telephone_exact_ten_accepted.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--provider \
// 		--provider-output contract_owner_create_telephone_exact_ten_accepted.spec.ts \
// 		--request-data {"firstName":"Boundary","lastName":"Exact","address":"1 Test St","city":"Madison","telephone":"6085551234"} \
// 		--response-status-code 201 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

// contract test for /petclinic/api/owners POST
test('testOwnersPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const ownersPostRequestBody: string = `{
        "address": "1 Test St",
        "city": "Madison",
        "firstName": "Boundary",
        "lastName": "Exact",
        "telephone": "6085551234"
    }`;

    // Expected Response Body
    const expectedOwnersPostResponseBody: string = `{
        "address": "1 Test St",
        "city": "Madison",
        "firstName": "Boundary",
        "lastName": "Exact",
        "telephone": "6085551234",
        "pets": [],
        "id": 1
    }`;

    // Execute Request
    const ownersPostResponse = await client.sendRequest({
        url: URL,
        path: "/petclinic/api/owners",
        method: "POST",
        body: ownersPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(ownersPostResponse.statusCode, 'status code').toBe(201);
    expect(checkSchema(ownersPostResponse, expectedOwnersPostResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(ownersPostResponse, "address"), 'value').not.toBeNull();
    expect(getResponseValue(ownersPostResponse, "city"), 'value').not.toBeNull();
    expect(getResponseValue(ownersPostResponse, "firstName"), 'value').not.toBeNull();
    expect(getResponseValue(ownersPostResponse, "telephone"), 'telephone').toBe("6085551234");
    expect(getResponseValue(ownersPostResponse, "firstName"), 'firstName').toBe("Boundary");
    expect(getResponseValue(ownersPostResponse, "lastName"), 'lastName').toBe("Exact");
    expect(getResponseValue(ownersPostResponse, "address"), 'address').toBe("1 Test St");
    expect(getResponseValue(ownersPostResponse, "city"), 'city').toBe("Madison");
    expect(getResponseValue(ownersPostResponse, "id"), 'id').toBeGreaterThan(0);
    expect(getResponseValue(ownersPostResponse, "pets.0"), 'no pets').toBeNull();
});
