// Generated by Skyramp v1.3.40 on 2026-08-29 04:48:39.568771476 +0000 UTC m=+619.356340073
// Command: skyramp generate contract rest http://localhost:9966/petclinic/api/owners \
// 		--api-schema /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-rest/src/main/resources/openapi.yml \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output contract_owner_city_120_char_boundary.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--provider \
// 		--request-data {"firstName":"Boundary","lastName":"Tester","address":"1 Test St.","city":"AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","telephone":"6085551023"} \
// 		--response-status-code 201 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

// contract test for /petclinic/api/owners POST
test('testOwnersPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const ownersPostRequestBody: string = `{
        "address": "1 Test St.",
        "city": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "firstName": "Boundary",
        "lastName": "Tester",
        "telephone": "6085551023"
    }`;

    // Expected Response Body
    const expectedOwnersPostResponseBody: string = `{
        "address": "110 W. Liberty St.",
        "city": "Madison",
        "firstName": "George",
        "lastName": "Franklin",
        "pets": [
            {
                "birthDate": "2010-09-07",
                "id": 1,
                "name": "Leo",
                "type": {
                    "id": 1,
                    "name": "cat"
                },
                "visits": [
                    {
                        "description": "rabies shot",
                        "id": 1,
                        "petId": 1
                    }
                ]
            }
        ],
        "telephone": "6085551023"
    }`;

    // Execute Request
    const ownersPostResponse = await client.sendRequest({
        url: URL,
        path: "/petclinic/api/owners",
        method: "POST",
        body: ownersPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(ownersPostResponse.statusCode, 'status code').toBe(201);
    expect(checkSchema(ownersPostResponse, expectedOwnersPostResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(ownersPostResponse, "address"), 'address').toBe("1 Test St.");
    expect(getResponseValue(ownersPostResponse, "city"), 'city').toBe("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    expect(String(getResponseValue(ownersPostResponse, "city")).length, 'city length').toBe(120);
    expect(getResponseValue(ownersPostResponse, "firstName"), 'firstName').toBe("Boundary");
    expect(getResponseValue(ownersPostResponse, "lastName"), 'lastName').toBe("Tester");
    expect(getResponseValue(ownersPostResponse, "telephone"), 'telephone').toBe("6085551023");
    expect(Number(getResponseValue(ownersPostResponse, "id")), 'id').toBeGreaterThan(0);
});
