// Generated by Skyramp v1.3.40 on 2026-09-02 07:58:07.009316085 +0000 UTC m=+704.025907217
// Command: skyramp generate contract rest http://localhost:9966/petclinic/api/owners \
// 		--api-schema http://localhost:9966/petclinic/v3/api-docs \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output contract_owners_list_includes_pets.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--provider \
// 		--response-data [{"firstName":"George","lastName":"Franklin","address":"110 W. Liberty St.","city":"Madison","telephone":"6085551023","pets":[{"name":"Leo","birthDate":"2010-09-07","type":{"name":"cat","id":1},"id":1,"visits":[],"ownerId":1}],"id":1}] \
// 		--response-status-code 200 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

// contract test for /petclinic/api/owners GET
test('testOwnersGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedOwnersGetResponseBody: string = `[
        {
            "address": "110 W. Liberty St.",
            "city": "Madison",
            "firstName": "George",
            "id": 1,
            "lastName": "Franklin",
            "pets": [
                {
                    "birthDate": "2010-09-07",
                    "id": 1,
                    "name": "Leo",
                    "ownerId": 1,
                    "type": {
                        "id": 1,
                        "name": "cat"
                    },
                    "visits": []
                }
            ],
            "telephone": "6085551023"
        }
    ]`;

    // Execute Request
    const ownersGetResponse = await client.sendRequest({
        url: URL,
        path: "/petclinic/api/owners",
        method: "GET",
        headers: headers,
        queryParams: {"lastName": null}
    });

    // Generated Assertions
    expect(ownersGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(ownersGetResponse, expectedOwnersGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(ownersGetResponse, "0.address"), 'value').not.toBeNull();
    expect(getResponseValue(ownersGetResponse, "0.city"), 'value').not.toBeNull();
    expect(getResponseValue(ownersGetResponse, "0.firstName"), 'value').not.toBeNull();
    expect(getResponseValue(ownersGetResponse, "0.id"), 'id').toBe(1);
    expect(getResponseValue(ownersGetResponse, "0.firstName"), 'firstName').toBe("George");
    expect(getResponseValue(ownersGetResponse, "0.lastName"), 'lastName').toBe("Franklin");
    expect(getResponseValue(ownersGetResponse, "0.address"), 'address').toBe("110 W. Liberty St.");
    expect(getResponseValue(ownersGetResponse, "0.city"), 'city').toBe("Madison");
    expect(getResponseValue(ownersGetResponse, "0.telephone"), 'telephone').toBe("6085551023");
    expect(getResponseValue(ownersGetResponse, "0.pets"), 'pets').toHaveLength(1);
    expect(getResponseValue(ownersGetResponse, "0.pets.0.name"), 'pets.0.name').toBe("Leo");
    expect(getResponseValue(ownersGetResponse, "0.pets.0.type.name"), 'pets.0.type.name').toBe("cat");
    expect(getResponseValue(ownersGetResponse, "0.pets.0.ownerId"), 'pets.0.ownerId').toBe(1);
    expect(getResponseValue(ownersGetResponse, "0.pets.1"), 'pets.1').toBeNull();
});
