// Generated by Skyramp v1.3.40 on 2026-09-02 08:04:41.163946812 +0000 UTC m=+1188.949572669
// Command: skyramp generate contract rest http://localhost:9966/petclinic/api/v2/owners \
// 		--api-schema /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-rest/src/main/resources/openapi.yml \
// 		--framework playwright \
// 		--language typescript \
// 		--method GET \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--provider \
// 		--provider-output contract_v2_owners_default_page_size.spec.ts \
// 		--response-status-code 200 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

// contract test for /petclinic/api/v2/owners GET
test('testOwnersGet', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Expected Response Body
    const expectedOwnersGetResponseBody: string = `{
        "content": [
            {
                "address": "110 W. Liberty St.",
                "city": "Madison",
                "firstName": "George",
                "lastName": "Franklin",
                "pets": [
                    {
                        "birthDate": "2010-09-07",
                        "id": 1,
                        "name": "Leo",
                        "type": {
                            "id": 1,
                            "name": "cat"
                        },
                        "visits": [
                            {
                                "description": "rabies shot",
                                "id": 1,
                                "petId": 1
                            }
                        ]
                    }
                ],
                "telephone": "6085551023"
            }
        ],
        "page": 0,
        "size": 5,
        "totalElements": 10,
        "totalPages": 2
    }`;

    // Execute Request
    const ownersGetResponse = await client.sendRequest({
        url: URL,
        path: "/petclinic/api/v2/owners",
        method: "GET",
        headers: headers,
    });

    // Generated Assertions
    expect(ownersGetResponse.statusCode, 'status code').toBe(200);
    expect(checkSchema(ownersGetResponse, expectedOwnersGetResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(ownersGetResponse, "page"), 'page').toBe(0);
    expect(getResponseValue(ownersGetResponse, "size"), 'default page size').toBe(5);
    expect(getResponseValue(ownersGetResponse, "totalElements"), 'totalElements').toBe(10);
    expect(getResponseValue(ownersGetResponse, "totalPages"), 'totalPages').toBe(2);
    expect(getResponseValue(ownersGetResponse, "content.4.lastName") ?? null, 'fifth owner present').not.toBeNull();
    expect(getResponseValue(ownersGetResponse, "content.5.lastName") ?? null, 'no sixth owner on the first page').toBeNull();
    expect(getResponseValue(ownersGetResponse, "content.0.firstName"), 'first owner firstName').toBe("George");
    expect(getResponseValue(ownersGetResponse, "content.0.lastName"), 'first owner lastName').toBe("Franklin");
    expect(getResponseValue(ownersGetResponse, "content.0.address"), 'first owner address').toBe("110 W. Liberty St.");
    expect(getResponseValue(ownersGetResponse, "content.0.city"), 'first owner city').toBe("Madison");
    expect(getResponseValue(ownersGetResponse, "content.0.telephone"), 'first owner telephone').toBe("6085551023");
    expect(getResponseValue(ownersGetResponse, "content.4.lastName"), 'fifth owner lastName').toBe("McTavish");
    expect(getResponseValue(ownersGetResponse, "content.0.address"), 'value').not.toBeNull();
    expect(getResponseValue(ownersGetResponse, "content.0.city"), 'value').not.toBeNull();
    expect(getResponseValue(ownersGetResponse, "content.0.firstName"), 'value').not.toBeNull();
});
