// Generated by Skyramp v1.3.40 on 2026-09-02 08:09:51.78176018 +0000 UTC m=+1190.108479145
// Command: skyramp generate contract rest http://localhost:9966/petclinic/api/owners \
// 		--api-schema /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-rest/src/main/resources/openapi.yml \
// 		--framework playwright \
// 		--language typescript \
// 		--method POST \
// 		--output contract_owner_create_telephone_above_maximum_rejected.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--provider \
// 		--provider-output contract_owner_create_telephone_above_maximum_rejected.spec.ts \
// 		--request-data {"firstName":"Boundary","lastName":"Long","address":"1 Test St","city":"Madison","telephone":"60855512345"} \
// 		--response-status-code 400 \
// 		--runtime local \
// 		--skipProvisionParents

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getResponseValue } from '@skyramp/skyramp';

// URL for test requests
const URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

// contract test for /petclinic/api/owners POST
test('testOwnersPost', async () => {
    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Definition of authentication header
    const headers: Record<string, string> = {};
    if (process.env.SKYRAMP_TEST_TOKEN && process.env.SKYRAMP_TEST_TOKEN != "") {
        headers["Authorization"] = "Bearer " + process.env.SKYRAMP_TEST_TOKEN;
    }

    // Request Body
    const ownersPostRequestBody: string = `{
        "address": "1 Test St",
        "city": "Madison",
        "firstName": "Boundary",
        "lastName": "Long",
        "telephone": "60855512345"
    }`;

    // Expected Response Body
    const expectedOwnersPostResponseBody: string = `{
        "detail": "The request contains invalid or missing parameters",
        "instance": "/petclinic/api/owners",
        "status": 400,
        "title": "MethodArgumentNotValidException",
        "type": "http://localhost:9966/petclinic/api/owners",
        "timestamp": "2026-09-02T08:13:46.016552272Z",
        "schemaValidationErrors": [
            {
                "message": "Field 'telephone' size must be between 10 and 10 (rejected value: 60855512345)",
                "field": "telephone",
                "defaultMessage": "size must be between 10 and 10",
                "rejectedValue": "60855512345"
            }
        ]
    }`;

    // Execute Request
    const ownersPostResponse = await client.sendRequest({
        url: URL,
        path: "/petclinic/api/owners",
        method: "POST",
        body: ownersPostRequestBody,
        headers: headers
    });

    // Generated Assertions
    expect(ownersPostResponse.statusCode, 'status code').toBe(400);
    expect(checkSchema(ownersPostResponse, expectedOwnersPostResponseBody), 'schema').toBeTruthy();
    expect(getResponseValue(ownersPostResponse, "detail"), 'value').not.toBeNull();
    expect(getResponseValue(ownersPostResponse, "schemaValidationErrors.0.message"), 'value').not.toBeNull();
    expect(getResponseValue(ownersPostResponse, "status"), 'value').not.toBeNull();
    expect(getResponseValue(ownersPostResponse, "detail"), 'detail').toBe("The request contains invalid or missing parameters");
    expect(getResponseValue(ownersPostResponse, "title"), 'title').toBe("MethodArgumentNotValidException");
    expect(getResponseValue(ownersPostResponse, "status"), 'status').toBe(400);
    expect(getResponseValue(ownersPostResponse, "instance"), 'instance').toBe("/petclinic/api/owners");
    expect(getResponseValue(ownersPostResponse, "timestamp"), 'timestamp').toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getResponseValue(ownersPostResponse, "schemaValidationErrors.0.field"), 'error 0 field').toBe("telephone");
    expect(getResponseValue(ownersPostResponse, "schemaValidationErrors.0.rejectedValue"), 'error 0 rejected value').toBe("60855512345");
    expect(getResponseValue(ownersPostResponse, "schemaValidationErrors.1.field"), 'error 1 field').toBe("telephone");
    expect(getResponseValue(ownersPostResponse, "schemaValidationErrors.1.rejectedValue"), 'error 1 rejected value').toBe("60855512345");
    expect(getResponseValue(ownersPostResponse, "schemaValidationErrors.2"), 'no third error').toBeNull();
});
