// Generated by Skyramp v1.3.44 on 2026-09-08 19:07:15.699467243 +0000 UTC m=+942.128024477
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_page_envelope_and_paging_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_owners_page_envelope_and_paging.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import { getOwnersPage } from './skyrampUtils';

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Declaration of variables
    const lastName = "Zzzq";

    const ownersGetResponse = await getOwnersPage(client);

    expect(ownersGetResponse.statusCode, 'status code').toBe(200);

    expect(getResponseValue(ownersGetResponse, "page"), 'page index of the default page').toBe(0);
    expect(getResponseValue(ownersGetResponse, "size"), 'default page size').toBe(5);
    expect(getResponseValue(ownersGetResponse, "totalElements"), 'owners in the clinic').toBe(10);
    expect(getResponseValue(ownersGetResponse, "totalPages"), 'pages at the default size').toBe(2);
    expect(getResponseValue(ownersGetResponse, "content").length, 'owners on the default page').toBe(5);
    expect(getResponseValue(ownersGetResponse, "content.5"), 'no sixth owner on the default page').toBeNull();
    // totalPages is ceil(totalElements / size)
    expect(getResponseValue(ownersGetResponse, "totalPages"), 'totalPages is derived from totalElements and size').toBe(
        Math.ceil(getResponseValue(ownersGetResponse, "totalElements") / getResponseValue(ownersGetResponse, "size"))
    );
    // The default page carries fewer owners than the clinic holds - this is what the owners list renders.
    expect(getResponseValue(ownersGetResponse, "content").length, 'the default page is a strict subset of all owners')
        .toBeLessThan(getResponseValue(ownersGetResponse, "totalElements"));
    expect(getResponseValue(ownersGetResponse, "content.0.id"), 'first owner id').toBe(1);
    expect(getResponseValue(ownersGetResponse, "content.0.lastName"), 'first owner last name').toBe("Franklin");
    expect(getResponseValue(ownersGetResponse, "content.4.id"), 'last owner id on the default page').toBe(5);
    expect(getResponseValue(ownersGetResponse, "content.4.lastName"), 'last owner last name on the default page').toBe("McTavish");

    const ownersGet1Response = await getOwnersPage(client, {"page": ["1"]});

    expect(ownersGet1Response.statusCode, 'status code').toBe(200);

    expect(getResponseValue(ownersGet1Response, "page"), 'page index reflects the requested page').toBe(1);
    expect(getResponseValue(ownersGet1Response, "size"), 'page size is unchanged on page 1').toBe(5);
    expect(getResponseValue(ownersGet1Response, "totalElements"), 'totalElements counts every owner, not the page').toBe(10);
    expect(getResponseValue(ownersGet1Response, "totalPages"), 'totalPages is unchanged on page 1').toBe(2);
    expect(getResponseValue(ownersGet1Response, "content").length, 'owners on the second page').toBe(5);
    expect(getResponseValue(ownersGet1Response, "content.5"), 'no sixth owner on the second page').toBeNull();
    // The second page holds the owners the default page omits, Carlos Estaban last among them.
    expect(getResponseValue(ownersGet1Response, "content.0.id"), 'second page starts after the first').toBe(6);
    expect(getResponseValue(ownersGet1Response, "content.0.lastName"), 'first owner on the second page').toBe("Coleman");
    expect(getResponseValue(ownersGet1Response, "content.4.id"), 'Carlos Estaban id').toBe(10);
    expect(getResponseValue(ownersGet1Response, "content.4.firstName"), 'Carlos Estaban first name').toBe("Carlos");
    expect(getResponseValue(ownersGet1Response, "content.4.lastName"), 'Carlos Estaban last name').toBe("Estaban");
    expect(getResponseValue(ownersGet1Response, "content.0.id"), 'the second page holds different owners than the first')
        .not.toBe(getResponseValue(ownersGetResponse, "content.0.id"));

    const filteredLastName = getResponseValue(ownersGetResponse, "content.1.lastName");

    const ownersGet2Response = await getOwnersPage(client, {"lastName": [filteredLastName]});

    expect(ownersGet2Response.statusCode, 'status code').toBe(200);

    expect(filteredLastName, 'the last name chained from the default page').toBe("Davis");
    expect(getResponseValue(ownersGet2Response, "page"), 'filtered result starts at page 0').toBe(0);
    expect(getResponseValue(ownersGet2Response, "size"), 'filtered result keeps the default page size').toBe(5);
    expect(getResponseValue(ownersGet2Response, "totalElements"), 'owners named Davis').toBe(2);
    expect(getResponseValue(ownersGet2Response, "totalPages"), 'the filtered result fits on one page').toBe(1);
    expect(getResponseValue(ownersGet2Response, "content").length, 'owners returned by the filter').toBe(2);
    expect(getResponseValue(ownersGet2Response, "content.2"), 'no third owner matches the filter').toBeNull();
    // A single-page result returns every match it counted.
    expect(getResponseValue(ownersGet2Response, "content").length, 'a single page returns every counted match')
        .toBe(getResponseValue(ownersGet2Response, "totalElements"));
    // Every owner returned carries the last name that was sent.
    expect(getResponseValue(ownersGet2Response, "content.0.lastName"), 'first match honours the filter').toBe(filteredLastName);
    expect(getResponseValue(ownersGet2Response, "content.1.lastName"), 'second match honours the filter').toBe(filteredLastName);
    expect(getResponseValue(ownersGet2Response, "content.0.id"), 'Betty Davis id').toBe(2);
    expect(getResponseValue(ownersGet2Response, "content.0.firstName"), 'Betty Davis first name').toBe("Betty");
    expect(getResponseValue(ownersGet2Response, "content.1.id"), 'Harold Davis id').toBe(4);
    expect(getResponseValue(ownersGet2Response, "content.1.firstName"), 'Harold Davis first name').toBe("Harold");
    // The filter narrows the result rather than returning the whole clinic.
    expect(getResponseValue(ownersGet2Response, "totalElements"), 'the filter narrows the total')
        .toBeLessThan(getResponseValue(ownersGetResponse, "totalElements"));

    const ownersGet3Response = await getOwnersPage(client, {"lastName": [lastName]});

    expect(ownersGet3Response.statusCode, 'status code').toBe(200);

    // A last name no owner has returns an empty page, not the unfiltered list.
    expect(getResponseValue(ownersGet3Response, "page"), 'unmatched filter starts at page 0').toBe(0);
    expect(getResponseValue(ownersGet3Response, "size"), 'unmatched filter keeps the default page size').toBe(5);
    expect(getResponseValue(ownersGet3Response, "totalElements"), 'no owner is named Zzzq').toBe(0);
    expect(getResponseValue(ownersGet3Response, "totalPages"), 'an empty result spans no pages').toBe(0);
    expect(getResponseValue(ownersGet3Response, "content").length, 'the unmatched filter returns no owners').toBe(0);
    expect(getResponseValue(ownersGet3Response, "content.0"), 'the empty page has no first owner').toBeNull();
});
