// Generated by Skyramp v1.3.44 on 2026-09-08 19:16:20 +0000 UTC
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_email_create_read_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_owner_email_create_read.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import { createOwner, updateOwner, getOwner, deleteOwner } from './skyrampUtils';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");
test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Request Body
    const ownersPostRequestBody: string = `{
        "address": "1 Test Way",
        "city": "Madison",
        "email": "emma.roundtrip@example.com",
        "firstName": "Emma",
        "lastName": "Roundtrip",
        "telephone": "6085551000"
    }`;

    const ownersPostResponse = await createOwner(client, URL_localhost, ownersPostRequestBody);

    expect(ownersPostResponse.statusCode, 'status code').toBe(201);

    expect(getResponseValue(ownersPostResponse, "email"), 'email').toBe("emma.roundtrip@example.com");
    expect(getResponseValue(ownersPostResponse, "firstName"), 'firstName').toBe("Emma");
    expect(getResponseValue(ownersPostResponse, "lastName"), 'lastName').toBe("Roundtrip");
    expect(getResponseValue(ownersPostResponse, "address"), 'address').toBe("1 Test Way");
    expect(getResponseValue(ownersPostResponse, "city"), 'city').toBe("Madison");
    expect(getResponseValue(ownersPostResponse, "telephone"), 'telephone').toBe("6085551000");
    expect(getResponseValue(ownersPostResponse, "id"), 'id').toBeGreaterThan(0);

    const ownersOwnersGetResponse = await getOwner(client, URL_localhost, getResponseValue(ownersPostResponse, "id"));

    expect(ownersOwnersGetResponse.statusCode, 'status code').toBe(200);

    expect(getResponseValue(ownersOwnersGetResponse, "email"), 'email round-trips through the store').toBe("emma.roundtrip@example.com");
    expect(getResponseValue(ownersOwnersGetResponse, "id"), 'id').toBe(getResponseValue(ownersPostResponse, "id"));
    expect(getResponseValue(ownersOwnersGetResponse, "firstName"), 'firstName').toBe("Emma");
    expect(getResponseValue(ownersOwnersGetResponse, "lastName"), 'lastName').toBe("Roundtrip");
    expect(getResponseValue(ownersOwnersGetResponse, "telephone"), 'telephone').toBe("6085551000");

    const owners999999GetResponse = await getOwner(client, URL_localhost, 999999);

    expect(owners999999GetResponse.statusCode, 'status code').toBe(404);

    const ownersOwnersDeleteResponse = await deleteOwner(client, URL_localhost, getResponseValue(ownersPostResponse, "id"));

    expect(ownersOwnersDeleteResponse.statusCode, 'status code').toBe(204);
});
