// Generated by Skyramp v1.3.44 on 2026-09-08 19:07:28.912345678 +0000 UTC m=+955.340902931
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_page_parameter_bounds_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_owners_page_parameter_bounds.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import { getOwnersPage } from './skyrampUtils';

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Declaration of variables
    const page = "-1";
    const page_1 = "0";
    const size = "101";
    const size_1 = "0";

    const ownersGetResponse = await getOwnersPage(client, {"page": [page_1], "size": ["1"]}, 200);

    expect(ownersGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(ownersGetResponse, "page"), 'response echoes the requested page').toBe(0);
    expect(getResponseValue(ownersGetResponse, "size"), 'response echoes size at its declared minimum').toBe(1);
    expect(getResponseValue(ownersGetResponse, "content").length, 'a page of one holds one owner').toBe(1);
    expect(getResponseValue(ownersGetResponse, "content.1"), 'no second owner on a page of one').toBeNull();
    expect(getResponseValue(ownersGetResponse, "totalElements"), 'owners in the clinic').toBe(10);
    expect(getResponseValue(ownersGetResponse, "totalPages"), 'ten owners at one per page').toBe(10);
    expect(getResponseValue(ownersGetResponse, "content.0.id"), 'first owner id').toBe(1);
    expect(getResponseValue(ownersGetResponse, "content.0.lastName"), 'first owner last name').toBe("Franklin");

    const ownersGet1Response = await getOwnersPage(client, {"size": ["100"]}, 200);

    expect(ownersGet1Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(ownersGet1Response, "page"), 'response starts at page 0').toBe(0);
    expect(getResponseValue(ownersGet1Response, "size"), 'response echoes size at its declared maximum').toBe(100);
    expect(getResponseValue(ownersGet1Response, "totalElements"), 'owners in the clinic').toBe(10);
    expect(getResponseValue(ownersGet1Response, "totalPages"), 'every owner fits on one page of a hundred').toBe(1);
    expect(getResponseValue(ownersGet1Response, "content").length, 'the whole clinic on one page').toBe(10);
    expect(getResponseValue(ownersGet1Response, "content.10"), 'no eleventh owner').toBeNull();
    // A single page returns every owner it counted.
    expect(getResponseValue(ownersGet1Response, "content").length, 'a single page returns every counted owner')
        .toBe(getResponseValue(ownersGet1Response, "totalElements"));
    expect(getResponseValue(ownersGet1Response, "content.0.lastName"), 'first owner last name').toBe("Franklin");
    expect(getResponseValue(ownersGet1Response, "content.9.id"), 'Carlos Estaban id').toBe(10);
    expect(getResponseValue(ownersGet1Response, "content.9.lastName"), 'Carlos Estaban last name').toBe("Estaban");
    // Owners come back ordered by id.
    expect(getResponseValue(ownersGet1Response, "content.1.id"), 'owners are ordered by ascending id')
        .toBeGreaterThan(getResponseValue(ownersGet1Response, "content.0.id"));

    const ownersGet2Response = await getOwnersPage(client, {"size": [size_1]}, 400);

    // size below the declared minimum of 1 must be refused, with the ProblemDetail the OpenAPI declares for 400.
    expect(ownersGet2Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(ownersGet2Response, "status"), 'problem detail status for size=0').toBe(400);
    expect(getResponseValue(ownersGet2Response, "content"), 'a refused request returns no owner page').toBeNull();

    const ownersGet3Response = await getOwnersPage(client, {"size": [size]}, 400);

    // size above the declared maximum of 100 must be refused, with the ProblemDetail the OpenAPI declares for 400.
    expect(ownersGet3Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(ownersGet3Response, "status"), 'problem detail status for size=101').toBe(400);
    expect(getResponseValue(ownersGet3Response, "content"), 'a refused request returns no owner page').toBeNull();

    const ownersGet4Response = await getOwnersPage(client, {"page": [page]}, 400);

    // page below the declared minimum of 0 must be refused, with the ProblemDetail the OpenAPI declares for 400.
    expect(ownersGet4Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(ownersGet4Response, "status"), 'problem detail status for page=-1').toBe(400);
    expect(getResponseValue(ownersGet4Response, "content"), 'a refused request returns no owner page').toBeNull();
});
