// Generated by Skyramp v1.3.44 on 2026-09-08 19:21:47.287461404 +0000 UTC m=+1747.765462471
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_delete_preserves_other_owners_pets_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_owner-delete-preserves-other-owners-pets.json

// Import of required libraries
import { test, expect, SkyrampClient, getValue, getResponseValue, uniqueSuffix } from '@skyramp/skyramp';
import {
    createOwner,
    createPetForOwner,
    createPetType,
    deleteOwner,
    getOwner,
    getPetTypesList
} from './skyrampUtils';

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();

    const sharedTypeName = uniqueSuffix("skyramp-shared-type");

    const pettypesPostResponse = await createPetType(client, sharedTypeName);

    // Generated Assertions
    expect(pettypesPostResponse.statusCode, 'status code').toBe(201);
    expect(getResponseValue(pettypesPostResponse, "name"), 'name').toBe(sharedTypeName);
    expect(getResponseValue(pettypesPostResponse, "id"), 'id').toBeGreaterThan(0);

    const sharedTypeId = getResponseValue(pettypesPostResponse, "id");

    const ownersPostResponse = await createOwner(
        client,
        "Doomed",
        "Skyrampdoomed",
        "1 Cascade St.",
        "Madison",
        "6085550221"
    );

    // Generated Assertions
    expect(ownersPostResponse.statusCode, 'status code').toBe(201);
    expect(getResponseValue(ownersPostResponse, "firstName"), 'firstName').toBe("Doomed");
    expect(getResponseValue(ownersPostResponse, "lastName"), 'lastName').toBe("Skyrampdoomed");
    expect(getResponseValue(ownersPostResponse, "address"), 'address').toBe("1 Cascade St.");
    expect(getResponseValue(ownersPostResponse, "city"), 'city').toBe("Madison");
    expect(getResponseValue(ownersPostResponse, "telephone"), 'telephone').toBe("6085550221");
    expect(getResponseValue(ownersPostResponse, "id"), 'id').toBeGreaterThan(0);

    const ownerAId = getResponseValue(ownersPostResponse, "id");

    const ownersPost1Response = await createOwner(
        client,
        "Bystander",
        "Skyrampbystander",
        "2 Cascade St.",
        "Madison",
        "6085550222"
    );

    // Generated Assertions
    expect(ownersPost1Response.statusCode, 'status code').toBe(201);
    expect(getResponseValue(ownersPost1Response, "firstName"), 'firstName').toBe("Bystander");
    expect(getResponseValue(ownersPost1Response, "lastName"), 'lastName').toBe("Skyrampbystander");
    expect(getResponseValue(ownersPost1Response, "address"), 'address').toBe("2 Cascade St.");
    expect(getResponseValue(ownersPost1Response, "city"), 'city').toBe("Madison");
    expect(getResponseValue(ownersPost1Response, "telephone"), 'telephone').toBe("6085550222");
    expect(getResponseValue(ownersPost1Response, "id"), 'id').toBeGreaterThan(0);

    const ownerBId = getResponseValue(ownersPost1Response, "id");

    const petsPostResponse = await createPetForOwner(
        client,
        ownerAId,
        "PetOfA",
        "2020-05-01",
        sharedTypeId,
        sharedTypeName
    );

    // Generated Assertions
    expect(petsPostResponse.statusCode, 'status code').toBe(201);
    expect(getResponseValue(petsPostResponse, "name"), 'name').toBe("PetOfA");
    expect(getResponseValue(petsPostResponse, "birthDate"), 'birthDate').toBe("2020-05-01");
    expect(getResponseValue(petsPostResponse, "type.id"), 'type.id').toBe(sharedTypeId);
    expect(getResponseValue(petsPostResponse, "type.name"), 'type.name').toBe(sharedTypeName);
    expect(getResponseValue(petsPostResponse, "ownerId"), 'ownerId').toBe(ownerAId);
    expect(getResponseValue(petsPostResponse, "id"), 'id').toBeGreaterThan(0);

    const petsPost1Response = await createPetForOwner(
        client,
        ownerBId,
        "PetOfB",
        "2020-06-01",
        sharedTypeId,
        sharedTypeName
    );

    // Generated Assertions
    expect(petsPost1Response.statusCode, 'status code').toBe(201);
    expect(getResponseValue(petsPost1Response, "name"), 'name').toBe("PetOfB");
    expect(getResponseValue(petsPost1Response, "birthDate"), 'birthDate').toBe("2020-06-01");
    expect(getResponseValue(petsPost1Response, "type.id"), 'type.id').toBe(sharedTypeId);
    expect(getResponseValue(petsPost1Response, "type.name"), 'type.name').toBe(sharedTypeName);
    expect(getResponseValue(petsPost1Response, "ownerId"), 'ownerId').toBe(ownerBId);
    expect(getResponseValue(petsPost1Response, "id"), 'id').toBeGreaterThan(0);

    const petBId = getResponseValue(petsPost1Response, "id");

    const ownersOwnersDeleteResponse = await deleteOwner(client, ownerAId);

    // Generated Assertions
    expect(ownersOwnersDeleteResponse.statusCode, 'status code').toBe(204);

    try {
        const ownersOwnersGetResponse = await getOwner(client, ownerBId);

        // Generated Assertions
        // Deleting owner A must leave owner B and its pet untouched.
        expect(ownersOwnersGetResponse.statusCode, 'status code').toBe(200);
        expect(getResponseValue(ownersOwnersGetResponse, "id"), 'id').toBe(ownerBId);
        expect(getResponseValue(ownersOwnersGetResponse, "lastName"), 'lastName').toBe("Skyrampbystander");
        expect(getResponseValue(ownersOwnersGetResponse, "pets").length, 'pets still owned by the untouched owner').toBe(1);
        expect(getResponseValue(ownersOwnersGetResponse, "pets.0.id"), 'pets.0.id').toBe(petBId);
        expect(getResponseValue(ownersOwnersGetResponse, "pets.0.name"), 'pets.0.name').toBe("PetOfB");
        expect(getResponseValue(ownersOwnersGetResponse, "pets.0.type.id"), 'pets.0.type.id').toBe(sharedTypeId);
        expect(getResponseValue(ownersOwnersGetResponse, "pets.0.type.name"), 'pets.0.type.name').toBe(sharedTypeName);
        expect(getResponseValue(ownersOwnersGetResponse, "pets.1"), 'pets.1').toBeNull();

        const pettypesGetResponse = await getPetTypesList(client);

        // Generated Assertions
        // The shared pet type must survive the deletion of one of its pets' owners.
        expect(pettypesGetResponse.statusCode, 'status code').toBe(200);
        const petTypesInList = getResponseValue(pettypesGetResponse, "");
        const listedSharedType = petTypesInList.find((petType: { id: number }) => petType.id === sharedTypeId);
        expect(listedSharedType, 'the shared pet type is still listed').toBeDefined();
        expect(listedSharedType.name, 'name').toBe(sharedTypeName);
    } finally {
        // Cleanup runs even when an assertion above fails, so the test leaves no owner behind.
        const ownersOwnersDelete1Response = await deleteOwner(client, ownerBId);
        expect(ownersOwnersDelete1Response.statusCode, 'status code').toBe(204);
    }
});
