// Generated by Skyramp v1.3.44 on 2026-09-09 05:46:34.105706811 +0000 UTC m=+1306.638942169
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_reminders_upcoming_order_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_owner_reminders_upcoming_order.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import {
    createOwner,
    addPetToOwner,
    addVisitToOwner,
    getOwnerReminders,
    deleteVisit,
    deletePet,
    deleteOwner,
} from './skyrampUtils';

// The reminder window is relative to the day the test runs, so every visit date is
// derived from today rather than written as a literal. A literal date would make this
// test pass today and fail once it drifted out of the window.
function isoDateOffsetFromToday(days: number): string {
    const date = new Date();
    date.setUTCHours(0, 0, 0, 0);
    date.setUTCDate(date.getUTCDate() + days);
    return date.toISOString().slice(0, 10);
}

const TEN_DAYS_OUT = isoDateOffsetFromToday(10);
const TWO_DAYS_OUT = isoDateOffsetFromToday(2);
const YESTERDAY = isoDateOffsetFromToday(-1);

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Request Body
    const ownersPostRequestBody: string = `{
        "address": "12 Window St.",
        "city": "Madison",
        "firstName": "Reminders",
        "lastName": "Order",
        "telephone": "6085550101"
    }`;

    // Execute Request
    const ownersPostResponse = await createOwner(client, ownersPostRequestBody);
    expect(ownersPostResponse.statusCode, 'status code').toBe(201);

    expect(getResponseValue(ownersPostResponse, "firstName"), 'owner firstName').toBe('Reminders');
    expect(getResponseValue(ownersPostResponse, "lastName"), 'owner lastName').toBe('Order');
    expect(getResponseValue(ownersPostResponse, "address"), 'owner address').toBe('12 Window St.');
    expect(getResponseValue(ownersPostResponse, "city"), 'owner city').toBe('Madison');
    expect(getResponseValue(ownersPostResponse, "telephone"), 'owner telephone').toBe('6085550101');
    expect(getResponseValue(ownersPostResponse, "id"), 'owner id').toBeGreaterThan(0);

    // Request Body
    const petsPostRequestBody: string = `{
        "birthDate": "2020-04-01",
        "name": "Comet",
        "type": {
            "id": 1,
            "name": "cat"
        }
    }`;

    // Execute Request
    const petsPostResponse = await addPetToOwner(client, getResponseValue(ownersPostResponse, "id"), petsPostRequestBody);
    expect(petsPostResponse.statusCode, 'status code').toBe(201);

    expect(getResponseValue(petsPostResponse, "name"), 'pet name').toBe('Comet');
    expect(getResponseValue(petsPostResponse, "birthDate"), 'pet birthDate').toBe('2020-04-01');
    expect(getResponseValue(petsPostResponse, "type.name"), 'pet type name').toBe('cat');
    expect(getResponseValue(petsPostResponse, "ownerId"), 'pet ownerId').toBe(getResponseValue(ownersPostResponse, "id"));
    expect(getResponseValue(petsPostResponse, "id"), 'pet id').toBeGreaterThan(0);

    // Request Body
    const visitsPostRequestBody: string = `{
        "date": "${TEN_DAYS_OUT}",
        "description": "Later follow-up ten days out"
    }`;

    // Request Body
    const visitsPost1RequestBody: string = `{
        "date": "${TWO_DAYS_OUT}",
        "description": "Sooner follow-up two days out"
    }`;

    // Request Body
    const visitsPost2RequestBody: string = `{
        "date": "${YESTERDAY}",
        "description": "Past visit already happened"
    }`;

    const [visitsPostResponse, visitsPost1Response, visitsPost2Response] = await Promise.all([
        addVisitToOwner(client, getResponseValue(ownersPostResponse, "id"), getResponseValue(petsPostResponse, "id"), visitsPostRequestBody),
        addVisitToOwner(client, getResponseValue(ownersPostResponse, "id"), getResponseValue(petsPostResponse, "id"), visitsPost1RequestBody),
        addVisitToOwner(client, getResponseValue(ownersPostResponse, "id"), getResponseValue(petsPostResponse, "id"), visitsPost2RequestBody),
    ]);

    expect(visitsPostResponse.statusCode, 'status code').toBe(201);
    expect(visitsPost1Response.statusCode, 'status code').toBe(201);
    expect(visitsPost2Response.statusCode, 'status code').toBe(201);

    // Each visit POST echoes back the date and description it was sent, so assert the
    // exact values rather than merely that the fields are present.
    expect(getResponseValue(visitsPostResponse, "date"), 'ten-days-out visit date').toBe(TEN_DAYS_OUT);
    expect(getResponseValue(visitsPostResponse, "description"), 'ten-days-out visit description').toBe('Later follow-up ten days out');
    expect(getResponseValue(visitsPost1Response, "date"), 'two-days-out visit date').toBe(TWO_DAYS_OUT);
    expect(getResponseValue(visitsPost1Response, "description"), 'two-days-out visit description').toBe('Sooner follow-up two days out');
    expect(getResponseValue(visitsPost2Response, "date"), 'past visit date').toBe(YESTERDAY);
    expect(getResponseValue(visitsPost2Response, "description"), 'past visit description').toBe('Past visit already happened');

    // Execute Request
    const remindersGetResponse = await getOwnerReminders(client, getResponseValue(ownersPostResponse, "id"));
    expect(remindersGetResponse.statusCode, 'status code').toBe(200);

    const reminders = JSON.parse((remindersGetResponse as unknown as { responseBody: string }).responseBody) as Array<{ id: number; date: string; description: string; petId: number }>;

    // Only the two visits dated today or later are reminders: the visit dated yesterday
    // is history, so the list holds exactly two entries.
    expect(Array.isArray(reminders), 'reminders body is an array').toBe(true);
    expect(reminders.length, 'reminder count').toBe(2);

    // Soonest first: the two-days-out visit booked SECOND comes back FIRST, so the order
    // is the endpoint's sort and not the order the visits were created in.
    expect(reminders[0].date, 'first reminder date').toBe(TWO_DAYS_OUT);
    expect(reminders[0].description, 'first reminder description').toBe('Sooner follow-up two days out');
    expect(reminders[1].date, 'second reminder date').toBe(TEN_DAYS_OUT);
    expect(reminders[1].description, 'second reminder description').toBe('Later follow-up ten days out');

    // Nothing follows the second reminder: the index after the last item is absent.
    expect(reminders[2], 'no third reminder').toBeUndefined();

    // Compare the dates as dates, not as strings, so the ordering claim is about time.
    expect(
        Date.parse(reminders[0].date) < Date.parse(reminders[1].date),
        'reminders are ordered soonest first',
    ).toBe(true);

    // Each reminder carries the identity fields the Visit schema declares.
    expect(reminders[0].id, 'first reminder id').toBe(getResponseValue(visitsPost1Response, "id"));
    expect(reminders[1].id, 'second reminder id').toBe(getResponseValue(visitsPostResponse, "id"));
    expect(reminders[0].petId, 'first reminder petId').toBe(getResponseValue(petsPostResponse, "id"));

    // The past visit is absent. This negative check stands beside the positive length and
    // date assertions above on the same response.
    expect(
        reminders.map((reminder) => reminder.description),
        'reminder descriptions exclude the past visit',
    ).not.toContain('Past visit already happened');

    const [visitsVisitsDeleteResponse, visitsVisitsDelete1Response, visitsVisitsDelete2Response] = await Promise.all([
        deleteVisit(client, getResponseValue(visitsPostResponse, "id")),
        deleteVisit(client, getResponseValue(visitsPost1Response, "id")),
        deleteVisit(client, getResponseValue(visitsPost2Response, "id")),
    ]);

    expect(visitsVisitsDeleteResponse.statusCode, 'status code').toBe(204);
    expect(visitsVisitsDelete1Response.statusCode, 'status code').toBe(204);
    expect(visitsVisitsDelete2Response.statusCode, 'status code').toBe(204);

    // Execute Request
    const petsPetsDeleteResponse = await deletePet(client, getResponseValue(petsPostResponse, "id"));
    expect(petsPetsDeleteResponse.statusCode, 'status code').toBe(204);

    // Execute Request
    const ownersOwnersDeleteResponse = await deleteOwner(client, getResponseValue(ownersPostResponse, "id"));
    expect(ownersOwnersDeleteResponse.statusCode, 'status code').toBe(204);

    // The owner this test created is gone, so the test leaves no record behind.
    await getOwnerReminders(client, getResponseValue(ownersPostResponse, "id"), 404);
});
