// Generated by Skyramp v1.3.44 on 2026-09-08 19:18:46 +0000 UTC
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_update_telephone_constraint_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_owner-update-telephone-constraint-returns-validation-message.json

// Import of required libraries
import { test, expect, SkyrampClient, getValue, getResponseValue } from '@skyramp/skyramp';
import { createOwner, updateOwner, getOwner, deleteOwner } from './skyrampUtils';

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Request Body
    const ownersPostRequestBody: string = `{
        "address": "1 Probe Way",
        "city": "Testville",
        "firstName": "Probe",
        "lastName": "Tester",
        "telephone": "5551234567"
    }`;

    // Request Body
    const ownersOwnersPutRequestBody: string = `{
        "address": "1 Probe Way",
        "city": "Testville",
        "firstName": "Probe",
        "lastName": "Tester",
        "telephone": "12345"
    }`;

    const ownersPostResponse = await createOwner(client, ownersPostRequestBody, 201);
    expect(ownersPostResponse.statusCode, 'status code').toBe(201);
    expect(getResponseValue(ownersPostResponse, "firstName"), 'firstName').toBe("Probe");
    expect(getResponseValue(ownersPostResponse, "lastName"), 'lastName').toBe("Tester");
    expect(getResponseValue(ownersPostResponse, "address"), 'address').toBe("1 Probe Way");
    expect(getResponseValue(ownersPostResponse, "city"), 'city').toBe("Testville");
    expect(getResponseValue(ownersPostResponse, "telephone"), 'telephone').toBe("5551234567");
    expect(getResponseValue(ownersPostResponse, "pets").length, 'pets').toBe(0);
    expect(getResponseValue(ownersPostResponse, "pets.0"), 'pets.0').toBeNull();
    expect(getResponseValue(ownersPostResponse, "id"), 'id').toBeGreaterThan(0);

    const createdOwnerId = getResponseValue(ownersPostResponse, "id");

    // A five-digit telephone passes the OwnerFields schema (1-20 digits) but violates the
    // Owner entity's ^[0-9]{10}$ constraint. The PR requires the API's validation message to be
    // shown on a failed save, so the rejection has to arrive as a 400 carrying that message.
    const ownersOwnersPutResponse = await updateOwner(client, createdOwnerId, ownersOwnersPutRequestBody, 400);
    expect(ownersOwnersPutResponse.statusCode, 'status code').toBe(400);
    expect(getResponseValue(ownersOwnersPutResponse, "status"), 'status').toBe(400);
    expect(getResponseValue(ownersOwnersPutResponse, "detail"), 'detail').toBe("The request contains invalid or missing parameters");
    expect(getResponseValue(ownersOwnersPutResponse, "schemaValidationErrors"), 'schemaValidationErrors').toBeNull();
    expect(getResponseValue(ownersOwnersPutResponse, "validationErrors").length, 'validationErrors').toBeGreaterThan(0);
    expect(getResponseValue(ownersOwnersPutResponse, "validationErrors.0.field"), 'field').toBe("telephone");
    expect(getResponseValue(ownersOwnersPutResponse, "validationErrors.0.rejectedValue"), 'rejectedValue').toBe("12345");
    expect(getResponseValue(ownersOwnersPutResponse, "validationErrors.0.defaultMessage"), 'defaultMessage').toBe("Phone number must be exactly 10 digits");
    expect(getResponseValue(ownersOwnersPutResponse, "validationErrors.0.message"), 'message').toBe("Field 'telephone' Phone number must be exactly 10 digits (rejected value: 12345)");
    expect(getResponseValue(ownersOwnersPutResponse, "validationErrors.1"), 'validationErrors.1').toBeNull();

    const ownersOwnersGetResponse = await getOwner(client, createdOwnerId, 200);
    expect(ownersOwnersGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(ownersOwnersGetResponse, "id"), 'id').toBe(createdOwnerId);
    expect(getResponseValue(ownersOwnersGetResponse, "telephone"), 'telephone').toBe("5551234567");
    expect(getResponseValue(ownersOwnersGetResponse, "firstName"), 'firstName').toBe("Probe");
    expect(getResponseValue(ownersOwnersGetResponse, "lastName"), 'lastName').toBe("Tester");
    expect(getResponseValue(ownersOwnersGetResponse, "address"), 'address').toBe("1 Probe Way");
    expect(getResponseValue(ownersOwnersGetResponse, "city"), 'city').toBe("Testville");

    const ownersOwnersDeleteResponse = await deleteOwner(client, createdOwnerId, 204);
    expect(ownersOwnersDeleteResponse.statusCode, 'status code').toBe(204);
});
