// Generated by Skyramp v1.3.44 on 2026-09-08 19:10:55.066062431 +0000 UTC m=+1086.566452802
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_telephone_10_digit_contract_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_owners_telephone_10_digit_contract.json

// Import of required libraries
import { test, expect, SkyrampClient, getResponseValue } from '@skyramp/skyramp';
import { createOwner, getOwner, deleteOwner } from './skyrampUtils';

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Request Body
    const ownersPostRequestBody: string = `{
        "address": "1 Contract Way",
        "city": "Madison",
        "firstName": "Skyramp",
        "lastName": "Tendigit",
        "telephone": "6085551099"
    }`;

    const ownersPostResponse = await createOwner(client, ownersPostRequestBody, 201);

    expect(ownersPostResponse.statusCode, 'status code').toBe(201);

    expect(getResponseValue(ownersPostResponse, "id"), 'id').toBeGreaterThan(0);
    expect(getResponseValue(ownersPostResponse, "firstName"), 'firstName').toBe("Skyramp");
    expect(getResponseValue(ownersPostResponse, "lastName"), 'lastName').toBe("Tendigit");
    expect(getResponseValue(ownersPostResponse, "address"), 'address').toBe("1 Contract Way");
    expect(getResponseValue(ownersPostResponse, "city"), 'city').toBe("Madison");
    expect(getResponseValue(ownersPostResponse, "telephone"), 'telephone').toBe("6085551099");
    expect(getResponseValue(ownersPostResponse, "pets").length, 'pets length').toBe(0);
    expect(getResponseValue(ownersPostResponse, "pets.0"), 'pets.0').toBeNull();

    const ownersOwnersGetResponse = await getOwner(client, getResponseValue(ownersPostResponse, "id"), 200);

    expect(ownersOwnersGetResponse.statusCode, 'status code').toBe(200);

    expect(getResponseValue(ownersOwnersGetResponse, "id"), 'id').toBe(getResponseValue(ownersPostResponse, "id"));
    expect(getResponseValue(ownersOwnersGetResponse, "firstName"), 'firstName').toBe("Skyramp");
    expect(getResponseValue(ownersOwnersGetResponse, "lastName"), 'lastName').toBe("Tendigit");
    expect(getResponseValue(ownersOwnersGetResponse, "address"), 'address').toBe("1 Contract Way");
    expect(getResponseValue(ownersOwnersGetResponse, "city"), 'city').toBe("Madison");
    expect(getResponseValue(ownersOwnersGetResponse, "telephone"), 'telephone').toBe("6085551099");
    expect(getResponseValue(ownersOwnersGetResponse, "pets").length, 'pets length').toBe(0);

    // Request Body
    const ownersPost1RequestBody: string = `{
        "address": "1 Contract Way",
        "city": "Madison",
        "firstName": "Skyramp",
        "lastName": "Ninedigit",
        "telephone": "608555109"
    }`;

    // Request Body
    const ownersPost2RequestBody: string = `{
        "address": "1 Contract Way",
        "city": "Madison",
        "firstName": "Skyramp",
        "lastName": "Elevendigit",
        "telephone": "60855510999"
    }`;

    // Request Body
    const ownersPost3RequestBody: string = `{
        "address": "1 Contract Way",
        "city": "Madison",
        "firstName": "Skyramp",
        "lastName": "Dashed",
        "telephone": "608-555-1099"
    }`;

    // Request Body
    const ownersPost4RequestBody: string = `{
        "address": "1 Contract Way",
        "city": "Madison",
        "firstName": "Skyramp",
        "lastName": "Notel"
    }`;

    const rejectionOverride = {
        "address": getResponseValue(ownersOwnersGetResponse, "address"),
        "city": getResponseValue(ownersOwnersGetResponse, "city"),
        "firstName": getResponseValue(ownersOwnersGetResponse, "firstName")
    };

    const [ownersPost1Response, ownersPost2Response, ownersPost3Response, ownersPost4Response] = await Promise.all([
        createOwner(client, ownersPost1RequestBody, 400, rejectionOverride),
        createOwner(client, ownersPost2RequestBody, 400, rejectionOverride),
        createOwner(client, ownersPost3RequestBody, 400, rejectionOverride),
        createOwner(client, ownersPost4RequestBody, 400, rejectionOverride),
    ]);

    expect(ownersPost1Response.statusCode, 'status code').toBe(400);
    expect(ownersPost2Response.statusCode, 'status code').toBe(400);
    expect(ownersPost3Response.statusCode, 'status code').toBe(400);
    expect(ownersPost4Response.statusCode, 'status code').toBe(400);


    expect(getResponseValue(ownersPost1Response, "status"), 'status').toBe(400);
    expect(getResponseValue(ownersPost1Response, "title"), 'title').toBe("MethodArgumentNotValidException");
    expect(getResponseValue(ownersPost1Response, "detail"), 'detail').toBe("The request contains invalid or missing parameters");
    expect(getResponseValue(ownersPost1Response, "instance"), 'instance').toBe("/petclinic/api/owners");
    expect(getResponseValue(ownersPost1Response, "schemaValidationErrors").length, 'schemaValidationErrors length').toBe(2);
    expect(getResponseValue(ownersPost1Response, "schemaValidationErrors.0.field"), 'schemaValidationErrors.0.field').toBe("telephone");
    expect(getResponseValue(ownersPost1Response, "schemaValidationErrors.0.rejectedValue"), 'schemaValidationErrors.0.rejectedValue').toBe("608555109");
    expect(getResponseValue(ownersPost1Response, "schemaValidationErrors.1.field"), 'schemaValidationErrors.1.field').toBe("telephone");
    expect(getResponseValue(ownersPost1Response, "schemaValidationErrors.1.rejectedValue"), 'schemaValidationErrors.1.rejectedValue').toBe("608555109");
    expect(getResponseValue(ownersPost1Response, "schemaValidationErrors.2"), 'schemaValidationErrors.2').toBeNull();

    expect(getResponseValue(ownersPost2Response, "status"), 'status').toBe(400);
    expect(getResponseValue(ownersPost2Response, "title"), 'title').toBe("MethodArgumentNotValidException");
    expect(getResponseValue(ownersPost2Response, "detail"), 'detail').toBe("The request contains invalid or missing parameters");
    expect(getResponseValue(ownersPost2Response, "instance"), 'instance').toBe("/petclinic/api/owners");
    expect(getResponseValue(ownersPost2Response, "schemaValidationErrors").length, 'schemaValidationErrors length').toBe(2);
    expect(getResponseValue(ownersPost2Response, "schemaValidationErrors.0.field"), 'schemaValidationErrors.0.field').toBe("telephone");
    expect(getResponseValue(ownersPost2Response, "schemaValidationErrors.0.rejectedValue"), 'schemaValidationErrors.0.rejectedValue').toBe("60855510999");
    expect(getResponseValue(ownersPost2Response, "schemaValidationErrors.1.field"), 'schemaValidationErrors.1.field').toBe("telephone");
    expect(getResponseValue(ownersPost2Response, "schemaValidationErrors.1.rejectedValue"), 'schemaValidationErrors.1.rejectedValue').toBe("60855510999");
    expect(getResponseValue(ownersPost2Response, "schemaValidationErrors.2"), 'schemaValidationErrors.2').toBeNull();

    expect(getResponseValue(ownersPost3Response, "status"), 'status').toBe(400);
    expect(getResponseValue(ownersPost3Response, "title"), 'title').toBe("MethodArgumentNotValidException");
    expect(getResponseValue(ownersPost3Response, "detail"), 'detail').toBe("The request contains invalid or missing parameters");
    expect(getResponseValue(ownersPost3Response, "instance"), 'instance').toBe("/petclinic/api/owners");
    expect(getResponseValue(ownersPost3Response, "schemaValidationErrors").length, 'schemaValidationErrors length').toBe(2);
    expect(getResponseValue(ownersPost3Response, "schemaValidationErrors.0.field"), 'schemaValidationErrors.0.field').toBe("telephone");
    expect(getResponseValue(ownersPost3Response, "schemaValidationErrors.0.rejectedValue"), 'schemaValidationErrors.0.rejectedValue').toBe("608-555-1099");
    expect(getResponseValue(ownersPost3Response, "schemaValidationErrors.1.field"), 'schemaValidationErrors.1.field').toBe("telephone");
    expect(getResponseValue(ownersPost3Response, "schemaValidationErrors.1.rejectedValue"), 'schemaValidationErrors.1.rejectedValue').toBe("608-555-1099");
    expect(getResponseValue(ownersPost3Response, "schemaValidationErrors.2"), 'schemaValidationErrors.2').toBeNull();

    expect(getResponseValue(ownersPost4Response, "status"), 'status').toBe(400);
    expect(getResponseValue(ownersPost4Response, "title"), 'title').toBe("MethodArgumentNotValidException");
    expect(getResponseValue(ownersPost4Response, "detail"), 'detail').toBe("The request contains invalid or missing parameters");
    expect(getResponseValue(ownersPost4Response, "instance"), 'instance').toBe("/petclinic/api/owners");
    expect(getResponseValue(ownersPost4Response, "schemaValidationErrors").length, 'schemaValidationErrors length').toBe(1);
    expect(getResponseValue(ownersPost4Response, "schemaValidationErrors.0.field"), 'schemaValidationErrors.0.field').toBe("telephone");
    expect(getResponseValue(ownersPost4Response, "schemaValidationErrors.0.defaultMessage"), 'schemaValidationErrors.0.defaultMessage').toBe("must not be null");
    expect(getResponseValue(ownersPost4Response, "schemaValidationErrors.1"), 'schemaValidationErrors.1').toBeNull();

    const ownersOwnersDeleteResponse = await deleteOwner(client, getResponseValue(ownersPostResponse, "id"), 204);

    expect(ownersOwnersDeleteResponse.statusCode, 'status code').toBe(204);
});
