// Generated by Skyramp v1.3.44 on 2026-09-08 19:16:38.112927637 +0000 UTC m=+1438.458743470
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_post_phone_number_validation_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_owner_post_phone_number_validation.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import { createOwner, deleteOwner } from './skyrampUtils';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Request Body
    const ownersPostRequestBody: string = `{
        "address": "5 Contract Way",
        "city": "Madison",
        "firstName": "Phonethree",
        "lastName": "Validcase",
        "phoneNumber": "6085550555"
    }`;

    const ownersPostResponse = await createOwner(client, ownersPostRequestBody, 201);
    expect(ownersPostResponse.statusCode, 'status code').toBe(201);
    expect(getResponseValue(ownersPostResponse, "firstName"), 'firstName').toBe("Phonethree");
    expect(getResponseValue(ownersPostResponse, "lastName"), 'lastName').toBe("Validcase");
    expect(getResponseValue(ownersPostResponse, "address"), 'address').toBe("5 Contract Way");
    expect(getResponseValue(ownersPostResponse, "city"), 'city').toBe("Madison");
    expect(getResponseValue(ownersPostResponse, "phoneNumber"), 'phoneNumber').toBe("6085550555");
    expect(getResponseValue(ownersPostResponse, "telephone"), 'telephone mirrors phoneNumber').toBe("6085550555");
    expect(Number(getResponseValue(ownersPostResponse, "id")), 'id').toBeGreaterThan(0);
    const ownerId = getResponseValue(ownersPostResponse, "id");

    const ownersOwnersDeleteResponse = await deleteOwner(client, ownerId, 204);
    expect(ownersOwnersDeleteResponse.statusCode, 'status code').toBe(204);

    // Request Body
    const ownersPost1RequestBody: string = `{
        "address": "5 Contract Way",
        "city": "Madison",
        "firstName": "Phonethree",
        "lastName": "Baddigits",
        "phoneNumber": "abc123"
    }`;

    // Request Body
    const ownersPost2RequestBody: string = `{
        "address": "5 Contract Way",
        "city": "Madison",
        "firstName": "Phonethree",
        "lastName": "Longphone",
        "phoneNumber": "123456789012345678901"
    }`;

    // Request Body
    const ownersPost3RequestBody: string = `{
        "address": "5 Contract Way",
        "city": "Madison",
        "firstName": "Phonethree",
        "lastName": "Nophone"
    }`;

    const [ownersPost1Response, ownersPost2Response, ownersPost3Response] = await Promise.all([
        createOwner(client, ownersPost1RequestBody, 400),
        createOwner(client, ownersPost2RequestBody, 400),
        createOwner(client, ownersPost3RequestBody, 400),
    ]);

    expect(ownersPost1Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(ownersPost1Response, "status"), 'status').toBe(400);
    expect(getResponseValue(ownersPost1Response, "schemaValidationErrors.0.field"), 'rejected field').toBe("phoneNumber");
    expect(getResponseValue(ownersPost1Response, "schemaValidationErrors.0.rejectedValue"), 'rejected value').toBe("abc123");
    expect(getResponseValue(ownersPost1Response, "schemaValidationErrors.1"), 'only one validation error').toBeNull();

    expect(ownersPost2Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(ownersPost2Response, "status"), 'status').toBe(400);
    expect(getResponseValue(ownersPost2Response, "schemaValidationErrors.0.field"), 'rejected field').toBe("phoneNumber");
    expect(getResponseValue(ownersPost2Response, "schemaValidationErrors.0.rejectedValue"), 'rejected value').toBe("123456789012345678901");
    expect(getResponseValue(ownersPost2Response, "schemaValidationErrors.1"), 'only one validation error').toBeNull();

    expect(ownersPost3Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(ownersPost3Response, "status"), 'status').toBe(400);
});
