// Generated by Skyramp v1.3.44 on 2026-09-09 05:46:48.000000000 +0000 UTC
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_reminders_owner_id_rejections_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_owner_reminders_owner_id_rejections.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import { createOwner, getOwnerReminders, deleteOwner } from './skyrampUtils';

// An ownerId inside int32 range that no owner has. The seeded database and anything this
// suite creates use small sequential ids, so this one cannot collide with a real record.
// Kept as a string: the SDK renders a large number path parameter in scientific notation
// (2.147483e+09), which is not a valid id and makes the server answer 500 instead of 404.
const UNUSED_OWNER_ID = "2147483000";

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Request Body
    const ownersPostRequestBody: string = `{
        "address": "1 Quiet Ln.",
        "city": "Madison",
        "firstName": "Reminders",
        "lastName": "Empty",
        "telephone": "6085550100"
    }`;

    // Execute Request
    const ownersPostResponse = await createOwner(client, ownersPostRequestBody);
    expect(ownersPostResponse.statusCode, 'status code').toBe(201);

    expect(getResponseValue(ownersPostResponse, "firstName"), 'owner firstName').toBe('Reminders');
    expect(getResponseValue(ownersPostResponse, "lastName"), 'owner lastName').toBe('Empty');
    expect(getResponseValue(ownersPostResponse, "address"), 'owner address').toBe('1 Quiet Ln.');
    expect(getResponseValue(ownersPostResponse, "city"), 'owner city').toBe('Madison');
    expect(getResponseValue(ownersPostResponse, "telephone"), 'owner telephone').toBe('6085550100');
    expect(getResponseValue(ownersPostResponse, "id"), 'owner id').toBeGreaterThan(0);

    // The accepted request comes first: a real owner with no visits succeeds.
    const ownersRemindersGetResponse = await getOwnerReminders(client, getResponseValue(ownersPostResponse, "id"));
    expect(ownersRemindersGetResponse.statusCode, 'status code').toBe(200);

    const reminders = JSON.parse((ownersRemindersGetResponse as unknown as { responseBody: string }).responseBody) as unknown[];

    // An owner with nothing in the window is an ordinary outcome, not an error: the body
    // is an empty JSON array, asserted as an array of length 0 rather than as falsy.
    expect(Array.isArray(reminders), 'reminders body is an array').toBe(true);
    expect(reminders.length, 'reminder count for an owner with no visits').toBe(0);

    // The array is empty, so no element exists at index 0 to read a field from.
    expect(reminders[0], 'no first reminder').toBeUndefined();

    // An ownerId that no owner has is rejected with 404.
    const owners2147483000RemindersGetResponse = await getOwnerReminders(client, UNUSED_OWNER_ID, 404);
    expect(owners2147483000RemindersGetResponse.statusCode, 'status code').toBe(404);

    // A negative ownerId is rejected with 400 by the minimum: 0 the openapi spec declares
    // on the path parameter, which the generator emits as @Min(0).
    const remindersGetResponse = await getOwnerReminders(client, "-1", 400);
    expect(remindersGetResponse.statusCode, 'status code').toBe(400);

    // The 404 carries no response body - the controller answers an unknown owner with a
    // bare NOT_FOUND, the same way getOwner does - so the status code is the whole claim.
    expect((owners2147483000RemindersGetResponse as unknown as { responseBody: string }).responseBody, '404 body is empty').toBeFalsy();

    // The 400 does carry a ProblemDetail body: assert its fields with their exact values,
    // including which parameter was rejected and why.
    expect(getResponseValue(remindersGetResponse, "title"), '400 title').toBe('ConstraintViolationException');
    expect(getResponseValue(remindersGetResponse, "detail"), '400 detail').toBe('The request contains invalid or missing parameters');
    expect(getResponseValue(remindersGetResponse, "status"), '400 status field').toBe(400);
    expect(getResponseValue(remindersGetResponse, "instance"), '400 instance').toBe('/petclinic/api/owners/-1/reminders');
    expect(getResponseValue(remindersGetResponse, "schemaValidationErrors.0.field"), 'rejected field').toBe('ownerId');
    expect(getResponseValue(remindersGetResponse, "schemaValidationErrors.0.defaultMessage"), 'rejection reason').toBe('must be greater than or equal to 0');
    expect(getResponseValue(remindersGetResponse, "schemaValidationErrors.0.rejectedValue"), 'rejected value').toBe('-1');
    expect(getResponseValue(remindersGetResponse, "schemaValidationErrors.1"), 'only one validation error').toBeNull();
    expect(getResponseValue(remindersGetResponse, "timestamp"), '400 timestamp').toMatch(/^\d{4}-\d{2}-\d{2}T/);

    // Execute Request
    const ownersOwnersDeleteResponse = await deleteOwner(client, getResponseValue(ownersPostResponse, "id"));
    expect(ownersOwnersDeleteResponse.statusCode, 'status code').toBe(204);

    // The owner this test created is gone, so the test leaves no record behind.
    await getOwnerReminders(client, getResponseValue(ownersPostResponse, "id"), 404);
});
