// Generated by Skyramp v1.3.40 on 2026-09-02 07:58:23.259179968 +0000 UTC m=+1109.269986236
// Command: skyramp generate integration rest \
// 		--framework junit \
// 		--language java \
// 		--output OwnersUpdateEmailPersistsIntegrationTest.java \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_owners_update_email_persists.json

import java.util.*;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

import static dev.skyramp.api.Skyramp.*;
import dev.skyramp.api.SkyrampClient;
import dev.skyramp.exception.SkyrampException;
import dev.skyramp.model.*;

public final class OwnersUpdateEmailPersistsIntegrationTest {
    // URL for test requests
    String URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

    @Test
    public void testIntegration() throws SkyrampException {
        // Invocation of Skyramp Client
        var client = new SkyrampClient();
        // Request Body
        String ownersPostRequestBody = """
            {
                "address": "1 Update Way",
                "city": "Madison",
                "email": "before.update@example.com",
                "firstName": "Emailia",
                "lastName": "Updater",
                "telephone": "6085550111"
            }
        """;

        // Execute Request
        var ownersPostResponse = client.sendRequest(RequestV2.builder()
            .url(URL_localhost)
            .path("/petclinic/api/owners")
            .method("POST")
            .body(ownersPostRequestBody)
            .build());

        // Generated Assertions
        assertTrue(checkStatusCode(ownersPostResponse, "201"));
        assertEquals("Emailia", String.valueOf(getValue(ownersPostResponse, "firstName")));
        assertEquals("Updater", String.valueOf(getValue(ownersPostResponse, "lastName")));
        assertEquals("1 Update Way", String.valueOf(getValue(ownersPostResponse, "address")));
        assertEquals("Madison", String.valueOf(getValue(ownersPostResponse, "city")));
        assertEquals("6085550111", String.valueOf(getValue(ownersPostResponse, "telephone")));
        assertEquals("before.update@example.com", String.valueOf(getValue(ownersPostResponse, "email")));
        assertTrue(Double.parseDouble(String.valueOf(getValue(ownersPostResponse, "id"))) > 0);

        // Request Body
        String ownersOwnersPutRequestBody = """
            {
                "address": "1 Update Way",
                "city": "Madison",
                "email": "after.update@example.com",
                "firstName": "Emailia",
                "lastName": "Updater",
                "telephone": "6085550111"
            }
        """;

        // Execute Request
        var ownersOwnersPutResponse = client.sendRequest(RequestV2.builder()
            .url(URL_localhost)
            .path("/petclinic/api/owners/{owners}")
            .method("PUT")
            .body(ownersOwnersPutRequestBody)
            .pathParams(asMap("owners", getValue(ownersPostResponse, "id")))
            .build());

        // Generated Assertions
        assertTrue(checkStatusCode(ownersOwnersPutResponse, "204"));

        // Execute Request
        var ownersOwnersGetResponse = client.sendRequest(RequestV2.builder()
            .url(URL_localhost)
            .path("/petclinic/api/owners/{owners}")
            .method("GET")
            .pathParams(asMap("owners", getValue(ownersPostResponse, "id")))
            .build());

        // Generated Assertions
        assertTrue(checkStatusCode(ownersOwnersGetResponse, "200"));
        assertEquals(
            String.valueOf(getValue(ownersPostResponse, "id")),
            String.valueOf(getValue(ownersOwnersGetResponse, "id")));
        assertEquals("Emailia", String.valueOf(getValue(ownersOwnersGetResponse, "firstName")));
        assertEquals("Updater", String.valueOf(getValue(ownersOwnersGetResponse, "lastName")));
        assertEquals("1 Update Way", String.valueOf(getValue(ownersOwnersGetResponse, "address")));
        assertEquals("Madison", String.valueOf(getValue(ownersOwnersGetResponse, "city")));
        assertEquals("6085550111", String.valueOf(getValue(ownersOwnersGetResponse, "telephone")));
        // The PUT above sent email=after.update@example.com. OwnerRestControllerV1.updateOwner
        // copies address/city/firstName/lastName/telephone onto the existing owner but never
        // calls setEmail, so the updated address is silently discarded and this assertion fails.
        assertEquals("after.update@example.com", String.valueOf(getValue(ownersOwnersGetResponse, "email")));
    }
}
