// Generated by Skyramp v1.3.44 on 2026-09-08 19:18:51 +0000 UTC
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_update_rejection_validation_errors_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_owner-update-rejection-body-carries-validation-errors.json

// Import of required libraries
import { test, expect, SkyrampClient, getValue, getResponseValue } from '@skyramp/skyramp';
import { createOwner, updateOwner, getOwner, deleteOwner } from './skyrampUtils';

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Request Body
    const ownersPostRequestBody: string = `{
        "address": "1 Probe Way",
        "city": "Testville",
        "firstName": "Probe",
        "lastName": "Tester",
        "telephone": "5551234567"
    }`;

    // Request Body
    const ownersOwnersPutRequestBody: string = `{
        "address": "110 W. Liberty St.",
        "city": "Madison",
        "firstName": "George",
        "lastName": "Franklin",
        "telephone": "6085551023"
    }`;

    // Request Body
    const ownersOwnersPut1RequestBody: string = `{
        "address": "110 W. Liberty St.",
        "city": "Madison",
        "firstName": "",
        "lastName": "Franklin",
        "telephone": "6085551023"
    }`;

    // Request Body
    const ownersOwnersPut2RequestBody: string = `{
        "address": "110 W. Liberty St.",
        "city": "Madison",
        "firstName": "George123",
        "lastName": "Franklin",
        "telephone": "6085551023"
    }`;

    // Request Body
    const ownersOwnersPut3RequestBody: string = `{
        "address": "110 W. Liberty St.",
        "city": "Madison",
        "firstName": "George",
        "lastName": "",
        "telephone": "6085551023"
    }`;

    // Request Body
    const ownersOwnersPut4RequestBody: string = `{
        "city": "Madison",
        "firstName": "George",
        "lastName": "Franklin",
        "telephone": "6085551023"
    }`;

    // Request Body
    const ownersOwnersPut5RequestBody: string = `{
        "address": "110 W. Liberty St.",
        "city": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
        "firstName": "George",
        "lastName": "Franklin",
        "telephone": "6085551023"
    }`;

    // Request Body
    const ownersOwnersPut6RequestBody: string = `{
        "address": "110 W. Liberty St.",
        "city": "Madison",
        "firstName": "George",
        "lastName": "Franklin",
        "telephone": "abcdefghij"
    }`;

    // Request Body
    const ownersOwnersPut7RequestBody: string = `{
        "address": "110 W. Liberty St.",
        "city": "Madison",
        "firstName": "George",
        "lastName": "Franklin"
    }`;

    // Request Body
    const owners99999999PutRequestBody: string = `{
        "address": "110 W. Liberty St.",
        "city": "Madison",
        "firstName": "George",
        "lastName": "Franklin",
        "telephone": "6085551023"
    }`;

    const ownersPostResponse = await createOwner(client, ownersPostRequestBody, 201);
    expect(ownersPostResponse.statusCode, 'status code').toBe(201);
    expect(getResponseValue(ownersPostResponse, "firstName"), 'firstName').toBe("Probe");
    expect(getResponseValue(ownersPostResponse, "lastName"), 'lastName').toBe("Tester");
    expect(getResponseValue(ownersPostResponse, "address"), 'address').toBe("1 Probe Way");
    expect(getResponseValue(ownersPostResponse, "city"), 'city').toBe("Testville");
    expect(getResponseValue(ownersPostResponse, "telephone"), 'telephone').toBe("5551234567");
    expect(getResponseValue(ownersPostResponse, "pets").length, 'pets').toBe(0);
    expect(getResponseValue(ownersPostResponse, "pets.0"), 'pets.0').toBeNull();
    expect(getResponseValue(ownersPostResponse, "id"), 'id').toBeGreaterThan(0);

    const createdOwnerId = getResponseValue(ownersPostResponse, "id");

    const ownersOwnersPutResponse = await updateOwner(client, createdOwnerId, ownersOwnersPutRequestBody, 204);
    expect(ownersOwnersPutResponse.statusCode, 'status code').toBe(204);

    const ownersOwnersPut1Response = await updateOwner(client, createdOwnerId, ownersOwnersPut1RequestBody, 400);
    expect(ownersOwnersPut1Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(ownersOwnersPut1Response, "status"), 'status').toBe(400);
    expect(getResponseValue(ownersOwnersPut1Response, "title"), 'title').toBe("MethodArgumentNotValidException");
    expect(getResponseValue(ownersOwnersPut1Response, "detail"), 'detail').toBe("The request contains invalid or missing parameters");
    expect(getResponseValue(ownersOwnersPut1Response, "schemaValidationErrors"), 'schemaValidationErrors').toBeNull();
    expect(getResponseValue(ownersOwnersPut1Response, "validationErrors.0.field"), 'field').toBe("firstName");
    expect(getResponseValue(ownersOwnersPut1Response, "validationErrors.0.rejectedValue"), 'rejectedValue').toBe("");
    expect(getResponseValue(ownersOwnersPut1Response, "validationErrors.0.message"), 'message').toContain("Field 'firstName'");
    expect(getResponseValue(ownersOwnersPut1Response, "validationErrors.1.field"), 'field').toBe("firstName");
    expect(getResponseValue(ownersOwnersPut1Response, "validationErrors.2"), 'validationErrors.2').toBeNull();

    const ownersOwnersPut2Response = await updateOwner(client, createdOwnerId, ownersOwnersPut2RequestBody, 400);
    expect(ownersOwnersPut2Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(ownersOwnersPut2Response, "status"), 'status').toBe(400);
    expect(getResponseValue(ownersOwnersPut2Response, "title"), 'title').toBe("MethodArgumentNotValidException");
    expect(getResponseValue(ownersOwnersPut2Response, "detail"), 'detail').toBe("The request contains invalid or missing parameters");
    expect(getResponseValue(ownersOwnersPut2Response, "schemaValidationErrors"), 'schemaValidationErrors').toBeNull();
    expect(getResponseValue(ownersOwnersPut2Response, "validationErrors.0.field"), 'field').toBe("firstName");
    expect(getResponseValue(ownersOwnersPut2Response, "validationErrors.0.rejectedValue"), 'rejectedValue').toBe("George123");
    expect(getResponseValue(ownersOwnersPut2Response, "validationErrors.0.message"), 'message').toContain("must match");
    expect(getResponseValue(ownersOwnersPut2Response, "validationErrors.1"), 'validationErrors.1').toBeNull();

    const ownersOwnersPut3Response = await updateOwner(client, createdOwnerId, ownersOwnersPut3RequestBody, 400);
    expect(ownersOwnersPut3Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(ownersOwnersPut3Response, "status"), 'status').toBe(400);
    expect(getResponseValue(ownersOwnersPut3Response, "title"), 'title').toBe("MethodArgumentNotValidException");
    expect(getResponseValue(ownersOwnersPut3Response, "detail"), 'detail').toBe("The request contains invalid or missing parameters");
    expect(getResponseValue(ownersOwnersPut3Response, "schemaValidationErrors"), 'schemaValidationErrors').toBeNull();
    expect(getResponseValue(ownersOwnersPut3Response, "validationErrors.0.field"), 'field').toBe("lastName");
    expect(getResponseValue(ownersOwnersPut3Response, "validationErrors.0.rejectedValue"), 'rejectedValue').toBe("");
    expect(getResponseValue(ownersOwnersPut3Response, "validationErrors.0.message"), 'message').toContain("Field 'lastName'");
    expect(getResponseValue(ownersOwnersPut3Response, "validationErrors.1.field"), 'field').toBe("lastName");
    expect(getResponseValue(ownersOwnersPut3Response, "validationErrors.2"), 'validationErrors.2').toBeNull();

    const ownersOwnersPut4Response = await updateOwner(client, createdOwnerId, ownersOwnersPut4RequestBody, 400);
    expect(ownersOwnersPut4Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(ownersOwnersPut4Response, "status"), 'status').toBe(400);
    expect(getResponseValue(ownersOwnersPut4Response, "title"), 'title').toBe("MethodArgumentNotValidException");
    expect(getResponseValue(ownersOwnersPut4Response, "detail"), 'detail').toBe("The request contains invalid or missing parameters");
    expect(getResponseValue(ownersOwnersPut4Response, "schemaValidationErrors"), 'schemaValidationErrors').toBeNull();
    expect(getResponseValue(ownersOwnersPut4Response, "validationErrors.0.field"), 'field').toBe("address");
    expect(getResponseValue(ownersOwnersPut4Response, "validationErrors.0.rejectedValue"), 'rejectedValue').toBe("null");
    expect(getResponseValue(ownersOwnersPut4Response, "validationErrors.0.defaultMessage"), 'defaultMessage').toBe("must not be null");
    expect(getResponseValue(ownersOwnersPut4Response, "validationErrors.0.message"), 'message').toBe("Field 'address' must not be null (rejected value: null)");
    expect(getResponseValue(ownersOwnersPut4Response, "validationErrors.1"), 'validationErrors.1').toBeNull();

    const ownersOwnersPut5Response = await updateOwner(client, createdOwnerId, ownersOwnersPut5RequestBody, 400);
    expect(ownersOwnersPut5Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(ownersOwnersPut5Response, "status"), 'status').toBe(400);
    expect(getResponseValue(ownersOwnersPut5Response, "title"), 'title').toBe("MethodArgumentNotValidException");
    expect(getResponseValue(ownersOwnersPut5Response, "detail"), 'detail').toBe("The request contains invalid or missing parameters");
    expect(getResponseValue(ownersOwnersPut5Response, "schemaValidationErrors"), 'schemaValidationErrors').toBeNull();
    expect(getResponseValue(ownersOwnersPut5Response, "validationErrors.0.field"), 'field').toBe("city");
    expect(getResponseValue(ownersOwnersPut5Response, "validationErrors.0.rejectedValue"), 'rejectedValue').toBe("AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA");
    expect(getResponseValue(ownersOwnersPut5Response, "validationErrors.0.defaultMessage"), 'defaultMessage').toBe("size must be between 1 and 80");
    expect(getResponseValue(ownersOwnersPut5Response, "validationErrors.0.message"), 'message').toBe("Field 'city' size must be between 1 and 80 (rejected value: AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA)");
    expect(getResponseValue(ownersOwnersPut5Response, "validationErrors.1"), 'validationErrors.1').toBeNull();

    const ownersOwnersPut6Response = await updateOwner(client, createdOwnerId, ownersOwnersPut6RequestBody, 400);
    expect(ownersOwnersPut6Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(ownersOwnersPut6Response, "status"), 'status').toBe(400);
    expect(getResponseValue(ownersOwnersPut6Response, "title"), 'title').toBe("MethodArgumentNotValidException");
    expect(getResponseValue(ownersOwnersPut6Response, "detail"), 'detail').toBe("The request contains invalid or missing parameters");
    expect(getResponseValue(ownersOwnersPut6Response, "schemaValidationErrors"), 'schemaValidationErrors').toBeNull();
    expect(getResponseValue(ownersOwnersPut6Response, "validationErrors.0.field"), 'field').toBe("telephone");
    expect(getResponseValue(ownersOwnersPut6Response, "validationErrors.0.rejectedValue"), 'rejectedValue').toBe("abcdefghij");
    expect(getResponseValue(ownersOwnersPut6Response, "validationErrors.0.defaultMessage"), 'defaultMessage').toBe("must match \"^[0-9]*$\"");
    expect(getResponseValue(ownersOwnersPut6Response, "validationErrors.0.message"), 'message').toBe("Field 'telephone' must match \"^[0-9]*$\" (rejected value: abcdefghij)");
    expect(getResponseValue(ownersOwnersPut6Response, "validationErrors.1"), 'validationErrors.1').toBeNull();

    const ownersOwnersPut7Response = await updateOwner(client, createdOwnerId, ownersOwnersPut7RequestBody, 400);
    expect(ownersOwnersPut7Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(ownersOwnersPut7Response, "status"), 'status').toBe(400);
    expect(getResponseValue(ownersOwnersPut7Response, "title"), 'title').toBe("MethodArgumentNotValidException");
    expect(getResponseValue(ownersOwnersPut7Response, "detail"), 'detail').toBe("The request contains invalid or missing parameters");
    expect(getResponseValue(ownersOwnersPut7Response, "schemaValidationErrors"), 'schemaValidationErrors').toBeNull();
    expect(getResponseValue(ownersOwnersPut7Response, "validationErrors.0.field"), 'field').toBe("telephone");
    expect(getResponseValue(ownersOwnersPut7Response, "validationErrors.0.rejectedValue"), 'rejectedValue').toBe("null");
    expect(getResponseValue(ownersOwnersPut7Response, "validationErrors.0.defaultMessage"), 'defaultMessage').toBe("must not be null");
    expect(getResponseValue(ownersOwnersPut7Response, "validationErrors.0.message"), 'message').toBe("Field 'telephone' must not be null (rejected value: null)");
    expect(getResponseValue(ownersOwnersPut7Response, "validationErrors.1"), 'validationErrors.1').toBeNull();

    const owners99999999PutResponse = await updateOwner(client, "99999999", owners99999999PutRequestBody, 404);
    expect(owners99999999PutResponse.statusCode, 'status code').toBe(404);
    expect(getResponseValue(owners99999999PutResponse, "detail"), 'detail').toBeNull();
    expect(getResponseValue(owners99999999PutResponse, "validationErrors"), 'validationErrors').toBeNull();

    const ownersOwnersGetResponse = await getOwner(client, createdOwnerId, 200);
    expect(ownersOwnersGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(ownersOwnersGetResponse, "id"), 'id').toBe(createdOwnerId);
    expect(getResponseValue(ownersOwnersGetResponse, "firstName"), 'firstName').toBe("George");
    expect(getResponseValue(ownersOwnersGetResponse, "lastName"), 'lastName').toBe("Franklin");
    expect(getResponseValue(ownersOwnersGetResponse, "address"), 'address').toBe("110 W. Liberty St.");
    expect(getResponseValue(ownersOwnersGetResponse, "city"), 'city').toBe("Madison");
    expect(getResponseValue(ownersOwnersGetResponse, "telephone"), 'telephone').toBe("6085551023");

    const ownersOwnersDeleteResponse = await deleteOwner(client, createdOwnerId, 204);
    expect(ownersOwnersDeleteResponse.statusCode, 'status code').toBe(204);
});
