// Generated by Skyramp v1.3.40 on 2026-09-02 07:58:55.002681336 +0000 UTC m=+752.019272478
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_pet_count_list_vs_detail_consistency_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_owner_pet_count_list_vs_detail_consistency.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import { getOwnersList, getOwner } from './skyrampUtils';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();

    const ownersGetResponse = await getOwnersList(client);

    expect(getResponseValue(ownersGetResponse, "1.id"), 'id').toBeGreaterThan(0);
    expect(getResponseValue(ownersGetResponse, "1.firstName"), 'firstName').not.toBeNull();
    expect(getResponseValue(ownersGetResponse, "1.lastName"), 'lastName').not.toBeNull();

    const ownersOwnersGetResponse = await getOwner(client, getResponseValue(ownersGetResponse, "1.id"));

    expect(getResponseValue(ownersOwnersGetResponse, "id"), 'id').toBe(getResponseValue(ownersGetResponse, "1.id"));
    expect(getResponseValue(ownersOwnersGetResponse, "firstName"), 'firstName').toBe(getResponseValue(ownersGetResponse, "1.firstName"));
    expect(getResponseValue(ownersOwnersGetResponse, "lastName"), 'lastName').toBe(getResponseValue(ownersGetResponse, "1.lastName"));
    expect(getResponseValue(ownersOwnersGetResponse, "pets.0.name"), 'pets.0.name').not.toBeNull();

    expect(getResponseValue(ownersGetResponse, "1.pets"), 'pets').toHaveLength((getResponseValue(ownersOwnersGetResponse, "pets") || []).length);
    expect(getResponseValue(ownersGetResponse, "1.pets.0.name"), 'pets.0.name').toBe(getResponseValue(ownersOwnersGetResponse, "pets.0.name"));
});
