// Generated by Skyramp v1.3.44 on 2026-09-09 05:46:41.000000000 +0000 UTC
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_reminders_fourteen_day_window_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_owner_reminders_fourteen_day_window.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import {
    createOwner,
    addPetToOwner,
    addVisitToOwner,
    getOwnerReminders,
    deleteVisit,
    deletePet,
    deleteOwner,
} from './skyrampUtils';

// docs/specs/visit-reminders.md caps the reminder window at 14 days and states that a
// visit exactly 14 days away is included while one 15 days away is not. Both dates are
// derived from the day the test runs so the boundary is always exactly on the edge.
function isoDateOffsetFromToday(days: number): string {
    const date = new Date();
    date.setUTCHours(0, 0, 0, 0);
    date.setUTCDate(date.getUTCDate() + days);
    return date.toISOString().slice(0, 10);
}

const FOURTEEN_DAYS_OUT = isoDateOffsetFromToday(14);
const FIFTEEN_DAYS_OUT = isoDateOffsetFromToday(15);

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Request Body
    const ownersPostRequestBody: string = `{
        "address": "14 Fortnight Rd.",
        "city": "Madison",
        "firstName": "Reminders",
        "lastName": "Window",
        "telephone": "6085550114"
    }`;

    // Execute Request
    const ownersPostResponse = await createOwner(client, ownersPostRequestBody);
    expect(ownersPostResponse.statusCode, 'status code').toBe(201);

    expect(getResponseValue(ownersPostResponse, "firstName"), 'owner firstName').toBe('Reminders');
    expect(getResponseValue(ownersPostResponse, "lastName"), 'owner lastName').toBe('Window');
    expect(getResponseValue(ownersPostResponse, "address"), 'owner address').toBe('14 Fortnight Rd.');
    expect(getResponseValue(ownersPostResponse, "city"), 'owner city').toBe('Madison');
    expect(getResponseValue(ownersPostResponse, "telephone"), 'owner telephone').toBe('6085550114');
    expect(getResponseValue(ownersPostResponse, "id"), 'owner id').toBeGreaterThan(0);

    // Request Body
    const petsPostRequestBody: string = `{
        "birthDate": "2019-06-15",
        "name": "Fortnight",
        "type": {
            "id": 1,
            "name": "cat"
        }
    }`;

    // Execute Request
    const petsPostResponse = await addPetToOwner(client, getResponseValue(ownersPostResponse, "id"), petsPostRequestBody);
    expect(petsPostResponse.statusCode, 'status code').toBe(201);

    expect(getResponseValue(petsPostResponse, "name"), 'pet name').toBe('Fortnight');
    expect(getResponseValue(petsPostResponse, "birthDate"), 'pet birthDate').toBe('2019-06-15');
    expect(getResponseValue(petsPostResponse, "type.name"), 'pet type name').toBe('cat');
    expect(getResponseValue(petsPostResponse, "ownerId"), 'pet ownerId').toBe(getResponseValue(ownersPostResponse, "id"));
    expect(getResponseValue(petsPostResponse, "id"), 'pet id').toBeGreaterThan(0);

    // Request Body
    const visitsPostRequestBody: string = `{
        "date": "${FOURTEEN_DAYS_OUT}",
        "description": "Boundary visit fourteen days out"
    }`;

    // Request Body
    const visitsPost1RequestBody: string = `{
        "date": "${FIFTEEN_DAYS_OUT}",
        "description": "Outside window fifteen days out"
    }`;

    const [visitsPostResponse, visitsPost1Response] = await Promise.all([
        addVisitToOwner(client, getResponseValue(ownersPostResponse, "id"), getResponseValue(petsPostResponse, "id"), visitsPostRequestBody),
        addVisitToOwner(client, getResponseValue(ownersPostResponse, "id"), getResponseValue(petsPostResponse, "id"), visitsPost1RequestBody),
    ]);

expect(visitsPostResponse.statusCode, 'status code').toBe(201);
    expect(visitsPost1Response.statusCode, 'status code').toBe(201);

        // Both visits were accepted and stored on the dates sent, so the reminders result
    // below is about the window and not about a rejected booking.
    expect(getResponseValue(visitsPostResponse, "date"), 'fourteen-days-out visit date').toBe(FOURTEEN_DAYS_OUT);
    expect(getResponseValue(visitsPost1Response, "date"), 'fifteen-days-out visit date').toBe(FIFTEEN_DAYS_OUT);
    expect(getResponseValue(visitsPostResponse, "description"), 'fourteen-days-out visit description').toBe('Boundary visit fourteen days out');
    expect(getResponseValue(visitsPost1Response, "description"), 'fifteen-days-out visit description').toBe('Outside window fifteen days out');
    expect(getResponseValue(visitsPostResponse, "id"), 'fourteen-days-out visit id').toBeGreaterThan(0);
    expect(getResponseValue(visitsPost1Response, "id"), 'fifteen-days-out visit id').toBeGreaterThan(0);

    // Execute Request
    const remindersGetResponse = await getOwnerReminders(client, getResponseValue(ownersPostResponse, "id"));
    expect(remindersGetResponse.statusCode, 'status code').toBe(200);

    const reminders = JSON.parse((remindersGetResponse as unknown as { responseBody: string }).responseBody) as Array<{ id: number; date: string; description: string; petId: number }>;

    // The window assertions below are the point of this test and are expected to fail
    // until the 14-day cap is implemented. They run inside a try/finally so the records
    // this test created are deleted either way, leaving nothing behind on a red run.
    try {
        // The spec includes a visit exactly 14 days away and excludes one 15 days away, so
        // exactly one of the two booked visits is a reminder.
        expect(Array.isArray(reminders), 'reminders body is an array').toBe(true);
        expect(reminders.length, 'reminder count inside the fourteen-day window').toBe(1);
        expect(reminders[0].date, 'the one reminder is the fourteen-days-out visit').toBe(FOURTEEN_DAYS_OUT);
        expect(reminders[0].description, 'the one reminder description').toBe('Boundary visit fourteen days out');
        expect(reminders[0].id, 'the one reminder id').toBe(getResponseValue(visitsPostResponse, "id"));

        // Nothing follows the single reminder: the index after the last item is absent.
        expect(reminders[1], 'no second reminder').toBeUndefined();

        // The visit 15 days away is past the window. This negative check stands beside the
        // positive length, date and description assertions above on the same response.
        expect(
            reminders.map((reminder) => reminder.description),
            'reminder descriptions exclude the visit outside the window',
        ).not.toContain('Outside window fifteen days out');
    } finally {
        const [visitsVisitsDeleteResponse, visitsVisitsDelete1Response] = await Promise.all([
            deleteVisit(client, getResponseValue(visitsPostResponse, "id")),
            deleteVisit(client, getResponseValue(visitsPost1Response, "id")),
        ]);

        expect(visitsVisitsDeleteResponse.statusCode, 'status code').toBe(204);
        expect(visitsVisitsDelete1Response.statusCode, 'status code').toBe(204);

        // Execute Request
        const petsPetsDeleteResponse = await deletePet(client, getResponseValue(petsPostResponse, "id"));
        expect(petsPetsDeleteResponse.statusCode, 'status code').toBe(204);

        // Execute Request
        const ownersOwnersDeleteResponse = await deleteOwner(client, getResponseValue(ownersPostResponse, "id"));
        expect(ownersOwnersDeleteResponse.statusCode, 'status code').toBe(204);

        // The owner this test created is gone, so the test leaves no record behind.
        await getOwnerReminders(client, getResponseValue(ownersPostResponse, "id"), 404);
    }
});
