// Generated by Skyramp v1.3.40 on 2026-09-02 07:55:09.456977663 +0000 UTC m=+605.079213882
// Command: skyramp generate integration rest \
// 		--chaining-key id \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_city_120_chars_round_trip_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_owner-city-120-chars-round-trip.json

// Import of required libraries
import { test, expect, SkyrampClient, getResponseValue, getValue } from '@skyramp/skyramp';
import { createOwner, getOwner } from './skyrampUtils';

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();

    const ownersPostResponse = await createOwner(client);
    expect(getValue(ownersPostResponse, "city"), 'created city').toBe("Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogochxxx");
    expect((getValue(ownersPostResponse, "city") as string).length, 'created city length').toBe(120);
    expect(getValue(ownersPostResponse, "firstName"), 'created firstName').toBe("Grace");
    expect(getValue(ownersPostResponse, "lastName"), 'created lastName').toBe("Hopper");
    expect(getValue(ownersPostResponse, "address"), 'created address').toBe("34 Compiler Court");
    expect(getValue(ownersPostResponse, "telephone"), 'created telephone').toBe("6085559876");
    expect(getValue(ownersPostResponse, "id"), 'created id').toBeGreaterThan(0);

    const ownersOwnersGetResponse = await getOwner(client, getResponseValue(ownersPostResponse, "id"));
    expect(getValue(ownersOwnersGetResponse, "id"), 'persisted id').toBe(getValue(ownersPostResponse, "id"));
    expect(getValue(ownersOwnersGetResponse, "city"), 'persisted city').toBe("Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch Llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogochxxx");
    expect((getValue(ownersOwnersGetResponse, "city") as string).length, 'persisted city length').toBe(120);
    expect(getValue(ownersOwnersGetResponse, "city"), 'persisted city matches created city').toBe(getValue(ownersPostResponse, "city"));
    expect(getValue(ownersOwnersGetResponse, "firstName"), 'persisted firstName').toBe("Grace");
    expect(getValue(ownersOwnersGetResponse, "lastName"), 'persisted lastName').toBe("Hopper");
    expect(getValue(ownersOwnersGetResponse, "address"), 'persisted address').toBe("34 Compiler Court");
    expect(getValue(ownersOwnersGetResponse, "telephone"), 'persisted telephone').toBe("6085559876");
});
