// Generated by Skyramp v1.3.44 on 2026-09-08 19:21:41.493183189 +0000 UTC m=+1741.971184255
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owners_collection_reports_pet_count_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_owners-collection-reports-pet-count.json

// Import of required libraries
import { test, expect, SkyrampClient, getValue, getResponseValue, uniqueSuffix, checkSchema } from '@skyramp/skyramp';
import {
    createOwner,
    createPetForOwner,
    createPetType,
    deleteOwner,
    getOwner,
    getOwnersList
} from './skyrampUtils';

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Declaration of variables
    const lastName = "Zzzznosuchowner";
    const petTypeName = uniqueSuffix("skyramp-count-type");

    const pettypesPostResponse = await createPetType(client, petTypeName);

    // Generated Assertions
    expect(pettypesPostResponse.statusCode, 'status code').toBe(201);
    expect(getResponseValue(pettypesPostResponse, "name"), 'name').toBe(petTypeName);
    expect(getResponseValue(pettypesPostResponse, "id"), 'id').toBeGreaterThan(0);

    const ownersPostResponse = await createOwner(
        client,
        "Petcount",
        "Skyrampcount",
        "1 Collection Way",
        "Madison",
        "6085550111"
    );

    // Generated Assertions
    expect(ownersPostResponse.statusCode, 'status code').toBe(201);
    expect(getResponseValue(ownersPostResponse, "firstName"), 'firstName').toBe("Petcount");
    expect(getResponseValue(ownersPostResponse, "lastName"), 'lastName').toBe("Skyrampcount");
    expect(getResponseValue(ownersPostResponse, "address"), 'address').toBe("1 Collection Way");
    expect(getResponseValue(ownersPostResponse, "city"), 'city').toBe("Madison");
    expect(getResponseValue(ownersPostResponse, "telephone"), 'telephone').toBe("6085550111");
    expect(getResponseValue(ownersPostResponse, "id"), 'id').toBeGreaterThan(0);
    expect(getResponseValue(ownersPostResponse, "pets").length, 'pets of a brand new owner').toBe(0);
    expect(getResponseValue(ownersPostResponse, "pets.0"), 'pets.0').toBeNull();

    const createdOwnerId = getResponseValue(ownersPostResponse, "id");
    const createdPetTypeId = getResponseValue(pettypesPostResponse, "id");

    const petsPostResponse = await createPetForOwner(
        client,
        createdOwnerId,
        "Countable",
        "2020-05-01",
        createdPetTypeId,
        petTypeName
    );

    // Generated Assertions
    expect(petsPostResponse.statusCode, 'status code').toBe(201);
    expect(getResponseValue(petsPostResponse, "name"), 'name').toBe("Countable");
    expect(getResponseValue(petsPostResponse, "birthDate"), 'birthDate').toBe("2020-05-01");
    expect(getResponseValue(petsPostResponse, "type.id"), 'type.id').toBe(createdPetTypeId);
    expect(getResponseValue(petsPostResponse, "type.name"), 'type.name').toBe(petTypeName);
    expect(getResponseValue(petsPostResponse, "ownerId"), 'ownerId').toBe(createdOwnerId);
    expect(getResponseValue(petsPostResponse, "id"), 'id').toBeGreaterThan(0);
    expect(getResponseValue(petsPostResponse, "visits").length, 'visits of a brand new pet').toBe(0);
    expect(getResponseValue(petsPostResponse, "visits.0"), 'visits.0').toBeNull();

    const createdPetId = getResponseValue(petsPostResponse, "id");

    try {
        const ownersOwnersGetResponse = await getOwner(client, createdOwnerId);

        // Generated Assertions
        expect(ownersOwnersGetResponse.statusCode, 'status code').toBe(200);
        // Control: read individually, the owner carries the one pet just added to it.
        expect(getResponseValue(ownersOwnersGetResponse, "id"), 'id').toBe(createdOwnerId);
        expect(getResponseValue(ownersOwnersGetResponse, "lastName"), 'lastName').toBe("Skyrampcount");
        expect(getResponseValue(ownersOwnersGetResponse, "pets").length, 'pets of the owner read individually').toBe(1);
        expect(getResponseValue(ownersOwnersGetResponse, "pets.0.id"), 'pets.0.id').toBe(createdPetId);
        expect(getResponseValue(ownersOwnersGetResponse, "pets.0.name"), 'pets.0.name').toBe("Countable");
        expect(getResponseValue(ownersOwnersGetResponse, "pets.0.type.name"), 'pets.0.type.name').toBe(petTypeName);
        expect(getResponseValue(ownersOwnersGetResponse, "pets.1"), 'pets.1').toBeNull();

        const [ownersGetResponse, ownersGet1Response, ownersGet2Response] = await Promise.all([
            getOwnersList(client),
            getOwnersList(client, {"lastName": [getResponseValue(ownersOwnersGetResponse, "lastName")]}),
            getOwnersList(client, {"lastName": [lastName]}, 404),
        ]);

        // Generated Assertions
        // The owners collection must report the created owner with the same one pet the
        // individual owner response returned above, so the directory can show a pet count.
        expect(ownersGetResponse.statusCode, 'status code').toBe(200);
        expect(ownersGet1Response.statusCode, 'status code').toBe(200);
        expect(ownersGet2Response.statusCode, 'status code').toBe(404);
        const ownersInList = getResponseValue(ownersGetResponse, "");
        const listedOwner = ownersInList.find((owner: { id: number }) => owner.id === createdOwnerId);
        expect(listedOwner, 'created owner is present in GET /owners').toBeDefined();
        expect(listedOwner.lastName, 'lastName').toBe("Skyrampcount");
        expect(listedOwner.pets.length, 'pets of the created owner in GET /owners').toBe(1);
        expect(listedOwner.pets[0].id, 'pets.0.id').toBe(createdPetId);
        expect(listedOwner.pets[0].name, 'pets.0.name').toBe("Countable");
        expect(listedOwner.pets[0].type.name, 'pets.0.type.name').toBe(petTypeName);
        expect(listedOwner.pets[1], 'pets.1').toBeUndefined();

        // The ?lastName= search the owners directory uses must reflect the filter and
        // carry the same pets.
        const searchedOwners = getResponseValue(ownersGet1Response, "");
        expect(searchedOwners.length, 'owners matching lastName=Skyrampcount').toBeGreaterThan(0);
        expect(
            searchedOwners.every((owner: { lastName: string }) => owner.lastName === "Skyrampcount"),
            'every owner in the filtered response has the requested lastName'
        ).toBe(true);
        const searchedOwner = searchedOwners.find((owner: { id: number }) => owner.id === createdOwnerId);
        expect(searchedOwner, 'created owner is present in GET /owners?lastName=Skyrampcount').toBeDefined();
        expect(searchedOwner.pets.length, 'pets of the created owner in the filtered response').toBe(1);
        expect(searchedOwner.pets[0].name, 'pets.0.name').toBe("Countable");

        // A lastName matching no owner is rejected and returns no owner data.
        expect(getResponseValue(ownersGet2Response, "0"), 'no owner is returned for an unmatched lastName').toBeNull();

        const owners99999999GetResponse = await getOwner(client, "99999999", 404);

        // Generated Assertions
        expect(owners99999999GetResponse.statusCode, 'status code').toBe(404);
        expect(getResponseValue(owners99999999GetResponse, "id"), 'no owner is returned for an unknown ownerId').toBeNull();
    } finally {
        // Cleanup runs even when an assertion above fails, so the test leaves no owner behind.
        const ownersOwnersDeleteResponse = await deleteOwner(client, createdOwnerId);
        expect(ownersOwnersDeleteResponse.statusCode, 'status code').toBe(204);
    }
});
