// Generated by Skyramp v1.3.40 on 2026-09-02 08:11:04.230654639 +0000 UTC m=+1486.740247561
// Command: skyramp generate integration rest \
// 		--chaining-key id \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_update_invalid_returns_validation_errors_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_owner_update_invalid_returns_validation_errors.json

// Import of required libraries
import { test, expect, SkyrampClient, getValue, getResponseValue, checkSchema } from '@skyramp/skyramp';
import { createOwner, updateOwner } from './skyrampUtils';

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();

    const ownersPostResponse = await createOwner(client);
    expect(getValue(ownersPostResponse, "firstName"), 'firstName').toBe("Testowner");
    expect(getValue(ownersPostResponse, "lastName"), 'lastName').toBe("Casey");
    expect(getValue(ownersPostResponse, "address"), 'address').toBe("1 Main St");
    expect(getValue(ownersPostResponse, "city"), 'city').toBe("Madison");
    expect(getValue(ownersPostResponse, "telephone"), 'telephone').toBe("6085551234");
    expect(getValue(ownersPostResponse, "id"), 'id').toBeGreaterThan(0);
    expect(checkSchema(ownersPostResponse, '{"pets": []}'), 'pets present and empty').toBe(true);
    expect(getValue(ownersPostResponse, "pets.0.id"), 'pets first item').toBeNull();

    const ownersOwnersPutResponse = await updateOwner(client, getResponseValue(ownersPostResponse, "id"));
    expect(getValue(ownersOwnersPutResponse, "status"), 'status').toBe(400);
    expect(getValue(ownersOwnersPutResponse, "title"), 'title').toBe("MethodArgumentNotValidException");
    expect(getValue(ownersOwnersPutResponse, "detail"), 'detail').toBe("The request contains invalid or missing parameters");
    expect(getValue(ownersOwnersPutResponse, "instance"), 'instance').toBe(`/petclinic/api/owners/${getResponseValue(ownersPostResponse, "id")}`);
    expect(getValue(ownersOwnersPutResponse, "timestamp"), 'timestamp').toMatch(/^\d{4}-\d{2}-\d{2}T/);
    expect(getValue(ownersOwnersPutResponse, "validationErrors.0.field"), 'validationErrors[0].field').toBe("firstName");
    expect(getValue(ownersOwnersPutResponse, "validationErrors.0.rejectedValue"), 'validationErrors[0].rejectedValue').toBe("A1");
    expect(getValue(ownersOwnersPutResponse, "validationErrors.0.message"), 'validationErrors[0].message').toBe("Field 'firstName' must match \"^[\\p{L}]+([ '-][\\p{L}]+){0,2}$\" (rejected value: A1)");
    expect(getValue(ownersOwnersPutResponse, "validationErrors.1.message"), 'validationErrors second item').toBeNull();
});
