// Generated by Skyramp v1.3.44 on 2026-09-08 19:16:27 +0000 UTC
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_email_update_roundtrip_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_owner_email_update_roundtrip.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import { createOwner, updateOwner, getOwner, deleteOwner } from './skyrampUtils';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");
test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Request Body
    const ownersPostRequestBody: string = `{
        "address": "2 Test Way",
        "city": "Monona",
        "email": "noah.before@example.com",
        "firstName": "Noah",
        "lastName": "Update",
        "telephone": "6085551005"
    }`;

    const ownersPostResponse = await createOwner(client, URL_localhost, ownersPostRequestBody);

    expect(ownersPostResponse.statusCode, 'status code').toBe(201);

    expect(getResponseValue(ownersPostResponse, "email"), 'email').toBe("noah.before@example.com");
    expect(getResponseValue(ownersPostResponse, "id"), 'id').toBeGreaterThan(0);

    // Request Body
    const ownersOwnersPutRequestBody: string = `{
        "address": "2 Test Way",
        "city": "Monona",
        "email": "not-an-email",
        "firstName": "Noah",
        "lastName": "Update",
        "telephone": "6085551005"
    }`;

    const ownersOwnersPutResponse = await updateOwner(client, URL_localhost, getResponseValue(ownersPostResponse, "id"), ownersOwnersPutRequestBody);

    expect(ownersOwnersPutResponse.statusCode, 'status code').toBe(400);

    // Request Body
    const owners999999PutRequestBody: string = `{
        "address": "2 Test Way",
        "city": "Monona",
        "email": "noah.after@example.com",
        "firstName": "Noah",
        "lastName": "Update",
        "telephone": "6085551005"
    }`;

    const owners999999PutResponse = await updateOwner(client, URL_localhost, 999999, owners999999PutRequestBody);

    expect(owners999999PutResponse.statusCode, 'status code').toBe(404);

    // Request Body
    const ownersOwnersPut1RequestBody: string = `{
        "address": "2 Test Way",
        "city": "Monona",
        "email": "noah.after@example.com",
        "firstName": "Noah",
        "lastName": "Update",
        "telephone": "6085551005"
    }`;

    const ownersOwnersPut1Response = await updateOwner(client, URL_localhost, getResponseValue(ownersPostResponse, "id"), ownersOwnersPut1RequestBody);

    expect(ownersOwnersPut1Response.statusCode, 'status code').toBe(204);

    const ownersOwnersGetResponse = await getOwner(client, URL_localhost, getResponseValue(ownersPostResponse, "id"));

    expect(ownersOwnersGetResponse.statusCode, 'status code').toBe(200);

    // The address step 4 sent and received a 204 for must be the address that reads back.
    expect(getResponseValue(ownersOwnersGetResponse, "email"), 'email saved by PUT /owners/{ownerId}').toBe("noah.after@example.com");
    expect(getResponseValue(ownersOwnersGetResponse, "id"), 'id').toBe(getResponseValue(ownersPostResponse, "id"));
    expect(getResponseValue(ownersOwnersGetResponse, "firstName"), 'firstName').toBe("Noah");
    expect(getResponseValue(ownersOwnersGetResponse, "lastName"), 'lastName').toBe("Update");
    expect(getResponseValue(ownersOwnersGetResponse, "telephone"), 'telephone').toBe("6085551005");

    const ownersOwnersDeleteResponse = await deleteOwner(client, URL_localhost, getResponseValue(ownersPostResponse, "id"));

    expect(ownersOwnersDeleteResponse.statusCode, 'status code').toBe(204);
});
