// Generated by Skyramp v1.3.40 on 2026-09-02 08:06:33.941179274 +0000 UTC m=+1270.407652351
// Command: skyramp generate integration rest \
// 		--chaining-key id \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_pets_bulk_delete_cascade_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_owner_pets_bulk_delete_cascade.json

// Import of required libraries
import { test, expect, SkyrampClient, checkSchema, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import { createOwner, createOwnerPet, createOwnerPetVisit, deleteOwnerPets, getOwner } from './skyrampUtils';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Request Body
    const ownersPostRequestBody: string = `{
        "address": "1 Cascade St",
        "city": "Testville",
        "firstName": "Bulk",
        "lastName": "Deletecase",
        "telephone": "5550100200"
    }`;

    const ownersPostResponse = await createOwner(client, URL_localhost, ownersPostRequestBody);
    expect(ownersPostResponse.statusCode, 'status code').toBe(201);

    expect(getResponseValue(ownersPostResponse, "firstName"), 'firstName').toBe("Bulk");
    expect(getResponseValue(ownersPostResponse, "lastName"), 'lastName').toBe("Deletecase");
    expect(getResponseValue(ownersPostResponse, "address"), 'address').toBe("1 Cascade St");
    expect(getResponseValue(ownersPostResponse, "city"), 'city').toBe("Testville");
    expect(getResponseValue(ownersPostResponse, "telephone"), 'telephone').toBe("5550100200");
    expect(Number(getResponseValue(ownersPostResponse, "id")), 'id').toBeGreaterThan(0);
    expect(checkSchema(ownersPostResponse, '{"pets": []}'), 'pets is an empty array on create').toBe(true);
    expect(getValue(ownersPostResponse, "pets.0"), 'first pet absent on create').toBeNull();

    // Request Body
    const petsPostRequestBody: string = `{
        "birthDate": "2020-01-01",
        "name": "CascadeA",
        "type": {
            "id": 1,
            "name": "cat"
        }
    }`;

    const petsPostResponse = await createOwnerPet(client, URL_localhost, getResponseValue(ownersPostResponse, "id"), petsPostRequestBody);
    expect(petsPostResponse.statusCode, 'status code').toBe(201);

    expect(getResponseValue(petsPostResponse, "name"), 'name').toBe("CascadeA");
    expect(getResponseValue(petsPostResponse, "birthDate"), 'birthDate').toBe("2020-01-01");
    expect(Number(getResponseValue(petsPostResponse, "type.id")), 'type.id').toBe(1);
    expect(getResponseValue(petsPostResponse, "type.name"), 'type.name').toBe("cat");
    expect(Number(getResponseValue(petsPostResponse, "ownerId")), 'ownerId').toBe(Number(getResponseValue(ownersPostResponse, "id")));
    expect(Number(getResponseValue(petsPostResponse, "id")), 'id').toBeGreaterThan(0);
    expect(checkSchema(petsPostResponse, '{"visits": []}'), 'visits is an empty array on create').toBe(true);
    expect(getValue(petsPostResponse, "visits.0"), 'no visit present on create').toBeNull();

    // Request Body
    const petsPost1RequestBody: string = `{
        "birthDate": "2021-02-02",
        "name": "CascadeB",
        "type": {
            "id": 2,
            "name": "dog"
        }
    }`;

    const petsPost1Response = await createOwnerPet(client, URL_localhost, getResponseValue(ownersPostResponse, "id"), petsPost1RequestBody);
    expect(petsPost1Response.statusCode, 'status code').toBe(201);

    expect(getResponseValue(petsPost1Response, "name"), 'name').toBe("CascadeB");
    expect(getResponseValue(petsPost1Response, "birthDate"), 'birthDate').toBe("2021-02-02");
    expect(Number(getResponseValue(petsPost1Response, "type.id")), 'type.id').toBe(2);
    expect(getResponseValue(petsPost1Response, "type.name"), 'type.name').toBe("dog");
    expect(Number(getResponseValue(petsPost1Response, "ownerId")), 'ownerId').toBe(Number(getResponseValue(ownersPostResponse, "id")));
    expect(Number(getResponseValue(petsPost1Response, "id")), 'id').not.toBe(Number(getResponseValue(petsPostResponse, "id")));

    // Request Body
    const visitsPostRequestBody: string = `{
        "date": "2024-01-15",
        "description": "cascade probe visit"
    }`;

    const visitsPostResponse = await createOwnerPetVisit(client, URL_localhost, getResponseValue(ownersPostResponse, "id"), getResponseValue(petsPostResponse, "id"), visitsPostRequestBody);
    expect(visitsPostResponse.statusCode, 'status code').toBe(201);

    expect(getResponseValue(visitsPostResponse, "description"), 'description').toBe("cascade probe visit");
    expect(getResponseValue(visitsPostResponse, "date"), 'date').toBe("2024-01-15");
    expect(Number(getResponseValue(visitsPostResponse, "petId")), 'petId').toBe(Number(getResponseValue(petsPostResponse, "id")));
    expect(Number(getResponseValue(visitsPostResponse, "id")), 'id').toBeGreaterThan(0);

    const petsDeleteResponse = await deleteOwnerPets(client, URL_localhost, getResponseValue(ownersPostResponse, "id"));
    expect(petsDeleteResponse.statusCode, 'status code').toBe(204);

    const ownersOwnersGetResponse = await getOwner(client, URL_localhost, getResponseValue(ownersPostResponse, "id"));
    expect(ownersOwnersGetResponse.statusCode, 'status code').toBe(200);

    expect(getValue(ownersOwnersGetResponse, "pets.0"), 'no pet remains after bulk delete').toBeNull();
    expect(checkSchema(ownersOwnersGetResponse, '{"pets": []}'), 'pets is an empty array after bulk delete').toBe(true);
    expect(Number(getResponseValue(ownersOwnersGetResponse, "id")), 'owner survived the bulk delete').toBe(Number(getResponseValue(ownersPostResponse, "id")));
    expect(getResponseValue(ownersOwnersGetResponse, "firstName"), 'firstName unchanged').toBe("Bulk");
    expect(getResponseValue(ownersOwnersGetResponse, "lastName"), 'lastName unchanged').toBe("Deletecase");
});
