// Generated by Skyramp v1.3.44 on 2026-09-09 04:45:35.72967086 +0000 UTC m=+1352.884321656
// Command: skyramp generate integration rest \
// 		--chaining-key id \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_email_lifecycle_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_api-owner-email-lifecycle.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import { createOwner, getOwner, updateOwner, deleteOwner } from './skyrampUtils';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Request Body
    const ownersPostRequestBody: string = `{
        "address": "42 Inbox Lane",
        "city": "Madison",
        "email": "emilia.mailford@example.com",
        "firstName": "Emilia",
        "lastName": "Mailford",
        "telephone": "6085552601"
    }`;

    const ownersPostResponse = await createOwner(client, URL_localhost, ownersPostRequestBody);
    expect(ownersPostResponse.statusCode, 'status code').toBe(201);
    expect(getResponseValue(ownersPostResponse, "email"), 'email').toBe("emilia.mailford@example.com");
    expect(getResponseValue(ownersPostResponse, "firstName"), 'firstName').toBe("Emilia");
    expect(getResponseValue(ownersPostResponse, "lastName"), 'lastName').toBe("Mailford");
    expect(getResponseValue(ownersPostResponse, "address"), 'address').toBe("42 Inbox Lane");
    expect(getResponseValue(ownersPostResponse, "city"), 'city').toBe("Madison");
    expect(getResponseValue(ownersPostResponse, "telephone"), 'telephone').toBe("6085552601");
    expect(Number(getResponseValue(ownersPostResponse, "id")), 'id').toBeGreaterThan(0);
    expect(getResponseValue(ownersPostResponse, "pets").length, 'pets length').toBe(0);
    expect(getResponseValue(ownersPostResponse, "pets.0"), 'pets.0').toBeNull();

    const ownersOwnersGetResponse = await getOwner(client, URL_localhost, getResponseValue(ownersPostResponse, "id"));
    expect(ownersOwnersGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(ownersOwnersGetResponse, "id"), 'id').toBe(getResponseValue(ownersPostResponse, "id"));
    expect(getResponseValue(ownersOwnersGetResponse, "email"), 'email').toBe("emilia.mailford@example.com");
    expect(getResponseValue(ownersOwnersGetResponse, "city"), 'city').toBe("Madison");
    expect(getResponseValue(ownersOwnersGetResponse, "telephone"), 'telephone').toBe("6085552601");

    // Request Body
    const ownersOwnersPutRequestBody: string = `{
        "address": "42 Inbox Lane",
        "city": "Madison",
        "email": "emilia.updated@example.com",
        "firstName": "Emilia",
        "lastName": "Mailford",
        "telephone": "6085552601"
    }`;

    const ownersOwnersPutResponse = await updateOwner(client, URL_localhost, getResponseValue(ownersPostResponse, "id"), ownersOwnersPutRequestBody, {
        "address": getResponseValue(ownersOwnersGetResponse, "address"),
        "city": getResponseValue(ownersOwnersGetResponse, "city"),
        "firstName": getResponseValue(ownersOwnersGetResponse, "firstName"),
        "lastName": getResponseValue(ownersOwnersGetResponse, "lastName"),
        "telephone": getResponseValue(ownersOwnersGetResponse, "telephone")
    });
    expect(ownersOwnersPutResponse.statusCode, 'status code').toBe(204);

    const ownersOwnersGet1Response = await getOwner(client, URL_localhost, getResponseValue(ownersPostResponse, "id"));
    expect(ownersOwnersGet1Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(ownersOwnersGet1Response, "id"), 'id').toBe(getResponseValue(ownersPostResponse, "id"));
    expect(getResponseValue(ownersOwnersGet1Response, "email"), 'email').toBe("emilia.updated@example.com");
    expect(getResponseValue(ownersOwnersGet1Response, "city"), 'city').toBe("Madison");

    // Request Body
    const ownersOwnersPut1RequestBody: string = `{
        "address": "42 Inbox Lane",
        "city": "Monona",
        "firstName": "Emilia",
        "lastName": "Mailford",
        "telephone": "6085552601"
    }`;

    const ownersOwnersPut1Response = await updateOwner(client, URL_localhost, getResponseValue(ownersPostResponse, "id"), ownersOwnersPut1RequestBody, {
        "address": getResponseValue(ownersOwnersGetResponse, "address"),
        "firstName": getResponseValue(ownersOwnersGetResponse, "firstName"),
        "lastName": getResponseValue(ownersOwnersGetResponse, "lastName"),
        "telephone": getResponseValue(ownersOwnersGetResponse, "telephone")
    });
    expect(ownersOwnersPut1Response.statusCode, 'status code').toBe(204);

    const ownersOwnersGet2Response = await getOwner(client, URL_localhost, getResponseValue(ownersPostResponse, "id"));
    expect(ownersOwnersGet2Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(ownersOwnersGet2Response, "id"), 'id').toBe(getResponseValue(ownersPostResponse, "id"));
    expect(getResponseValue(ownersOwnersGet2Response, "city"), 'city').toBe("Monona");
    expect(getResponseValue(ownersOwnersGet2Response, "email"), 'email').toBe("emilia.updated@example.com");
    expect(getResponseValue(ownersOwnersGet2Response, "telephone"), 'telephone').toBe("6085552601");
    expect(getResponseValue(ownersOwnersGet2Response, "lastName"), 'lastName').toBe("Mailford");

    const ownersOwnersDeleteResponse = await deleteOwner(client, URL_localhost, getResponseValue(ownersPostResponse, "id"));
    expect(ownersOwnersDeleteResponse.statusCode, 'status code').toBe(204);
    const ownersDeletedGetResponse = await getOwner(client, URL_localhost, getResponseValue(ownersPostResponse, "id"), 404);
    expect(ownersDeletedGetResponse.statusCode, 'status code').toBe(404);
    expect(getResponseValue(ownersDeletedGetResponse, "email"), 'email').toBeNull();
    expect(getResponseValue(ownersDeletedGetResponse, "id"), 'id').toBeNull();
});
