// Generated by Skyramp v1.3.44 on 2026-09-08 19:16:31.858136338 +0000 UTC m=+1432.203952161
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output owner_phone_number_only_update_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_owner_phone_number_only_update.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import { createOwner, updateOwner, getOwner, deleteOwner } from './skyrampUtils';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Request Body
    const ownersPostRequestBody: string = `{
        "address": "3 Contract Way",
        "city": "Madison",
        "firstName": "Phonetwo",
        "lastName": "Onlycase",
        "phoneNumber": "6085550333"
    }`;

    const ownersPostResponse = await createOwner(client, ownersPostRequestBody, 201);
    expect(ownersPostResponse.statusCode, 'status code').toBe(201);
    expect(getResponseValue(ownersPostResponse, "firstName"), 'firstName').toBe("Phonetwo");
    expect(getResponseValue(ownersPostResponse, "lastName"), 'lastName').toBe("Onlycase");
    expect(getResponseValue(ownersPostResponse, "address"), 'address').toBe("3 Contract Way");
    expect(getResponseValue(ownersPostResponse, "city"), 'city').toBe("Madison");
    expect(getResponseValue(ownersPostResponse, "phoneNumber"), 'phoneNumber').toBe("6085550333");
    expect(getResponseValue(ownersPostResponse, "telephone"), 'telephone mirrors phoneNumber').toBe("6085550333");
    expect(Number(getResponseValue(ownersPostResponse, "id")), 'id').toBeGreaterThan(0);
    const ownerId = getResponseValue(ownersPostResponse, "id");

    // Request Body
    const ownersOwnersPutRequestBody: string = `{
        "address": "4 Contract Way",
        "city": "Madison",
        "firstName": "Phonetwo",
        "lastName": "Onlycase",
        "phoneNumber": "6085550444"
    }`;

    const ownersOwnersPutResponse = await updateOwner(client, ownerId, ownersOwnersPutRequestBody, 204);
    expect(ownersOwnersPutResponse.statusCode, 'status code').toBe(204);

    const ownersOwnersGetResponse = await getOwner(client, ownerId, 200);
    expect(ownersOwnersGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(ownersOwnersGetResponse, "id"), 'id').toBe(ownerId);
    expect(getResponseValue(ownersOwnersGetResponse, "firstName"), 'firstName').toBe("Phonetwo");
    expect(getResponseValue(ownersOwnersGetResponse, "lastName"), 'lastName').toBe("Onlycase");
    expect(getResponseValue(ownersOwnersGetResponse, "city"), 'city').toBe("Madison");
    expect(getResponseValue(ownersOwnersGetResponse, "address"), 'address updated by the PUT').toBe("4 Contract Way");
    expect(getResponseValue(ownersOwnersGetResponse, "phoneNumber"), 'phoneNumber updated by the PUT').toBe("6085550444");
    expect(getResponseValue(ownersOwnersGetResponse, "telephone"), 'telephone mirrors phoneNumber').toBe("6085550444");

    const ownersOwnersDeleteResponse = await deleteOwner(client, ownerId, 204);
    expect(ownersOwnersDeleteResponse.statusCode, 'status code').toBe(204);
});
