// Generated by Skyramp v1.3.44 on 2026-09-08 19:31:17.9 +0000 UTC
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output pet_nickname_owner_scoped_update_dropped_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_pet_nickname_owner_scoped_update_dropped.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import {
    createOwner,
    createOwnerPet,
    updateOwnerPet,
    getPet,
    deletePet,
    deleteOwner
} from './skyrampUtils';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();

    const ownersPostResponse = await createOwner(
        client,
        "Nickname",
        "Ownerroute",
        "3 Nickname St.",
        "Madison",
        "6085550003"
    );

    expect(ownersPostResponse.statusCode, 'status code').toBe(201);
    expect(Number(getResponseValue(ownersPostResponse, "id")), 'owner id').toBeGreaterThan(0);
    expect(getResponseValue(ownersPostResponse, "firstName"), 'firstName').toBe("Nickname");
    expect(getResponseValue(ownersPostResponse, "lastName"), 'lastName').toBe("Ownerroute");

    const petsPostResponse = await createOwnerPet(
        client,
        getResponseValue(ownersPostResponse, "id"),
        "Zephyr",
        "2020-01-01",
        "Origin"
    );

    expect(petsPostResponse.statusCode, 'status code').toBe(201);
    expect(Number(getResponseValue(petsPostResponse, "id")), 'pet id').toBeGreaterThan(0);
    expect(getResponseValue(petsPostResponse, "nickname"), 'the nickname the pet starts with').toBe("Origin");
    expect(getResponseValue(petsPostResponse, "name"), 'name').toBe("Zephyr");

    const petsPetsPutResponse = await updateOwnerPet(
        client,
        getResponseValue(ownersPostResponse, "id"),
        getResponseValue(petsPostResponse, "id"),
        "Zephyr",
        "2020-01-01",
        1,
        "cat",
        "Renamed"
    );

    expect(petsPetsPutResponse.statusCode, 'the owner-scoped update reports success').toBe(204);

    const apiPetsPetsGetResponse = await getPet(client, getResponseValue(petsPostResponse, "id"));

    expect(apiPetsPetsGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(apiPetsPetsGetResponse, "nickname"), 'the nickname the owner-scoped update accepted must be the stored one').toBe("Renamed");
    expect(getResponseValue(apiPetsPetsGetResponse, "name"), 'name').toBe("Zephyr");
    expect(getResponseValue(apiPetsPetsGetResponse, "birthDate"), 'birthDate').toBe("2020-01-01");
    expect(Number(getResponseValue(apiPetsPetsGetResponse, "id")), 'pet id').toBe(Number(getResponseValue(petsPostResponse, "id")));

    const apiPetsPetsDeleteResponse = await deletePet(client, getResponseValue(petsPostResponse, "id"));

    expect(apiPetsPetsDeleteResponse.statusCode, 'status code').toBe(204);

    const ownersOwnersDeleteResponse = await deleteOwner(client, getResponseValue(ownersPostResponse, "id"));
});
