// Generated by Skyramp v1.3.44 on 2026-09-08 19:31:06.67916689 +0000 UTC m=+2312.167169799
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output pet_nickname_add_edit_round_trip_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_pet_nickname_add_edit_round_trip.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import {
    createOwner,
    createOwnerPet,
    getPet,
    updatePet,
    deletePet,
    deleteOwner
} from './skyrampUtils';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();

    const ownersPostResponse = await createOwner(
        client,
        "Nickname",
        "Roundtrip",
        "1 Nickname St.",
        "Madison",
        "6085550001"
    );

    expect(Number(getResponseValue(ownersPostResponse, "id")), 'owner id').toBeGreaterThan(0);
    expect(getResponseValue(ownersPostResponse, "firstName"), 'firstName').toBe("Nickname");
    expect(getResponseValue(ownersPostResponse, "lastName"), 'lastName').toBe("Roundtrip");
    expect(getResponseValue(ownersPostResponse, "address"), 'address').toBe("1 Nickname St.");
    expect(getResponseValue(ownersPostResponse, "city"), 'city').toBe("Madison");
    expect(getResponseValue(ownersPostResponse, "telephone"), 'telephone').toBe("6085550001");

    const petsPostResponse = await createOwnerPet(
        client,
        getResponseValue(ownersPostResponse, "id"),
        "Zephyr",
        "2020-01-01",
        "Zippy"
    );

    expect(Number(getResponseValue(petsPostResponse, "id")), 'pet id').toBeGreaterThan(0);
    expect(getResponseValue(petsPostResponse, "nickname"), 'created nickname').toBe("Zippy");
    expect(getResponseValue(petsPostResponse, "name"), 'name').toBe("Zephyr");
    expect(getResponseValue(petsPostResponse, "birthDate"), 'birthDate').toBe("2020-01-01");
    expect(Number(getResponseValue(petsPostResponse, "type.id")), 'type.id').toBe(1);
    expect(getResponseValue(petsPostResponse, "type.name"), 'type.name').toBe("cat");
    expect(Number(getResponseValue(petsPostResponse, "ownerId")), 'ownerId').toBe(Number(getResponseValue(ownersPostResponse, "id")));

    const petsPetsGetResponse = await getPet(client, getResponseValue(petsPostResponse, "id"));

    expect(getResponseValue(petsPetsGetResponse, "nickname"), 'stored nickname').toBe("Zippy");
    expect(getResponseValue(petsPetsGetResponse, "name"), 'name').toBe("Zephyr");
    expect(Number(getResponseValue(petsPetsGetResponse, "id")), 'pet id').toBe(Number(getResponseValue(petsPostResponse, "id")));

    const petsPetsPutResponse = await updatePet(
        client,
        getResponseValue(petsPostResponse, "id"),
        getResponseValue(petsPostResponse, "ownerId"),
        getResponseValue(petsPetsGetResponse, "name"),
        getResponseValue(petsPetsGetResponse, "birthDate"),
        getResponseValue(petsPetsGetResponse, "type.id"),
        getResponseValue(petsPetsGetResponse, "type.name"),
        "Zappy"
    );

    const petsPetsGet1Response = await getPet(client, getResponseValue(petsPostResponse, "id"));

    expect(petsPetsGet1Response.statusCode, 'status code').toBe(200);
    expect(getResponseValue(petsPetsGet1Response, "nickname"), 'updated nickname').toBe("Zappy");
    expect(getResponseValue(petsPetsGet1Response, "name"), 'name is untouched by the nickname update').toBe("Zephyr");
    expect(getResponseValue(petsPetsGet1Response, "birthDate"), 'birthDate is untouched by the nickname update').toBe("2020-01-01");
    expect(getResponseValue(petsPetsGet1Response, "type.name"), 'type is untouched by the nickname update').toBe("cat");

    const petsPetsDeleteResponse = await deletePet(client, getResponseValue(petsPostResponse, "id"));

    const ownersOwnersDeleteResponse = await deleteOwner(client, getResponseValue(ownersPostResponse, "id"));
});
