// Generated by Skyramp on 2026-09-08 19:11:18.250 Coordinated Universal Time


import { expect, SkyrampClient, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

export async function createVisit(client: SkyrampClient, body: string, dataOverride: Record<string, string> = {}, expectedStatus: number = 201) {
    const response = await client.sendRequest({
        url: URL_localhost,
        path: "/petclinic/api/visits",
        method: "POST",
        body: body,
        dataOverride: dataOverride
    });

    expect(response.statusCode, 'status code').toBe(expectedStatus);
    return response;
}

export async function getVisit(client: SkyrampClient, visitId: string, expectedStatus: number = 200) {
    const response = await client.sendRequest({
        url: URL_localhost,
        path: "/petclinic/api/visits/{visits}",
        method: "GET",
        pathParams: {"visits": visitId}
    });

    expect(response.statusCode, 'status code').toBe(expectedStatus);
    return response;
}

export async function deleteVisit(client: SkyrampClient, visitId: string, expectedStatus: number = 204) {
    const response = await client.sendRequest({
        url: URL_localhost,
        path: "/petclinic/api/visits/{visits}",
        method: "DELETE",
        pathParams: {"visits": visitId}
    });

    expect(response.statusCode, 'status code').toBe(expectedStatus);
    return response;
}
