// Generated by Skyramp on 2026-09-09 04:58:50.217 Coordinated Universal Time


import { expect, SkyrampClient } from '@skyramp/skyramp';

export async function createOwner(client: SkyrampClient, url: string, body: string, expectedStatus = 201) {
    const response = await client.sendRequest({
        url: url,
        path: "/petclinic/api/owners",
        method: "POST",
        body: body
    });

    expect(response.statusCode, 'status code').toBe(expectedStatus);
    return response;
}

export async function createPet(client: SkyrampClient, url: string, ownerId: any, body: string, expectedStatus = 201) {
    const response = await client.sendRequest({
        url: url,
        path: "/petclinic/api/owners/{owners}/pets",
        method: "POST",
        body: body,
        pathParams: {"owners": ownerId}
    });

    expect(response.statusCode, 'status code').toBe(expectedStatus);
    return response;
}

export async function createVisit(client: SkyrampClient, url: string, ownerId: any, petId: any, body: string, expectedStatus = 201) {
    const response = await client.sendRequest({
        url: url,
        path: "/petclinic/api/owners/{owners}/pets/{pets}/visits",
        method: "POST",
        body: body,
        pathParams: {
            "owners": ownerId,
            "pets": petId
        }
    });

    expect(response.statusCode, 'status code').toBe(expectedStatus);
    return response;
}

export async function updateVisit(client: SkyrampClient, url: string, visitId: any, body: string, expectedStatus = 204) {
    const response = await client.sendRequest({
        url: url,
        path: "/petclinic/api/visits/{visits}",
        method: "PUT",
        body: body,
        pathParams: {"visits": visitId}
    });

    expect(response.statusCode, 'status code').toBe(expectedStatus);
    return response;
}

export async function getVisit(client: SkyrampClient, url: string, visitId: any, expectedStatus = 200) {
    const response = await client.sendRequest({
        url: url,
        path: "/petclinic/api/visits/{visits}",
        method: "GET",
        pathParams: {"visits": visitId}
    });

    expect(response.statusCode, 'status code').toBe(expectedStatus);
    return response;
}

export async function deleteOwner(client: SkyrampClient, url: string, ownerId: any, expectedStatus = 204) {
    const response = await client.sendRequest({
        url: url,
        path: "/petclinic/api/owners/{owners}",
        method: "DELETE",
        pathParams: {"owners": ownerId}
    });

    expect(response.statusCode, 'status code').toBe(expectedStatus);
    return response;
}
