// Generated by Skyramp on 2026-09-08 19:16:21.982 Coordinated Universal Time


import { expect, SkyrampClient, getBaseUrl } from '@skyramp/skyramp';

// URL for test requests
export const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

export async function createVisit(
    client: SkyrampClient,
    ownerId: number,
    petId: number,
    body: string,
    dataOverride: Record<string, unknown> | undefined = undefined,
    expectedStatus = 201
) {
    const response = await client.sendRequest({
        url: URL_localhost,
        path: "/petclinic/api/owners/{ownerId}/pets/{petId}/visits",
        method: "POST",
        pathParams: {"ownerId": ownerId, "petId": petId},
        body: body,
        dataOverride: dataOverride
    });

    // Generated Assertions
    expect(response.statusCode, 'status code').toBe(expectedStatus);
    return response;
}

export async function getVisit(client: SkyrampClient, visitId: unknown, expectedStatus = 200) {
    const response = await client.sendRequest({
        url: URL_localhost,
        path: "/petclinic/api/visits/{visits}",
        method: "GET",
        pathParams: {"visits": visitId}
    });

    // Generated Assertions
    expect(response.statusCode, 'status code').toBe(expectedStatus);
    return response;
}

export async function deleteVisit(client: SkyrampClient, visitId: unknown, expectedStatus = 204) {
    const response = await client.sendRequest({
        url: URL_localhost,
        path: "/petclinic/api/visits/{visits}",
        method: "DELETE",
        pathParams: {"visits": visitId}
    });

    // Generated Assertions
    expect(response.statusCode, 'status code').toBe(expectedStatus);
    return response;
}
