// Generated by Skyramp v1.3.40 on 2026-09-02 08:08:31.000000000 +0000 UTC
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output visit_duration_create_and_read_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_visit_duration_create_and_read.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import { createOwner, createPet, createVisit, getVisit, getPet } from './skyrampUtils';

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();

    const ownersPostResponse = await createOwner(
        client, "Persist", "Probe", "2 Test Way", "Testville", "5550002222"
    );

    expect(getResponseValue(ownersPostResponse, "firstName"), 'firstName').toBe("Persist");
    expect(getResponseValue(ownersPostResponse, "lastName"), 'lastName').toBe("Probe");
    expect(getResponseValue(ownersPostResponse, "telephone"), 'telephone').toBe("5550002222");
    expect(getResponseValue(ownersPostResponse, "id"), 'owner id').toBeGreaterThan(0);

    const petsPostResponse = await createPet(
        client, getResponseValue(ownersPostResponse, "id"), "Persist", "2019-05-05", 1, "cat"
    );

    expect(getResponseValue(petsPostResponse, "name"), 'pet name').toBe("Persist");
    expect(getResponseValue(petsPostResponse, "birthDate"), 'pet birthDate').toBe("2019-05-05");
    expect(getResponseValue(petsPostResponse, "type.name"), 'pet type').toBe("cat");
    expect(getResponseValue(petsPostResponse, "ownerId"), 'pet ownerId').toBe(getResponseValue(ownersPostResponse, "id"));
    // A freshly created pet has no visits yet
    expect(getResponseValue(petsPostResponse, "visits.0"), 'no visits on new pet').toBeNull();

    const visitsPostResponse = await createVisit(
        client,
        getResponseValue(ownersPostResponse, "id"),
        getResponseValue(petsPostResponse, "id"),
        "2026-09-03",
        "dental cleaning",
        45
    );

    expect(getResponseValue(visitsPostResponse, "date"), 'visit date').toBe("2026-09-03");
    expect(getResponseValue(visitsPostResponse, "description"), 'visit description').toBe("dental cleaning");
    expect(getResponseValue(visitsPostResponse, "durationMinutes"), 'duration echoed on create').toBe(45);
    expect(getResponseValue(visitsPostResponse, "petId"), 'visit petId').toBe(getResponseValue(petsPostResponse, "id"));
    expect(getResponseValue(visitsPostResponse, "id"), 'visit id').toBeGreaterThan(0);

    const visitsVisitsGetResponse = await getVisit(
        client, getResponseValue(visitsPostResponse, "id")
    );

    expect(getResponseValue(visitsVisitsGetResponse, "id"), 'visit id').toBe(getResponseValue(visitsPostResponse, "id"));
    expect(getResponseValue(visitsVisitsGetResponse, "date"), 'visit date').toBe("2026-09-03");
    expect(getResponseValue(visitsVisitsGetResponse, "description"), 'visit description').toBe("dental cleaning");
    // duration_minutes must survive the round trip through the new database column
    expect(getResponseValue(visitsVisitsGetResponse, "durationMinutes"), 'duration read back').toBe(45);
    expect(getResponseValue(visitsVisitsGetResponse, "durationMinutes"), 'duration at least the 5 minute minimum').toBeGreaterThanOrEqual(5);
    expect(getResponseValue(visitsVisitsGetResponse, "durationMinutes"), 'duration at most the 240 minute maximum').toBeLessThanOrEqual(240);

    const petsPetsGetResponse = await getPet(
        client, getResponseValue(petsPostResponse, "id")
    );

    expect(getResponseValue(petsPetsGetResponse, "id"), 'pet id').toBe(getResponseValue(petsPostResponse, "id"));
    expect(getResponseValue(petsPetsGetResponse, "visits.0.id"), 'embedded visit id').toBe(getResponseValue(visitsPostResponse, "id"));
    expect(getResponseValue(petsPetsGetResponse, "visits.0.description"), 'embedded visit description').toBe("dental cleaning");
    // This is the payload the owner detail screen consumes to render the new Duration column
    expect(getResponseValue(petsPetsGetResponse, "visits.0.durationMinutes"), 'embedded visit duration').toBe(45);
    expect(getResponseValue(petsPetsGetResponse, "visits.1"), 'no second visit').toBeNull();
});
