// Generated by Skyramp v1.3.44 on 2026-09-08 19:24:22.369086661 +0000 UTC m=+1947.372691301
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output visits_duration_out_of_range_rejected_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_visits_duration_out_of_range_rejected.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import { createVisit, deleteVisit } from './skyrampUtils';

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Request Body
    const visitsPostRequestBody: string = `{
        "date": "2026-10-20",
        "description": "duration min",
        "durationMinutes": 5,
        "petId": 7
    }`;

    // Request Body
    const visitsPost1RequestBody: string = `{
        "date": "2026-10-21",
        "description": "duration max",
        "durationMinutes": 240,
        "petId": 7
    }`;

    // Request Body
    const visitsPost2RequestBody: string = `{
        "date": "2026-10-22",
        "description": "duration below min",
        "durationMinutes": 4,
        "petId": 7
    }`;

    // Request Body
    const visitsPost3RequestBody: string = `{
        "date": "2026-10-23",
        "description": "duration above max",
        "durationMinutes": 241,
        "petId": 7
    }`;

    // Request Body
    const visitsPost4RequestBody: string = `{
        "date": "2026-10-24",
        "description": "duration zero",
        "durationMinutes": 0,
        "petId": 7
    }`;

    // Request Body
    const visitsPost5RequestBody: string = `{
        "date": "2026-10-25",
        "description": "duration negative",
        "durationMinutes": -10,
        "petId": 7
    }`;

    // Request Body
    const visitsPost6RequestBody: string = `{
        "date": "2026-10-26",
        "description": "duration bad pet",
        "durationMinutes": 30,
        "petId": 999999
    }`;

    // 5 minutes is the lowest accepted duration
    const visitsPostResponse = await createVisit(client, visitsPostRequestBody, 201);

    expect(visitsPostResponse.statusCode, 'status code').toBe(201);
    expect(getResponseValue(visitsPostResponse, "id"), 'id').toBeGreaterThan(0);
    expect(getResponseValue(visitsPostResponse, "description"), 'description').toBe("duration min");
    expect(getResponseValue(visitsPostResponse, "durationMinutes"), 'durationMinutes').toBe(5);

    // 240 minutes is the highest accepted duration
    const visitsPost1Response = await createVisit(client, visitsPost1RequestBody, 201);

    expect(visitsPost1Response.statusCode, 'status code').toBe(201);
    expect(getResponseValue(visitsPost1Response, "id"), 'id').toBeGreaterThan(0);
    expect(getResponseValue(visitsPost1Response, "description"), 'description').toBe("duration max");
    expect(getResponseValue(visitsPost1Response, "durationMinutes"), 'durationMinutes').toBe(240);

    // 4 is one minute below the minimum
    const visitsPost2Response = await createVisit(client, visitsPost2RequestBody, 400);

    expect(visitsPost2Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(visitsPost2Response, "status"), 'status').toBe(400);
    expect(getResponseValue(visitsPost2Response, "title"), 'title').toBe("MethodArgumentNotValidException");
    expect(getResponseValue(visitsPost2Response, "schemaValidationErrors.0.field"), 'field').toBe("durationMinutes");
    expect(getResponseValue(visitsPost2Response, "schemaValidationErrors.0.rejectedValue"), 'rejectedValue').toBe("4");
    expect(getResponseValue(visitsPost2Response, "schemaValidationErrors.0.defaultMessage"), 'message').toBe("must be greater than or equal to 5");
    expect(getResponseValue(visitsPost2Response, "schemaValidationErrors.1"), 'only one validation error').toBeNull();

    // 241 is one minute above the maximum
    const visitsPost3Response = await createVisit(client, visitsPost3RequestBody, 400);

    expect(visitsPost3Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(visitsPost3Response, "status"), 'status').toBe(400);
    expect(getResponseValue(visitsPost3Response, "schemaValidationErrors.0.field"), 'field').toBe("durationMinutes");
    expect(getResponseValue(visitsPost3Response, "schemaValidationErrors.0.rejectedValue"), 'rejectedValue').toBe("241");
    expect(getResponseValue(visitsPost3Response, "schemaValidationErrors.0.defaultMessage"), 'message').toBe("must be less than or equal to 240");
    expect(getResponseValue(visitsPost3Response, "schemaValidationErrors.1"), 'only one validation error').toBeNull();

    // A zero duration is below the minimum
    const visitsPost4Response = await createVisit(client, visitsPost4RequestBody, 400);

    expect(visitsPost4Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(visitsPost4Response, "status"), 'status').toBe(400);
    expect(getResponseValue(visitsPost4Response, "schemaValidationErrors.0.field"), 'field').toBe("durationMinutes");
    expect(getResponseValue(visitsPost4Response, "schemaValidationErrors.0.rejectedValue"), 'rejectedValue').toBe("0");
    expect(getResponseValue(visitsPost4Response, "schemaValidationErrors.1"), 'only one validation error').toBeNull();

    // A negative duration is below the minimum
    const visitsPost5Response = await createVisit(client, visitsPost5RequestBody, 400);

    expect(visitsPost5Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(visitsPost5Response, "status"), 'status').toBe(400);
    expect(getResponseValue(visitsPost5Response, "schemaValidationErrors.0.field"), 'field').toBe("durationMinutes");
    expect(getResponseValue(visitsPost5Response, "schemaValidationErrors.0.rejectedValue"), 'rejectedValue').toBe("-10");
    expect(getResponseValue(visitsPost5Response, "schemaValidationErrors.1"), 'only one validation error').toBeNull();

    // A pet that does not exist cannot be booked
    const visitsPost6Response = await createVisit(client, visitsPost6RequestBody, 404);

    expect(visitsPost6Response.statusCode, 'status code').toBe(404);

    const visitsVisitsDeleteResponse = await deleteVisit(client, getResponseValue(visitsPostResponse, "id"), 204);

    expect(visitsVisitsDeleteResponse.statusCode, 'status code').toBe(204);

    const visitsVisitsDelete1Response = await deleteVisit(client, getResponseValue(visitsPost1Response, "id"), 204);

    expect(visitsVisitsDelete1Response.statusCode, 'status code').toBe(204);
});
