// Generated by Skyramp v1.3.44 on 2026-09-08 19:24:09.168948446 +0000 UTC m=+1934.172553106
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output visits_duration_create_persists_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_visits_duration_create_persists.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import { createVisit, getVisit, deleteVisit } from './skyrampUtils';

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Request Body
    const visitsPostRequestBody: string = `{
        "date": "2026-10-15",
        "description": "duration create",
        "durationMinutes": 45,
        "petId": 7
    }`;

    const visitsPostResponse = await createVisit(client, visitsPostRequestBody, 201);

    expect(visitsPostResponse.statusCode, 'status code').toBe(201);
    // Echo-back of the created visit, including the durationMinutes this PR adds
    expect(getResponseValue(visitsPostResponse, "id"), 'id').toBeGreaterThan(0);
    expect(getResponseValue(visitsPostResponse, "date"), 'date').toBe("2026-10-15");
    expect(getResponseValue(visitsPostResponse, "description"), 'description').toBe("duration create");
    expect(getResponseValue(visitsPostResponse, "durationMinutes"), 'durationMinutes').toBe(45);
    expect(getResponseValue(visitsPostResponse, "petId"), 'petId').toBe(7);

    const visitsVisitsGetResponse = await getVisit(
        client,
        getResponseValue(visitsPostResponse, "id"),
        200
    );

    expect(visitsVisitsGetResponse.statusCode, 'status code').toBe(200);
    // The stored duration survives the round trip
    expect(getResponseValue(visitsVisitsGetResponse, "id"), 'id').toBe(getResponseValue(visitsPostResponse, "id"));
    expect(getResponseValue(visitsVisitsGetResponse, "date"), 'date').toBe("2026-10-15");
    expect(getResponseValue(visitsVisitsGetResponse, "description"), 'description').toBe("duration create");
    expect(getResponseValue(visitsVisitsGetResponse, "durationMinutes"), 'durationMinutes').toBe(45);
    expect(getResponseValue(visitsVisitsGetResponse, "petId"), 'petId').toBe(7);

    // Request Body
    const visitsPost1RequestBody: string = `{
        "date": "2026-10-16",
        "description": "duration default",
        "petId": 7
    }`;

    const visitsPost1Response = await createVisit(client, visitsPost1RequestBody, 201);

    expect(visitsPost1Response.statusCode, 'status code').toBe(201);
    // durationMinutes was omitted, so the API applies its documented default of 30
    expect(getResponseValue(visitsPost1Response, "id"), 'id').toBeGreaterThan(0);
    expect(getResponseValue(visitsPost1Response, "date"), 'date').toBe("2026-10-16");
    expect(getResponseValue(visitsPost1Response, "description"), 'description').toBe("duration default");
    expect(getResponseValue(visitsPost1Response, "durationMinutes"), 'durationMinutes').toBe(30);
    expect(getResponseValue(visitsPost1Response, "petId"), 'petId').toBe(7);

    const visitsVisitsGet1Response = await getVisit(
        client,
        getResponseValue(visitsPost1Response, "id"),
        200
    );

    expect(visitsVisitsGet1Response.statusCode, 'status code').toBe(200);
    // The default was persisted, not just echoed
    expect(getResponseValue(visitsVisitsGet1Response, "id"), 'id').toBe(getResponseValue(visitsPost1Response, "id"));
    expect(getResponseValue(visitsVisitsGet1Response, "date"), 'date').toBe("2026-10-16");
    expect(getResponseValue(visitsVisitsGet1Response, "description"), 'description').toBe("duration default");
    expect(getResponseValue(visitsVisitsGet1Response, "durationMinutes"), 'durationMinutes').toBe(30);
    expect(getResponseValue(visitsVisitsGet1Response, "petId"), 'petId').toBe(7);

    const visitsVisitsDeleteResponse = await deleteVisit(client, getResponseValue(visitsPostResponse, "id"), 204);

    expect(visitsVisitsDeleteResponse.statusCode, 'status code').toBe(204);

    const visitsVisitsDelete1Response = await deleteVisit(client, getResponseValue(visitsPost1Response, "id"), 204);

    expect(visitsVisitsDelete1Response.statusCode, 'status code').toBe(204);
});
