// Generated by Skyramp v1.3.40 on 2026-08-29 09:26:21.000062043 +0000 UTC m=+1090.688547664
// Command: skyramp generate integration rest \
// 		--chaining-key id \
// 		--framework playwright \
// 		--language typescript \
// 		--output visit_description_30_char_boundary_roundtrip_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_visit_description_30_char_boundary_roundtrip.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import { createVisit, getVisit } from './skyrampUtils';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();

    const visitsPostResponse = await createVisit(client, "2026-08-29", "123456789012345678901234567890", 1);
    expect(getResponseValue(visitsPostResponse, "description"), 'description').toBe("123456789012345678901234567890");
    expect(getResponseValue(visitsPostResponse, "date"), 'date').toBe("2026-08-29");
    expect(getResponseValue(visitsPostResponse, "petId"), 'petId').toBe(1);
    expect(getResponseValue(visitsPostResponse, "id"), 'id').toBeGreaterThan(0);

    const visitsVisitsGetResponse = await getVisit(client, getResponseValue(visitsPostResponse, "id"));
    expect(getResponseValue(visitsVisitsGetResponse, "description"), 'description round-trips at full 30-character length').toBe("123456789012345678901234567890");
    expect(String(getResponseValue(visitsVisitsGetResponse, "description")).length, 'description not truncated').toBe(30);
    expect(getResponseValue(visitsVisitsGetResponse, "date"), 'date').toBe("2026-08-29");
    expect(getResponseValue(visitsVisitsGetResponse, "petId"), 'petId').toBe(1);
    expect(getResponseValue(visitsVisitsGetResponse, "id"), 'id').toBe(getResponseValue(visitsPostResponse, "id"));
});
