// Generated by Skyramp v1.3.40 on 2026-08-29 09:27:49.08940882 +0000 UTC m=+1189.219192533
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output visit_duration_nested_in_owner_response_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_visit_duration_nested_in_owner_response.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import { createVisit, getOwner } from './skyrampUtils';

// URL for test requests
const URL_localhost = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    const visitsPostResponse = await createVisit(client, URL_localhost, "2026-08-05", "nested duration probe", 75, 8);
    expect(getResponseValue(visitsPostResponse, "id"), 'id').toBeGreaterThan(0);
    expect(getResponseValue(visitsPostResponse, "date"), 'date').toBe("2026-08-05");
    expect(getResponseValue(visitsPostResponse, "description"), 'description').toBe("nested duration probe");
    expect(getResponseValue(visitsPostResponse, "petId"), 'petId').toBe(8);
    expect(getResponseValue(visitsPostResponse, "durationMinutes"), 'durationMinutes').toBe(75);

    const createdVisitId = getResponseValue(visitsPostResponse, "id");

    const owners6GetResponse = await getOwner(client, URL_localhost, 6);
    expect(getResponseValue(owners6GetResponse, "firstName"), 'firstName').toBe("Jean");
    expect(getResponseValue(owners6GetResponse, "lastName"), 'lastName').toBe("Coleman");

    // The Angular owner detail page renders its Duration column from this nested payload,
    // so durationMinutes must survive into owners -> pets -> visits.
    // Pet 8 (Max) is the first pet, and visits come back newest-date-first, so the
    // visit just created for 2026-08-05 is at index 0.
    expect(getResponseValue(owners6GetResponse, "pets.0.name"), 'pets.0.name').toBe("Max");
    expect(getResponseValue(owners6GetResponse, "pets.0.id"), 'pets.0.id').toBe(8);
    expect(getResponseValue(owners6GetResponse, "pets.0.visits.0.id"), 'nested id').toBe(createdVisitId);
    expect(getResponseValue(owners6GetResponse, "pets.0.visits.0.description"), 'nested description').toBe("nested duration probe");
    expect(getResponseValue(owners6GetResponse, "pets.0.visits.0.durationMinutes"), 'nested durationMinutes').toBe(75);
});
