// Generated by Skyramp v1.3.40 on 2026-09-02 07:55:34.272727449 +0000 UTC m=+631.340809429
// Command: skyramp generate contract rest http://localhost:9966/petclinic/api/visits \
// 		--framework junit \
// 		--language java \
// 		--method POST \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--provider \
// 		--provider-output VisitsPostCreatedAtContractTest.java \
// 		--request-data {"petId":1,"date":"2013-01-01","description":"rabies shot"} \
// 		--response-data {"id":1,"petId":1,"date":"2013-01-01","description":"rabies shot","createdAt":"2026-09-02T07:48:00"} \
// 		--response-status-code 201 \
// 		--runtime local \
// 		--skipProvisionParents

import java.util.*;

import static org.junit.jupiter.api.Assertions.*;
import org.junit.jupiter.api.Test;

import static dev.skyramp.api.Skyramp.*;
import dev.skyramp.api.SkyrampClient;
import dev.skyramp.exception.SkyrampException;
import dev.skyramp.model.*;

public final class VisitsPostProviderContractTest {
    // URL for test requests
    String URL = getBaseUrl("SKYRAMP_TEST_BASE_URL", "http://localhost:9966");

    // contract test for /petclinic/api/visits POST
    @Test
    public void testVisitsPost() throws SkyrampException {
        // Invocation of Skyramp Client
        var client = new SkyrampClient();
        // Definition of authentication header
        String token = System.getenv("SKYRAMP_TEST_TOKEN");
        Map<String, String> headers = Map.of();
        if (token != null && !token.isEmpty()) {
            headers = Map.of("Authorization", "Bearer " + token);
        }

        // Request Body
        String visitsPostRequestBody = """
            {
                "date": "2013-01-01",
                "description": "rabies shot",
                "petId": 1
            }
        """;

        // Expected Response Body
        String expectedVisitsPostResponseBody = """
            {
                "createdAt": "2026-09-02T07:48:00",
                "date": "2013-01-01",
                "description": "rabies shot",
                "id": 1,
                "petId": 1
            }
        """;

        // Execute Request
        var visitsPostResponse = client.sendRequest(RequestV2.builder()
            .url(URL)
            .path("/petclinic/api/visits")
            .method("POST")
            .body(visitsPostRequestBody)
            .headers(headers)
            .build());

        // Generated Assertions
        assertTrue(checkStatusCode(visitsPostResponse, "201"));
        assertTrue(checkSchema(visitsPostResponse, expectedVisitsPostResponseBody));
        assertNotNull(getValue(visitsPostResponse, "createdAt"));
        assertNotNull(getValue(visitsPostResponse, "date"));
        assertNotNull(getValue(visitsPostResponse, "description"));
        assertEquals("2013-01-01", String.valueOf(getValue(visitsPostResponse, "date")));
        assertEquals("rabies shot", String.valueOf(getValue(visitsPostResponse, "description")));
        assertEquals(1.0, Double.parseDouble(String.valueOf(getValue(visitsPostResponse, "petId"))));
        assertTrue(Double.parseDouble(String.valueOf(getValue(visitsPostResponse, "id"))) > 0);
        assertTrue(String.valueOf(getValue(visitsPostResponse, "createdAt")).matches("^\\d{4}-\\d{2}-\\d{2}T.*"));
    }
}
