// Generated by Skyramp v1.3.44 on 2026-09-08 19:24:15.431733597 +0000 UTC m=+1940.435338237
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output visits_duration_update_persists_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_visits_duration_update_persists.json

// Import of required libraries
import { test, expect, SkyrampClient, getBaseUrl, getValue, getResponseValue } from '@skyramp/skyramp';
import { createVisit, getVisit, updateVisit, deleteVisit } from './skyrampUtils';

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Request Body
    const visitsPostRequestBody: string = `{
        "date": "2026-12-01",
        "description": "duration update",
        "durationMinutes": 45,
        "petId": 7
    }`;

    const visitsPostResponse = await createVisit(client, visitsPostRequestBody, 201);

    expect(visitsPostResponse.statusCode, 'status code').toBe(201);
    // The visit starts out booked for 45 minutes
    expect(getResponseValue(visitsPostResponse, "id"), 'id').toBeGreaterThan(0);
    expect(getResponseValue(visitsPostResponse, "date"), 'date').toBe("2026-12-01");
    expect(getResponseValue(visitsPostResponse, "description"), 'description').toBe("duration update");
    expect(getResponseValue(visitsPostResponse, "durationMinutes"), 'durationMinutes').toBe(45);
    expect(getResponseValue(visitsPostResponse, "petId"), 'petId').toBe(7);

    // Request Body
    const visitsVisitsPutRequestBody: string = `{
        "date": "2026-12-01",
        "description": "duration update",
        "durationMinutes": 90
    }`;

    const visitsVisitsPutResponse = await updateVisit(
        client,
        getResponseValue(visitsPostResponse, "id"),
        visitsVisitsPutRequestBody,
        204
    );

    expect(visitsVisitsPutResponse.statusCode, 'status code').toBe(204);

    const visitsVisitsGetResponse = await getVisit(
        client,
        getResponseValue(visitsPostResponse, "id"),
        200
    );

    expect(visitsVisitsGetResponse.statusCode, 'status code').toBe(200);
    // The PR promises the appointment length can be changed from the edit form.
    // The duration sent in the PUT must be the duration that comes back.
    expect(getResponseValue(visitsVisitsGetResponse, "id"), 'id').toBe(getResponseValue(visitsPostResponse, "id"));
    expect(getResponseValue(visitsVisitsGetResponse, "durationMinutes"), 'durationMinutes').toBe(90);
    expect(getResponseValue(visitsVisitsGetResponse, "date"), 'date').toBe("2026-12-01");
    expect(getResponseValue(visitsVisitsGetResponse, "description"), 'description').toBe("duration update");
    expect(getResponseValue(visitsVisitsGetResponse, "petId"), 'petId').toBe(7);

    // Request Body
    const visits999999PutRequestBody: string = `{
        "date": "2026-12-01",
        "description": "missing visit",
        "durationMinutes": 60
    }`;

    const visits999999PutResponse = await updateVisit(
        client,
        999999,
        visits999999PutRequestBody,
        404,
        {"date": getResponseValue(visitsVisitsGetResponse, "date")}
    );

    expect(visits999999PutResponse.statusCode, 'status code').toBe(404);

    const visitsVisitsDeleteResponse = await deleteVisit(client, getResponseValue(visitsPostResponse, "id"), 204);

    expect(visitsVisitsDeleteResponse.statusCode, 'status code').toBe(204);
});
