// Generated by Skyramp v1.3.44 on 2026-09-08 19:11:54.673957625 +0000 UTC m=+1191.049287681
// Command: skyramp generate integration rest \
// 		--framework playwright \
// 		--language typescript \
// 		--output visit_description_length_boundary_integration_test.spec.ts \
// 		--output-dir /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp \
// 		--overwrite \
// 		--runtime local \
// 		--trace /home/runner/work/spring-petclinic-angular/spring-petclinic-angular/spring-petclinic-angular/tests/skyramp/scenario_visit_description_length_boundary.json

// Import of required libraries
import { test, expect, SkyrampClient, getResponseValue } from '@skyramp/skyramp';
import { createVisit, deleteVisit, getVisit } from './skyrampUtils';

test('testIntegration', async () => {
    test.setTimeout(60000);

    // Invocation of Skyramp Client
    const client = new SkyrampClient();
    // Request Body
    const visitsPostRequestBody: string = `{
        "date": "2026-09-08",
        "description": "Annual wellness exam and rabie"
    }`;

    // Execute Request
    const visitsPostResponse = await createVisit(client, 1, 1, visitsPostRequestBody);
    expect(visitsPostResponse.statusCode, 'status code').toBe(201);
    expect(getResponseValue(visitsPostResponse, "description"), 'description').toBe("Annual wellness exam and rabie");
    expect(getResponseValue(visitsPostResponse, "petId"), 'petId').toBe(1);
    expect(getResponseValue(visitsPostResponse, "date"), 'date').toBe("2026-09-08");
    expect(getResponseValue(visitsPostResponse, "id"), 'id').toBeGreaterThan(0);

    // Execute Request
    const visitsVisitsGetResponse = await getVisit(client, getResponseValue(visitsPostResponse, "id"));
    expect(visitsVisitsGetResponse.statusCode, 'status code').toBe(200);
    expect(getResponseValue(visitsVisitsGetResponse, "description"), 'description round-trips at 30 characters').toBe("Annual wellness exam and rabie");
    expect(getResponseValue(visitsVisitsGetResponse, "id"), 'id').toBe(getResponseValue(visitsPostResponse, "id"));
    expect(getResponseValue(visitsVisitsGetResponse, "petId"), 'petId').toBe(1);
    expect(getResponseValue(visitsVisitsGetResponse, "date"), 'date').toBe("2026-09-08");

    // Request Body
    const visitsPost1RequestBody: string = `{
        "date": "2026-09-08",
        "description": "Annual wellness exam and rabies"
    }`;

    // Request Body
    const visitsPost2RequestBody: string = `{
        "date": "2026-09-08",
        "description": ""
    }`;

    // Request Body
    const visitsPost3RequestBody: string = `{
        "date": "2026-09-08"
    }`;

    const [visitsPost1Response, visitsPost2Response, visitsPost3Response] = await Promise.all([
        createVisit(client, 1, 1, visitsPost1RequestBody, {"date": getResponseValue(visitsVisitsGetResponse, "date")}, 400),
        createVisit(client, 1, 1, visitsPost2RequestBody, {"date": getResponseValue(visitsVisitsGetResponse, "date")}, 400),
        createVisit(client, 1, 1, visitsPost3RequestBody, {"date": getResponseValue(visitsVisitsGetResponse, "date")}, 400),
    ]);

    // 31 characters -- the first rejected length.
    expect(visitsPost1Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(visitsPost1Response, "status"), 'status').toBe(400);
    expect(getResponseValue(visitsPost1Response, "title"), 'title').toBe("MethodArgumentNotValidException");
    expect(getResponseValue(visitsPost1Response, "detail"), 'detail').toBe("The request contains invalid or missing parameters");
    expect(getResponseValue(visitsPost1Response, "schemaValidationErrors.0.field"), 'rejected field').toBe("description");
    expect(getResponseValue(visitsPost1Response, "schemaValidationErrors.0.defaultMessage"), 'rejection reason').toBe("size must be between 1 and 30");
    expect(getResponseValue(visitsPost1Response, "schemaValidationErrors.1"), 'only one validation error').toBeNull();

    // Empty description -- rejected by the same minLength/maxLength constraint.
    expect(visitsPost2Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(visitsPost2Response, "status"), 'status').toBe(400);
    expect(getResponseValue(visitsPost2Response, "title"), 'title').toBe("MethodArgumentNotValidException");
    expect(getResponseValue(visitsPost2Response, "detail"), 'detail').toBe("The request contains invalid or missing parameters");
    expect(getResponseValue(visitsPost2Response, "schemaValidationErrors.0.field"), 'rejected field').toBe("description");
    expect(getResponseValue(visitsPost2Response, "schemaValidationErrors.0.defaultMessage"), 'rejection reason').toBe("size must be between 1 and 30");
    expect(getResponseValue(visitsPost2Response, "schemaValidationErrors.1"), 'only one validation error').toBeNull();

    // Omitted description -- rejected as null rather than as a length violation.
    expect(visitsPost3Response.statusCode, 'status code').toBe(400);
    expect(getResponseValue(visitsPost3Response, "status"), 'status').toBe(400);
    expect(getResponseValue(visitsPost3Response, "title"), 'title').toBe("MethodArgumentNotValidException");
    expect(getResponseValue(visitsPost3Response, "detail"), 'detail').toBe("The request contains invalid or missing parameters");
    expect(getResponseValue(visitsPost3Response, "schemaValidationErrors.0.field"), 'rejected field').toBe("description");
    expect(getResponseValue(visitsPost3Response, "schemaValidationErrors.0.defaultMessage"), 'rejection reason').toBe("must not be null");
    expect(getResponseValue(visitsPost3Response, "schemaValidationErrors.1"), 'only one validation error').toBeNull();

    // Request Body
    const pets999999VisitsPostRequestBody: string = `{
        "date": "2026-09-08",
        "description": "Annual wellness exam and rabie"
    }`;

    // Execute Request
    const pets999999VisitsPostResponse = await createVisit(
        client,
        1,
        999999,
        pets999999VisitsPostRequestBody,
        {
            "date": getResponseValue(visitsVisitsGetResponse, "date"),
            "description": getResponseValue(visitsVisitsGetResponse, "description")
        },
        404
    );
    expect(pets999999VisitsPostResponse.statusCode, 'status code').toBe(404);
    expect(getResponseValue(pets999999VisitsPostResponse, "status"), 'status').toBe(404);
    expect(getResponseValue(pets999999VisitsPostResponse, "title"), 'title').toBe("DataIntegrityViolationException");
    expect(getResponseValue(pets999999VisitsPostResponse, "detail"), 'detail').toBe("The requested resource could not be processed due to a data constraint violation");

    // Execute Request
    const visitsVisitsDeleteResponse = await deleteVisit(client, getResponseValue(visitsPostResponse, "id"));
    expect(visitsVisitsDeleteResponse.statusCode, 'status code').toBe(204);
});
